/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/math_consts.h"
#include "asm.h"
#include "sda.h"
#include "rnc/gameplay/entities/moby.h"

/* per-frame level ambience (wind/sway) state machine: picks a random target, then eases toward it */
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002A5B20), where it is exact; names translated to the US level program. */

struct Amb {
    float f0;
    float f4;
    float f8;
    short hC;
    short hE;
    float f10;
    float f14;
    float f18;
    short h1C;
    short h1E;
};

extern f32 convert_integer_to_float(s32) __asm__("func_001FA6C0");
extern float D_0015ED6C;
extern float fast_add_rotations(float, float) __asm__("FUN_001fa580");
extern float fast_subtract_rotations(float, float) __asm__("FUN_001fa5c8");
extern float FUN_001f96b0(float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001f9770(void *);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern struct Amb D_L00_001CB7C0;
float absolute_float(float input) __asm__("func_001F99C0");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L00_002a4890(void) {
    struct Amb *s = &D_L00_001CB7C0;
    float a, b, c, d, e;
    switch (s->hC) {
    case 1:
        break;
    case 2:
        switch (s->hE) {
        case 0:
            if (FUN_001f9770(&s->h1E)) {
                a = convert_integer_to_float(s->h1C) * random_float_between_alt(0.5f, 1.5f);
                c = fast_add_rotations(s->f0, random_float_between_alt(-1.0471976f, 1.0471976f));
                b = random_float_between_alt(s->f10 * 0.5f, s->f10 * 1.5f);
                s->f8 = fast_subtract_rotations(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 1;
            }
            break;
        case 1:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(convert_integer_to_float(s->h1C) *
                                         random_float_between_alt(2.0f, 3.0f));
                s->hE = 0;
            } else {
                s->f4 = fast_add_rotations(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = absolute_float(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f)
                        e = -e;
                    s->f14 = e;
                }
            }
            break;
        }
        break;
    case 3:
        switch (s->hE) {
        case 0:
            if (FUN_001f9770(&s->h1E)) {
                a = FUN_001f96b0(random_float_between_alt(45.0f, 60.0f));
                c = fast_add_rotations(s->f0, random_float_between_alt(-1.5707964f, 1.5707964f));
                b = random_float_between_alt(s->f10 * 1.5f, s->f10 + s->f10);
                s->f8 = fast_subtract_rotations(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 1;
            }
            break;
        case 1:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(convert_integer_to_float(s->h1C) *
                                         random_float_between_alt(1.0f, 1.5f));
                s->hE = 2;
            } else {
                s->f4 = fast_add_rotations(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = absolute_float(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f)
                        e = -e;
                    s->f14 = e;
                }
            }
            break;
        case 2:
            if (FUN_001f9770(&s->h1E)) {
                a = FUN_001f96b0(random_float_between_alt(45.0f, 60.0f));
                c = fast_add_rotations(s->f0, random_float_between_alt(-0.785398f, 0.785398f));
                b = random_float_between_alt(s->f10 * 0.8f, s->f10 * 1.2f);
                s->f8 = fast_subtract_rotations(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 3;
            }
            break;
        case 3:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(convert_integer_to_float(s->h1C) *
                                         random_float_between_alt(3.0f, 5.0f));
                s->hE = 0;
            } else {
                s->f4 = fast_add_rotations(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = absolute_float(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f)
                        e = -e;
                    s->f14 = e;
                }
            }
            break;
        }
        break;
    }
}
extern int D_L00_00161390;
extern int D_L00_00161368 __attribute__((sda));
extern int D_L00_0016136C __attribute__((sda));
extern int D_L00_00161370 __attribute__((sda));
extern int D_L00_0016137C __attribute__((sda));
extern int D_L00_00161380 __attribute__((sda));
extern int D_L00_00161388;
extern float D_L00_00161374 __attribute__((sda));
extern float D_L00_00161378 __attribute__((sda));
extern float D_L00_00161384 __attribute__((sda));
extern float D_L00_0016138C __attribute__((sda));
extern float D_0015ED60;
int scale_game_frames(int) __asm__("FUN_001f96f8");
float FUN_001fa6c0(int);
void FUN_L00_002a4cd8(unsigned char *p) {
    float one;
    int r;
    switch (p[0x20]) {
    case 0:
        D_L00_00161390 = 0;
        p[0x20] = 1;
        p[0x30] = 0xFF;
        one = 1.0f;
        D_L00_0016137C = scale_game_frames(D_L00_00161368);
        r = scale_game_frames(D_L00_0016136C);
        D_L00_00161380 = r;
        D_L00_00161384 = one / FUN_001fa6c0(r);
        r = scale_game_frames(D_L00_00161370);
        D_L00_00161388 = r;
        D_L00_0016138C = one / (float)r;
        break;
    case 1:
        D_L00_00161374 -= D_L00_00161378 * D_0015ED60;
        if (D_L00_00161374 <= -8.0f)
            D_L00_00161374 += 8.0f;
        break;
    }
}
int FUN_L00_002a4dc8(int a) {
    int t = D_L00_00161390;
    D_L00_00161390 = t + a;
    return t;
}
#include "eetypes.h"
#include "qcopy.h"
#include "rnc/overlay/quad.h"
unsigned char *create_moby(int) __asm__("FUN_0020c4f8");
void FUN_L00_00250df8(unsigned char *);
/* Creates a class 0x3EF moby at v and runs FUN_L00_00250df8 on it. */
unsigned char *FUN_L00_002a4de0(u128 *v) {
    unsigned char *m = create_moby(0x3ef);
    if (m) {
        m[0x30] = 0xff;
        *(unsigned short *)(m + 0x34) |= 0x41;
        qcopy(m + 0x10, v);
        FUN_L00_00250df8(m);
    }
    return m;
}
typedef struct {
    char p0[0x98];
    float f98;
    char p1[0x164 - 0x9C];
    float f164;
    char p2[0x2080 - 0x168];
    char *obj;
    char p3[0x208C - 0x2084];
    int w208C;
} G_2a4e48;
typedef struct {
    char p0[0x158];
    float f158;
    char p1[0x180 - 0x15C];
    char *c;
} C_2a4e48;
extern C_2a4e48 D_166C80_2a4e48 __asm__("D_L00_00166C80") __attribute__((section(".data")));
extern float D_0015ED6C_2a4e48 __asm__("D_0015ED6C");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern float dot_vectors_xyz(void *, void *) __asm__("FUN_001f9ab0");
extern void f9a68_2a4e48(void *, void *, float) __asm__("FUN_001f9a68");
extern float vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern float fast_difference_between_rotations(float, float) __asm__("FUN_001fa688");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");

void FUN_L00_002a4e48(char *o) {
    OvlQuad d[1];
    OvlQuad e[1];
    C_2a4e48 *C = &D_166C80_2a4e48;
    char *s;
    char *pos;
    G_2a4e48 *P;
    float f;

    if (C->c != 0) {
        s = o + 0x10;
        qcopy(s, C->c + 0x30);
        pos = (char *)&hero.motion.pos;
        subtract_vector_xyz(d, s, pos);
        P = (G_2a4e48 *)(pos - 0x80);
        f = dot_vectors_xyz(d, P->obj + 0xE0);
        f9a68_2a4e48(e, P->obj + 0xE0, f);
        subtract_vector_xyz(d, d, e);
        if (absolute_float(f) < 2.5f) {
            f = 0.1f;
            if (vector_length_xyz(d) < f || fast_difference_between_rotations(P->f98, C->f158) < 2.3561945f ||
                P->f164 < D_0015ED6C_2a4e48 * f) {
                *(float *)(o + 0x18) = 15.0f;
                *(float *)(o + 0x14) = 15.0f;
                *(float *)(o + 0x10) = 15.0f;
            } else {
                f = dot_vectors_xyz(s, P->obj + 0xE0);
                f9a68_2a4e48(e, P->obj + 0xE0, f);
                subtract_vector_xyz(d, s, e);
                f = dot_vectors_xyz(pos, P->obj + 0xE0);
                if (P->w208C != 0x11) {
                    f9a68_2a4e48(e, P->obj + 0xE0, f);
                    add_vector_xyz(s, d, e);
                }
            }
        }
    } else {
        *(float *)(o + 0x18) = 5.0f;
        *(float *)(o + 0x14) = 5.0f;
        *(float *)(o + 0x10) = 5.0f;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a5040.s", FUN_L00_002a5040);
typedef struct {
    f32 f[4];
} V_2a57a8;
typedef struct {
    u8 p0[0x24];
    f32 f24;
} N_2a57a8;
typedef struct {
    u8 p0[0x10];
    f32 f10, f14, f18;
    u8 p1C[0x24 - 0x1C];
    N_2a57a8 *p24;
    u8 p28[4];
    f32 f2C;
    u8 p30[2];
    u16 h32;
    u16 h34;
    u8 p36[0x73 - 0x36];
    u8 b73;
} M_2a57a8;
typedef struct {
    s32 i0, i4;
    u8 p8[4];
    M_2a57a8 *mC;
    u8 p10[0x90 - 0x10];
    f32 f90;
} Q_2a57a8;
typedef struct {
    u8 p0[0x10];
    f32 f10, f14, f18;
    u8 p1C[4];
    u8 b20;
    u8 p21[0x52 - 0x21];
    u8 b52, b53;
    u8 p54[0x78 - 0x54];
    Q_2a57a8 *q;
    u8 p7C[0x90 - 0x7C];
    s32 i90;
} P_2a57a8;
typedef struct {
    u8 p0[0x80];
    f32 f80, f84;
    u8 p88[0x98 - 0x88];
    f32 f98;
    u8 p9C[0x2084 - 0x9C];
    s32 i2084;
    u8 p2088[4];
    s32 i208C;
    u8 p2090[0x20A4 - 0x2090];
    u8 b20A4;
} G_2a57a8;
extern struct Hero hero_data __asm__("D_0013F350") __attribute__((section(".data")));
extern V_2a57a8 D_0013F3D0_2a57a8 __asm__("D_0013F3D0") __attribute__((section(".data")));
extern s32 D_0013CAE4_2a57a8 __asm__("D_0013CAE4") __attribute__((section(".data")));
extern s32 D_L00_0015F5CC_2a57a8 __asm__("D_L00_0015F5CC");
extern f32 D_L00_001613A4_2a57a8 __asm__("D_L00_001613A4") __attribute__((sda));
extern f32 D_L00_0016139C_2a57a8 __asm__("D_L00_0016139C") __attribute__((sda));
extern f32 D_L00_001613A0_2a57a8 __asm__("D_L00_001613A0") __attribute__((sda));
f32 fast_sin(f32) __asm__("FUN_001f9de0");
M_2a57a8 *FUN_0020c4f8_2a57a8(s32) __asm__("FUN_0020c4f8");
void attach_manipulator(M_2a57a8 *, s32, void *) __asm__("FUN_0020cb10");
f32 vector_distance(void *, void *) __asm__("FUN_001f9b80");
f32 FUN_001f99c0_2a57a8(f32) __asm__("FUN_001f99c0");
void blend_moby_animation_u(P_2a57a8 *, s32, s32, s32) __asm__("FUN_00212f90");
void FUN_L00_002a5040_2a57a8(void) __asm__("FUN_L00_002a5040");
void enqueue_callback_list_1(void *, P_2a57a8 *) __asm__("FUN_001f4600");
void FUN_L00_001fff28_2a57a8(void *, s32, f32) __asm__("FUN_L00_001fff28");
f32 FUN_001fa580_2a57a8(f32, f32) __asm__("FUN_001fa580");
void upd_a(M_2a57a8 *) __asm__("FUN_L00_00250df8");
f32 angle_atan2(f32, f32) __asm__("FUN_001f9e90");
f32 FUN_001fa688_2a57a8(f32, f32) __asm__("FUN_001fa688");
s32 try_set_help_message(s32, s32) __asm__("FUN_00215130");
void FUN_L00_0029a6b0_2a57a8(P_2a57a8 *) __asm__("FUN_L00_0029a6b0");

void FUN_L00_002a57a8(P_2a57a8 *p) {
    Q_2a57a8 *q = p->q;
    s32 i, a, b, c;
    u8 *v;
    f32 d, z;

    D_L00_001613A4_2a57a8 += 0.05f;
    if (D_L00_001613A4_2a57a8 > 3.14f)
        D_L00_001613A4_2a57a8 = -3.14f;
    p->i90 =
        (((s32)(fast_sin(D_L00_001613A4_2a57a8) * 48.0f) + 0x60) * 0x10101) | 0x80000000;
    switch (p->b20) {
    case 0:
        p->b20 = 1;
        q->i0 = 0;
        q->i4 = 0;
        q->mC = FUN_0020c4f8_2a57a8(0x477);
        q->mC->h34 |= 2;
        q->mC->h32 = 0x40;
        q->mC->f10 = p->f10;
        q->mC->f14 = p->f14;
        q->mC->f18 = p->f18 + 2.95f;
        q->mC->b73 = 0x20;
        q->f90 = 0.0f;
        for (i = 0; i < 2; i++) {
            attach_manipulator(q->mC, i, (u8 *)q + 0x10 + i * 0x40);
        }
        upd_a(q->mC);
        break;
    case 1:
        if (q->f90 > 0.0f)
            q->f90 -= 0.1f;
        if (q->f90 <= 0.0f)
            q->mC->h34 |= 1;
        if (!(D_L00_0015F5CC_2a57a8 & 7) &&
            vector_distance(&p->f10, &D_0013F3D0_2a57a8) <= 16.0f &&
            FUN_001f99c0_2a57a8(p->f18 - D_0013F3D0_2a57a8.f[2]) <= 8.0f) {
            p->b20 = 2;
            if (p->b53 != 1)
                blend_moby_animation_u(p, 1, 0, 10);
            q->mC->h34 &= 0xFFFE;
        }
        enqueue_callback_list_1(FUN_L00_002a5040_2a57a8, p);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x20, 2, D_L00_0016139C_2a57a8);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x60, 2, D_L00_001613A0_2a57a8);
        D_L00_0016139C_2a57a8 = FUN_001fa580_2a57a8(D_L00_0016139C_2a57a8, 0.01f);
        D_L00_001613A0_2a57a8 = FUN_001fa580_2a57a8(D_L00_001613A0_2a57a8, -0.02f);
        q->mC->f2C = q->f90 * q->mC->p24->f24 * 2.5f;
        upd_a(q->mC);
        break;
    case 2:
        if (q->f90 < 1.0f)
            q->f90 += 0.1f;
        d = vector_distance(&p->f10, &D_0013F3D0_2a57a8);
        z = FUN_001f99c0_2a57a8(p->f18 - D_0013F3D0_2a57a8.f[2]);
        if (!(D_L00_0015F5CC_2a57a8 & 7) && (d > 18.0f || z > 10.0f)) {
            p->b20 = 1;
            if (p->b53)
                blend_moby_animation_u(p, 0, 0, 10);
            break;
        }
        enqueue_callback_list_1(FUN_L00_002a5040_2a57a8, p);
        a = 1;
        b = 1;
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x20, 2, D_L00_0016139C_2a57a8);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x60, 2, D_L00_001613A0_2a57a8);
        D_L00_0016139C_2a57a8 = FUN_001fa580_2a57a8(D_L00_0016139C_2a57a8, 0.01f);
        D_L00_001613A0_2a57a8 = FUN_001fa580_2a57a8(D_L00_001613A0_2a57a8, -0.02f);
        q->mC->f2C = q->f90 * q->mC->p24->f24 * 2.5f;
        upd_a(q->mC);
        if (hero_data.state.control_mode != 0 && hero_data.state.current != 3 && hero_data.state.control_mode != 1) {
            a = 0;
            b = 0;
        }
        if (hero_data.state.current == 0x1D || hero_data.state.current == 0x32) {
            a = 0;
            b = 0;
        }
        if (hero_data.unk20A4) {
            a = 0;
            b = 0;
        }
        if (p->b52 != 1)
            a = 0;
        if (d > 4.0f || z > 2.0f) {
            a = 0;
            b = 0;
        }
        if (FUN_001fa688_2a57a8(hero_data.motion.rot.f[2], angle_atan2(p->f10 - hero_data.motion.pos.f[0],
                                                                   p->f14 - hero_data.motion.pos.f[1])) >
            1.5707964f) {
            a = 0;
            b = 0;
        }
        c = 0;
        if (b)
            c = try_set_help_message(1, 0x53E3) != 0;
        if ((D_0013CAE4_2a57a8 & 0x10) && a && c) {
            FUN_L00_0029a6b0_2a57a8(p);
            p->b20 = 3;
        }
        break;
    case 3:
        if (q->mC) {
            q->f90 = 0.0f;
            q->mC->f2C = q->mC->p24->f24 * q->f90 * 2.5f;
            upd_a(q->mC);
        }
        break;
    }
}
#include "qcopy.h"
#include "rnc/math/vector.h"
#include "rnc/gameplay/hero.h"
#include "rnc/overlay/collision.h"

typedef struct {
    u8 pad0[0x24];
    f32 scale; /* 0x24 */
} BoltClass;

struct Bolt;

typedef struct {
    Vec4 pos;            /* 0x00 */
    Vec4 rot;            /* 0x10 */
    Vec4 vel;            /* 0x20 */
    Vec4 spin;           /* 0x30 */
    u8 pad40[8];
    f32 unk48;           /* 0x48 */
    f32 unk4C;           /* 0x4C */
    f32 unk50;           /* 0x50 */
    u8 landed;           /* 0x54 */
    u8 unk55;            /* 0x55 */
    u8 hop_frames;       /* 0x56 */
    u8 hop_left;         /* 0x57 */
    f32 unk58;           /* 0x58 */
    void *ground_moby;   /* 0x5C */
    struct Bolt *unk60;  /* 0x60 */
    f32 speed;           /* 0x64 */
    f32 ground_z;        /* 0x68 */
    s16 slot;            /* 0x6C */
    s16 slot_timer;      /* 0x6E */
} BoltVars;

typedef struct Bolt {
    u8 pad0[0x10];
    Vec4 pos;            /* 0x10 */
    u8 state;            /* 0x20 */
    u8 pad21[3];
    BoltClass *pclass;   /* 0x24 */
    u8 pad28[4];
    f32 scale;           /* 0x2C */
    u8 unk30;            /* 0x30 */
    u8 unk31;            /* 0x31 */
    u16 unk32;           /* 0x32 */
    u16 flags;           /* 0x34 */
    u8 pad36[0x3D];
    u8 unk73;            /* 0x73 */
    u8 pad74[4];
    BoltVars *vars;      /* 0x78 */
    u8 pad7C[0x2A];
    s16 oclass;          /* 0xA6 */
    u8 padA8[8];
    u8 unkB0;            /* 0xB0 */
    u8 padB1;
    s16 unkB2;           /* 0xB2 */
    u8 padB4[0xC];
    Vec4 rot;            /* 0xC0 */
    u8 padD0[0x10];
    Vec4 unkE0;          /* 0xE0 */
} Bolt;

typedef struct {
    u8 pad0[0x454];
    u8 killed[1];   /* 0x454: indexed by the moby save id */
} MobyKillTable;

typedef struct {
    Vec4 pos;
    s16 pad10[2];
    s16 moby;            /* 0x14 */
    u8 pad16[0xA];
} BoltTrailSlot;

extern s32 D_L00_0015F5C4;
extern CollisionHit D_L00_00173E40 __attribute__((section(".data")));
extern Vec4 D_L00_001D73D0[];
extern BoltTrailSlot D_L00_0016EA40[];
extern u8 *D_L00_0015FFDC;
extern s32 D_L00_0015FFBC;
extern u8 *D_L00_0015FFD8;
extern u8 D_L00_0015FC88[] __attribute__((section(".sdata")));
extern s32 D_0015ED84;
extern MobyKillTable D_L00_001BA5D0 __attribute__((section(".data")));
extern MobyKillTable D_L00_001BB230 __attribute__((section(".data")));
extern u8 D_0014C050[][16];
extern f32 D_0015ED70;
extern f32 D_0015ED6C;

extern s32 FUN_00213260(s32);
extern f32 FUN_00213308(void);
extern f32 FUN_002132a8(f32, f32);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a40(void *, void *, void *, f32);
extern void FUN_001f9a28(void *, void *, void *);
extern f32 FUN_001f9af0(void *);
extern f32 FUN_001f9b80(void *, void *);
extern f32 FUN_001f9b20(void *);
extern void FUN_001f9bf8(void *, void *, f32);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_001f9d20(void *, void *, void *);
extern f32 FUN_001f9e90(f32, f32);
extern void FUN_001f99f8(void *);
extern f32 FUN_001f99c0(f32);
extern f32 FUN_001f96b0(f32);
extern s32 FUN_001f96f8(s32);
extern void FUN_001fa030(void *, void *);
extern void FUN_001fa328(void *, void *, void *);
extern void FUN_001fa400(void *, void *, void *, f32);
extern void FUN_001fa480(void *, void *);
extern f32 FUN_001fa6c0(s32);
extern s32 FUN_001fa6d0(f32);
extern s32 FUN_001efa68(void *, void *, s32, s32, s32);
extern void FUN_00214598(void *, void *);
extern void FUN_00213ed8(void *, f32, f32);
extern void FUN_0020c828(void *);
extern s32 FUN_L00_001f0d60(void *, s32, void *, f32);
extern void FUN_L00_001ff660(void *, void *, void *);
extern s32 FUN_L00_001fe990(void *, s32, f32);
extern s32 FUN_L00_002603d0(void *);
extern void FUN_L00_00260668(void *, void *, void *, void *, void *, void *);
extern s32 FUN_L00_00257b90(s32, s32);
extern void FUN_L00_00259f50(void *, void *);
extern void FUN_L00_0025f730(void *, f32);
extern void FUN_L00_002a6de8_c(Bolt *, void *, s32) __asm__("FUN_L00_002a6de8");
extern void FUN_L00_002a6b70_c(Bolt *) __asm__("FUN_L00_002a6b70");
extern void FUN_L00_002a7210_c(Bolt *, void *, f32, f32) __asm__("FUN_L00_002a7210");

void FUN_L00_002a5dd8(Bolt *obj) {
    BoltVars *v = obj->vars;
    Vec4 a;
    Vec4 b;
    Vec4 c;
    Vec4 d;
    Vec4 e;
    Vec4 m[3];
    s32 hit;
    f32 sc;
    f32 hr;
    f32 ang;
    f32 k;
    f32 t;
    f32 u;
    f32 h;
    f32 dist;
    f32 x;
    f32 s;
    s32 flag;
    u8 i;

    if (D_L00_0015F5C4 == 2) {
        obj->unk31 = 0;
        obj->flags |= 1;
    } else {
        obj->unk31 = 1;
        obj->flags &= 0xFFFE;
    }
    switch (obj->state) {
    case 0:
        obj->state = 3;
        obj->unk73 = 0x14;
        obj->flags |= 0x100;
        obj->unk30 = 0x20;
        obj->unk32 = 0x20;
        if (FUN_00213260(2) == 0) {
            v->unk55 |= 1;
        }
        FUN_001f9bf8(&a, &obj->unkE0, 0.2f);
        FUN_001f9a10(&a, &a, &obj->pos);
        FUN_001f9bf8(&b, &obj->unkE0, -3.0f);
        FUN_001f9a10(&b, &b, &obj->pos);
        hit = FUN_001efa68(&a, &b, 0x22, 0, 0);
        if (v->landed == 0 && hit != 0) {
            qcopy(&v->pos, &D_L00_00173E40.point);
            FUN_001f99f8(&v->rot);
            v->rot.f[2] = FUN_001f9e90(D_L00_00173E40.normal_x, D_L00_00173E40.normal_y);
            v->rot.f[1] = FUN_001f9e90(D_L00_00173E40.normal_z, FUN_001f9b20(&D_L00_00173E40.normal_x));
            if (D_L00_00173E40.moby != 0 && FUN_L00_002603d0((void *)D_L00_00173E40.moby) != 0) {
                void *gm = (void *)D_L00_00173E40.moby;
                v->ground_moby = gm;
                FUN_L00_00260668(obj, gm, v, &v->rot, v, &v->rot);
            }
        } else {
            qcopy(&v->pos, &obj->pos);
            FUN_001f99f8(&v->rot);
        }
        v->unk50 = FUN_00213308();
        v->unk58 = FUN_00213308();
        v->ground_z = obj->pos.f[2];
        v->slot_timer = FUN_L00_00257b90(0, FUN_001f96f8(600));
        v->slot = -1;
        switch (obj->oclass) {
        case 0xD:
            obj->scale = obj->pclass->scale * 0.65f;
            break;
        case 0xE:
            obj->scale = obj->pclass->scale * 0.7f;
            break;
        case 0xF:
            obj->scale = obj->pclass->scale * 0.75f;
            break;
        case 0x10:
            obj->scale = obj->pclass->scale * 0.6f;
            break;
        }
        break;
    case 1:
        v->vel.f[2] -= D_0015ED70 * 10.8f;
        FUN_001f9a10(&obj->pos, &obj->pos, &v->vel);
        FUN_001fa480(&v->spin, &c);
        FUN_001fa328(&obj->rot, &c, &obj->rot);
        switch (obj->oclass) {
        case 0xD:
            hr = 0.15f;
            break;
        case 0xE:
            hr = 0.23f;
            break;
        case 0xF:
            hr = 0.23f;
            break;
        default:
            hr = 0.25f;
            break;
        }
        if (obj->pos.f[2] < v->ground_z - 2.0f && obj->pos.f[2] < hero.motion.pos.f[2] - 2.0f) {
            FUN_L00_002a7210_c(obj, hero.moby, FUN_002132a8(-15.0f, 15.0f) * 0.017453292f, 0.0f);
            return;
        }
        if (FUN_L00_001f0d60(&obj->pos, 0x22, obj, hr) == 0) {
            return;
        }
        qcopy(&v->pos, &D_L00_00173E40.point);
        FUN_001f99f8(&v->rot);
        v->rot.f[2] = FUN_001f9e90(D_L00_00173E40.normal_x, D_L00_00173E40.normal_y);
        v->rot.f[1] = FUN_001f9e90(D_L00_00173E40.normal_z, FUN_001f9b20(&D_L00_00173E40.normal_x));
        FUN_001f9a28(&a, &obj->pos, &D_L00_00173E40.point);
        FUN_L00_001ff660(&v->vel, &v->vel, &a);
        if (FUN_001f9b80(&obj->pos, &hero.motion.pos) < hero.unk2288 &&
            FUN_001f99c0(obj->pos.f[2] - hero.motion.pos.f[2]) < hero.unk228C) {
            if (hero.health.hp == 0) {
                return;
            }
            FUN_001f9bf8(&v->vel, &v->vel, FUN_002132a8(3.0f, 7.0f) * D_0015ED6C);
            FUN_L00_002a7210_c(obj, hero.moby, 0.0f, 0.0f);
            return;
        }
        ang = 0.7853982f;
        if (!(FUN_001f9e90(a.f[2], FUN_001f9b20(&a)) < ang)) {
            return;
        }
        if (!(FUN_001f9e90(D_L00_00173E40.normal_z, FUN_001f9b20(&D_L00_00173E40.normal_x)) < ang)) {
            return;
        }
        obj->state = 2;
        v->hop_frames = v->hop_left = FUN_001fa6d0(FUN_001f96b0(FUN_002132a8(30.0f, 40.0f)));
        if (D_L00_00173E40.moby != 0 && FUN_L00_002603d0((void *)D_L00_00173E40.moby) != 0) {
            void *gm = (void *)D_L00_00173E40.moby;
            v->ground_moby = gm;
            FUN_L00_00260668(obj, gm, v, &v->rot, v, &v->rot);
        }
        FUN_00214598(&obj->rot, &b);
        FUN_L00_00259f50(&v->spin, &b);
        return;
    case 2:
        FUN_L00_002a6de8_c(obj, &b, 0);
        k = 0.25f;
        b.f[2] += k;
        FUN_00214598(&obj->rot, &a);
        FUN_L00_00259f50(&c, &a);
        s = 1.0f / FUN_001fa6c0(v->hop_left);
        h = FUN_001fa6c0(v->hop_left) / FUN_001fa6c0(v->hop_frames);
        FUN_001fa400(&v->spin, &v->spin, &c, s);
        FUN_001f9a40(&obj->pos, &obj->pos, &b, h);
        h -= 0.5f;
        obj->pos.f[2] += -(h * h - k) * ((f32)v->hop_frames * 0.025f);
        FUN_001fa480(&v->spin, &obj->rot);
        if (--v->hop_left != 0) {
            return;
        }
        obj->state = 3;
        v->hop_frames = v->hop_left = FUN_001fa6d0(FUN_001f96b0(FUN_002132a8(10.0f, 20.0f)));
        return;
    case 3:
        dist = FUN_001f9b80(&obj->pos, &hero.motion.pos);
        if (dist < hero.unk2288 && FUN_001f99c0(obj->pos.f[2] - hero.motion.pos.f[2]) < hero.unk228C) {
            FUN_L00_002a7210_c(obj, hero.moby, 0.0f, 0.0f);
            return;
        }
        if ((u8 *)obj > D_L00_0015FFDC && D_L00_0015FFBC < 200 && 48.0f < dist && obj->unk31 == 0) {
            FUN_0020c828(obj);
            return;
        }
        if (obj->unk31 != 0 || v->ground_moby != 0) {
        FUN_L00_002a6de8_c(obj, 0, 0);
        if (v->hop_left != 0) {
            u = FUN_001fa6c0(v->hop_left) / FUN_001fa6c0(v->hop_frames);
            u -= 0.5f;
            obj->pos.f[2] += -(u * u - 0.25f) * ((f32)v->hop_frames * 0.0125f);
            v->hop_left--;
        }
        if (v->slot >= 0) {
            FUN_001f9cf8(&a, &D_L00_001D73D0[obj->oclass], &obj->rot);
            FUN_001f9a10(&D_L00_0016EA40[v->slot], &a, &obj->pos);
            if (D_L00_0016EA40[v->slot].moby != (((u8 *)obj - D_L00_0015FFD8) >> 8)) {
                v->slot = -1;
            }
            return;
        }
        if (--v->slot_timer > 0) {
            return;
        }
        FUN_001f9cf8(&a, &D_L00_001D73D0[obj->oclass], &obj->rot);
        FUN_001f9a10(&a, &a, &obj->pos);
        v->slot = FUN_L00_001fe990(&a, ((u8 *)obj - D_L00_0015FFD8) >> 8, 1.4f);
        v->slot_timer = FUN_L00_00257b90(FUN_001f96f8(300), FUN_001f96f8(600));
        } else if (v->hop_left != 0) {
            v->hop_left--;
        }
        return;
    case 4:
        flag = 0;
        if (v->unk60->oclass == 0) {
            FUN_001f9a28(&a, &obj->pos, &hero.ground_point);
            FUN_001f9d20(&a, &a, hero.unk40);
            if (a.f[2] < 0.0f) {
                flag = 1;
            }
        }
        if (flag) {
            FUN_001f9bf8(&a, &hero.unk0[8], D_0015ED6C * 7.0f);
            FUN_001f9a28(&b, &a, &v->vel);
            FUN_L00_0025f730(&b, D_0015ED70 * 50.0f);
            FUN_001f9a10(&v->vel, &v->vel, &b);
        } else {
            t = D_0015ED70 * 10.0f;
            if (t < FUN_001f9af0(&v->vel)) {
                FUN_001f9bf8(&a, &v->vel, t);
                FUN_001f9a28(&v->vel, &v->vel, &a);
            }
            FUN_00213ed8(&v->speed, D_0015ED6C * 48.0f, D_0015ED70 * 16.0f);
            x = D_0015ED6C * 8.0f;
            if (x < hero.motion.speed_xy) {
                FUN_001f9bf8(&b, &hero.motion.unk100, (hero.motion.speed_xy - x) * 0.5f);
                FUN_001f9a10(&obj->pos, &obj->pos, &b);
            }
        }
        FUN_001fa480(&v->spin, &a);
        FUN_001fa328(&obj->rot, &a, &obj->rot);
        FUN_001f9a10(&obj->pos, &obj->pos, &v->vel);
        FUN_001f9a28(&d, &hero.motion.unkD0, &obj->pos);
        if (v->speed < FUN_001f9af0(&d)) {
            if (!(v->unk4C == 0.0f && v->unk48 == 0.0f)) {
                FUN_001f9cf8(&d, &d, hero.unk40);
                FUN_001f99f8(&e);
                e.f[1] = v->unk48;
                e.f[2] = v->unk4C;
                FUN_001fa030(m, &e);
                FUN_001f9cf8(&d, &d, m);
                FUN_001f9cf8(&d, &d, hero.unk0);
            }
            FUN_001f9bf8(&d, &d, v->speed);
            FUN_001f9a10(&obj->pos, &obj->pos, &d);
            return;
        }
        FUN_L00_002a6b70_c(obj);
        if ((u8 *)obj < D_L00_0015FFDC) {
            D_L00_001BA5D0.killed[obj->unkB2] = obj->unkB0 + 2;
            if (obj->unkB0 == 0xFF || (D_L00_0015FC88[obj->unkB0] != 0xFF && D_0014C050[D_0015ED84][obj->unkB0] == 0xFF)) {
                D_L00_001BB230.killed[obj->unkB2] = obj->unkB0 + 2;
            }
        }
        FUN_0020c828(obj);
        return;
    }
}
/* What a bolt moby's unkB8 points at: byte 0xB1 is its source's per-level id. */
typedef struct {
    u8 pad_00[0xB1];
    u8 id;                         /* 0x80 set: no id */
} BoltSource;

/* Per-level, per-source collection counts. */
typedef struct {
    u16 unk0;
    u16 bolts;
} BoltSourceStats;

extern s32 current_bolt_count __asm__("D_0015ED98");
extern s32 D_0015EE2C;                       /* bolts counted when the bolt's pvars[0x40] is set or it is an early moby */
extern s32 current_level_index __asm__("D_0015ED84") MACRO_ADDR;
/* second name for D_0015ED84: retail loads the level index again here */
extern s32 current_level_index_b __asm__("D_0015ED84") MACRO_ADDR;
extern BoltSourceStats bolt_source_stats[][64] __asm__("D_0014D590");
extern s32 level_bolts[] __asm__("D_0013DF38");  /* bolts collected per level */
extern s32 D_L00_0015F598;
extern void *D_L00_0015FFDC_u __asm__("D_L00_0015FFDC");
extern f32 D_0015ED6C;                       /* frame-rate scale */
extern void FUN_L00_00239cc8(void);          /* bolt counter HUD: init */
extern void FUN_L00_00239d00(void);          /* update */
extern void FUN_L00_00239df8(void);          /* draw */
extern void queue_animation_update(s32, s32, void *, void *, void *, void *, s32) __asm__("FUN_001ff308");
extern void FUN_L00_00257d78(void *, f32, f32);
extern void scale_vector_xyz(void *, void *, f32) __asm__("FUN_001f9a68");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 scale_game_frames(s32) __asm__("FUN_001f96f8");
/* spawns a sparkle particle */
extern u8 *FUN_L00_00272060(void *pos, s32 life, f32 size0, f32 size1, s32 color, s32 mode, s32 spin,
                            void *vel, f32 f2);

/*
 * CollectBolt: adds the bolt moby's value (1, or 5 / 20 / 50 for classes
 * 0xE / 0xF / 0x10) to the bolt count, the level's total and its source's
 * stats, shows the bolt counter and spawns two sparkles at the bolt.
 */
void FUN_L00_002a6b70(struct Moby *bolt)
{
    Vec4 vel;
    Vec4 pos;
    s32 value;
    s32 spin;
    f32 k;
    f32 size;
    BoltSource *src;

    switch (bolt->oclass) {
    default:
    case 0:
        value = 1;
        break;
    case 0xE:
        value = 5;
        break;
    case 0xF:
        value = 20;
        break;
    case 0x10:
        value = 50;
        break;
    }

    src = bolt->unkB8;
    if (src && !(src->id & 0x80))
        bolt_source_stats[current_level_index][src->id].bolts += value;
    current_bolt_count += value;
    if (bolt->pvars[0x40] || (D_L00_0015F598 && (void *)bolt < D_L00_0015FFDC_u))
        D_0015EE2C += value;
    level_bolts[current_level_index_b] += value;

    k = 0.7f;
    queue_animation_update(2, 0x754E, FUN_L00_00239cc8, FUN_L00_00239d00, FUN_L00_00239df8,
                           &current_bolt_count, 9999999);

    /* two sparkles 10 units out along a random direction, spinning opposite ways */
    FUN_L00_00257d78(&vel, D_0015ED6C * k, D_0015ED6C);
    scale_vector_xyz(&pos, &vel, 10.0f);
    add_vector_xyz(&pos, &pos, &bolt->pos);
    spin = random_integer_below(2);
    if (spin == 0)
        spin--;
    size = random_float_between(0.4f, 0.5f);
    FUN_L00_00272060(&pos, scale_game_frames(0x19), size * 0.2f, size, 0x7F207F7F, 0, spin, &vel, 0.0f);
    spin = -spin;
    FUN_L00_00272060(&pos, scale_game_frames(0x19), size * 0.14f, size * k, 0x7F7F7F7F, 1, spin, &vel, 0.0f);
}
#define NOT_SDA

#define MACRO_ADDR

/* Steers a thrown moby along its path: builds its orientation from the data's angles and, when done, releases the held target. */
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002A8088), where it is exact; names translated to the US level program. */

extern char *c338_p(void *) __asm__("FUN_L00_002603d0");
extern float D_0015ED6C;
extern int FUN_L00_001f0d60_u(float, void *, int, void *) __asm__("FUN_L00_001f0d60");
extern int FUN_L00_002604f0(int x, char *o, float *p, float *q, float *r, float *s);
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a68(void *, void *, float);
extern void FUN_001fa030(void *, void *);
extern void FUN_001fa328(void *, void *, void *);
extern void FUN_001f9bf8_u(float *, float *, float) __asm__("FUN_001f9bf8");

void FUN_L00_002a6de8(char *moby, void *out1, void *out2) {
    char *data = *(char **)(moby + 0x78);
    float m0[12];
    float m1[12];
    float v60[4];
    float v70[4];
    float A[4];
    float B[4];
    float D[4];
    float C[4];
    float c1, c2, c3, c4, c5;

    if (*(char **)(data + 0x5C) != 0) {
        FUN_L00_002604f0((int)moby, *(char **)(data + 0x5C), (float *)data, (float *)(data + 0x10),
                         A, B);
    } else {
        qcopy(A, data);
        qcopy(B, data + 0x10);
    }
    switch (*(short *)(moby + 0xA6)) {
    case 13:
        c1 = 0.04f;
        c2 = -0.25f;
        c3 = 0.04875f;
        c4 = 0.325f;
        c5 = 0.15f;
        break;
    case 14:
        c1 = 0.03f;
        c2 = -0.5f;
        c3 = 0.0245f;
        c4 = 0.35f;
        c5 = 0.23f;
        break;
    case 15:
        c1 = 0.025f;
        c2 = -0.4f;
        c3 = 0.05625f;
        c4 = 0.375f;
        c5 = 0.23f;
        break;
    default:
        c1 = 0.0175f;
        c2 = -0.35f;
        c3 = 0.135f;
        c4 = 0.3f;
        c5 = 0.25f;
        break;
    }
    if (*(unsigned char *)(data + 0x55) & 1) {
        *(float *)(data + 0x50) = fast_add_rotations(*(float *)(data + 0x50), c1);
        *(float *)(data + 0x58) = fast_add_rotations(*(float *)(data + 0x58), -0.0125f);
    } else {
        *(float *)(data + 0x50) = fast_subtract_rotations(*(float *)(data + 0x50), c1);
        *(float *)(data + 0x58) = fast_subtract_rotations(*(float *)(data + 0x58), -0.0125f);
    }
    qcopy(v60, data + 0x50);
    v60[1] = c2;
    FUN_001fa030(m0, v60);
    FUN_001fa030(m1, B);
    FUN_001fa328(moby + 0xC0, m1, m0);
    FUN_001f9a68(moby + 0x10, &m1[8], c3);
    FUN_001f9a68(v70, moby + 0xC0, c4);
    FUN_001f9a10(moby + 0x10, moby + 0x10, v70);
    FUN_001f9a10(moby + 0x10, moby + 0x10, A);
    if (out1 != 0)
        qcopy(out1, A);
    if (out2 != 0)
        qcopy(out2, B);
    if (*(unsigned char *)(moby + 0x20) == 3) {
        char *obj = *(char **)(data + 0x5C);
        if (obj != 0 && *(unsigned char *)(data + 0x57) == 0) {
            int r;
            char *x;
            if ((unsigned char)obj[0x20] == 0xFE ||
                (*(unsigned char **)(data + 0x5C))[0x20] == 0xFD) {
                r = 1;
            } else {
                r = FUN_L00_001f0d60_u(c5, moby + 0x10, 0x22, moby) == 0;
            }
            if (r) {
                moby[0x20] = 1;
                clear_u64_value(data + 0x30);
                *(float *)(data + 0x3C) = 1.0f;
                x = c338_p(*(char **)(data + 0x5C));
                if (x != 0) {
                    qcopy(data + 0x20, x + 0x10);
                } else {
                    clear_u64_value(data + 0x20);
                }
                FUN_001f9bf8_u(C, &m1[8], D_0015ED6C);
                FUN_001f9bf8_u(D, (float *)(moby + 0xC0), D_0015ED6C);
                FUN_001f9a10(C, C, D);
                FUN_001f9a10(data + 0x20, data + 0x20, C);
                FUN_001f9a10(moby + 0x10, moby + 0x10, data + 0x20);
                *(char **)(data + 0x5C) = 0;
            }
        }
    }
}
extern int D_1613AC_2a7210 __asm__("D_L00_001613AC") __attribute__((sda));
extern float D_1613A8_2a7210 __asm__("D_L00_001613A8") __attribute__((sda));
extern int D_15F5CC_2a7210 __asm__("D_L00_0015F5CC");
extern float D_15ED6C_2a7210 __asm__("D_0015ED6C");
extern int fr_2a7210(int) __asm__("FUN_001f96f8");
extern void allocate_voice_for_target_entry(int, int, char *) __asm__("FUN_0022da68");
extern float rndf_2a7210(float, float) __asm__("FUN_002132a8");
extern void vu_euler_rotation_basis(void *, void *) __asm__("FUN_001fa030");
extern void normalize_vector_xyz(void *, void *, float) __asm__("FUN_001f9bf8");
extern void cross_vectors_xyz(void *, void *, void *) __asm__("FUN_001f9ad8");
extern void build_quaternion_from_axis_angle(void *, void *, float) __asm__("FUN_00214530");

int FUN_L00_002a7210(void *ov, void *tv, float a, float b) {
    char *o = ov;
    char *t = tv;
    char *p = *(char **)(o + 0x78);
    int r, last, now;
    float k;
    float m[3][4] __attribute__((aligned(16)));

    if (*(unsigned char *)(o + 0x20) == 4) {
        return 0;
    }
    r = fr_2a7210(3);
    last = D_1613AC_2a7210;
    now = D_15F5CC_2a7210;
    if (last + r < now || now < last) {
        D_1613AC_2a7210 = now;
        allocate_voice_for_target_entry(0, 0x20, o);
    } else {
        if (a == 0.0f)
            a = rndf_2a7210(-30.0f, 30.0f) * DEG_TO_RAD;
        if (b == 0.0f)
            b = rndf_2a7210(0.0f, 30.0f) * DEG_TO_RAD;
    }
    if (*(unsigned char *)(o + 0x20) == 3) {
        vu_euler_rotation_basis(m, p + 0x10);
        normalize_vector_xyz(p + 0x20, m[2], rndf_2a7210(3.0f, 7.0f) * D_15ED6C_2a7210);
    }
    {
        *(float *)(p + 0x4C) = a;
        *(float *)(p + 0x48) = b;
        *(int *)(p + 0x64) = 0;
        *(char **)(p + 0x60) = t;
        subtract_vector_xyz(m[1], t + 0x10, o + 0x10);
        cross_vectors_xyz(m[0], p + 0x20, m[1]);
        normalize_vector_xyz(p + 0x30, m[0], 1.0f);
        k = rndf_2a7210(D_1613A8_2a7210 * 0.333000004f, D_1613A8_2a7210) * DEG_TO_RAD;
        build_quaternion_from_axis_angle(p + 0x30, p + 0x30, k * D_15ED6C_2a7210);
    }
    *(unsigned char *)(o + 0x20) = 4;
    return 1;
}
/* Vars of a bolt moby (classes 0xD..0x10). */
typedef struct {
    u8 pad_00[0x20];
    f32 vel[4] __attribute__((aligned(16)));   /* 0x20 */
    f32 spin[4] __attribute__((aligned(16)));  /* 0x30: per-frame rotation (quaternion) */
    u8 counted;                    /* 0x40: CollectBolt also adds the bolt to D_0015EE2C */
    u8 pad_41[0xF];
    f32 unk50;                     /* random angle */
    u8 pad_54;
    u8 unk55;                      /* bit 0 set at random */
    u8 pad_56[2];
    f32 unk58;                     /* random angle */
    u8 pad_5C[0xC];
    f32 start_z;                   /* 0x68 */
    s16 unk6C;
    s16 unk6E;                     /* random 0 .. 600 frames */
} BoltVars_u;

extern void *D_001413D0 __attribute__((section(".data")));
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern int random_int_between(int, int) __asm__("FUN_L00_00257b90");
extern void FUN_L00_002502f0(void *, int, int, int);       /* sets the moby colour */
extern void FUN_L00_001ff500(void *, void *, float);

/*
 * Spawns a bolt worth `value` (1, 5, 20 or 50) at `pos` with velocity `vel`,
 * coloured like `src`, spinning about vel x (src - pos). flags & 2 sends it
 * toward D_001413D0 (& 0x10 with a random angle). When no moby is free the
 * value goes straight into the bolt count.
 */
struct Moby *FUN_L00_002a7438(struct Moby *src, void *pos, void *vel, int flags, int value, int counted)
{
    f32 dir[4] __attribute__((aligned(16)));
    f32 tmp[4] __attribute__((aligned(16)));
    struct Moby *m;
    BoltVars_u *v;
    struct Moby *root;
    u8 *color;
    float scale;
    float spin;
    float angle;

    switch (value) {
    default:
    case 1:
        m = (struct Moby *)create_moby(0xD);
        scale = 0.65f;
        break;
    case 5:
        m = (struct Moby *)create_moby(0xE);
        scale = 0.7f;
        break;
    case 20:
        m = (struct Moby *)create_moby(0xF);
        scale = 0.75f;
        break;
    case 50:
        m = (struct Moby *)create_moby(0x10);
        scale = 0.6f;
        break;
    }
    if (0 != m) {
        v = (BoltVars_u *)m->pvars;
        v->counted = counted;
        /* the bolt source is the root of src's unkB8 chain */
        root = src;
        if (src != 0) {
            while (root->unkB8 != 0)
                root = root->unkB8;
        }
        m->unkB8 = root;
        m->unk73 = 20;
        m->flags |= 0x100;
        m->unk30 = 0x40;
        m->unk32 = 0x40;
        m->unk31 = 1;
        m->state = 1;
        m->scale = m->pclass->scale * scale;
        FUN_001fa030(&m->unkC0, &m->rot);
        if ((src->flags & 0x20) && (color = *(u8 **)(src->pvars + 0xC)) != 0)
            FUN_L00_002502f0(m, color[4], color[5], color[6]);
        else
            m->spawn_frame = src->spawn_frame;
        v->unk6E = random_int_between(0, scale_game_frames(600));
        v->unk6C = -1;
        qcopy(&m->pos, pos);
        qcopy(v->vel, vel);
        if (random_integer_below(2))
            v->unk55 |= 1;
        v->unk50 = random_angle_radians();
        v->unk58 = random_angle_radians();
        v->start_z = m->pos.z;
        spin = random_float_between(0.0f, D_1613A8_2a7210) * 0.017453292f * D_0015ED6C;
        subtract_vector_xyz(tmp, &src->pos, &m->pos);
        cross_vectors_xyz(dir, v->vel, tmp);
        FUN_L00_001ff500(v->spin, dir, 1.0f);
        build_quaternion_from_axis_angle(v->spin, v->spin, spin);
        if (flags & 2) {
            angle = 0.0f;
            if (flags & 0x10)
                angle = random_float_between(-30.0f, 30.0f) * 0.017453292f;
            FUN_L00_002a7210(m, D_001413D0, angle, 0.0f);
        }
        FUN_L00_00250df8((u8 *)m);
    } else {
        current_bolt_count += value;
    }
    return m;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a7780.s", FUN_L00_002a7780);
typedef struct {
    char p0[0x50];
    u8 b50;
    u8 b51;
    u8 b52;
    u8 b53;
    f32 f54;
} O_002a7c70;
typedef struct {
    char p0[0x198];
    s32 i198;
    char p1[0x2080 - 0x19C];
    O_002a7c70 *p2080;
    s32 i2084;
    char p2[8];
    s32 i2090;
} G_002a7c70;
extern struct Hero hero_data2 __asm__("D_0013F350") __attribute__((section(".data")));
s32 FUN_001f96f8_002a7c70(s32) __asm__("FUN_001f96f8");
void FUN_00212f90_002a7c70(void *, s32, s32, s32) __asm__("FUN_00212f90");
void update_moby_animation_state(void *) __asm__("FUN_0020c880");
void FUN_L00_002a7c70(O_002a7c70 *m) {
    struct Hero *g = &hero_data2;
    if (g->state.current == 0x3B) {
        u8 c = ((O_002a7c70 *)g->moby)->b53;
        s32 k = 0xB;
        if (c == 0x40)
            k = 0x13;
        if (c == 0x41)
            k = 0x12;
        if (k == 0x12 || k == 0x13) {
            m->b52 = k;
            m->b53 = k;
            m->f54 = ((O_002a7c70 *)g->moby)->f54;
            m->b50 = ((O_002a7c70 *)g->moby)->b50;
            m->b51 = ((O_002a7c70 *)g->moby)->b51;
            if (((O_002a7c70 *)g->moby)->b52 != ((O_002a7c70 *)g->moby)->b53)
                m->b50 = m->b51;
            update_moby_animation_state(m);
        } else {
            FUN_00212f90_002a7c70(m, k, 0, FUN_001f96f8_002a7c70(7));
        }
    } else if (g->state.prev == 0x3B && g->state_timer == 1) {
        FUN_00212f90_002a7c70(m, 1, 0, FUN_001f96f8_002a7c70(0x11));
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002A9030), where it is exact; names translated to the US level program. */

extern char *FUN_002141f8_002a7d90(void *) __asm__("FUN_002141f8");
extern void *D_L00_00173E58_002a7d90 __asm__("D_L00_00173E58") __attribute__((section(".data")));

/* True when the record for D_L00_00173E58 (FUN_002141f8) has byte 9 equal to 1. */
int FUN_L00_002a7d90(void) {
    int r = 0;
    char *x = 0;
    if (D_L00_00173E58_002a7d90 != 0)
        x = FUN_002141f8_002a7d90(D_L00_00173E58_002a7d90);
    if (x != 0)
        r = *(unsigned char *)(x + 9) == 1;
    return r;
}
extern int D_L00_00173E58 __attribute__((section(".data")));
char *FUN_L00_0025c338(int);
/* True when FUN_L00_0025c338(D_L00_00173E58) is set and has flag 2 at 0x1E. */
int FUN_L00_002a7de0(void) {
    char *p = FUN_L00_0025c338(D_L00_00173E58);
    if (p && (*(unsigned short *)(p + 0x1e) & 2))
        return 1;
    return 0;
}
extern float rndf_2a7e20(float, float) __asm__("FUN_002132a8");
extern int rndi_2a7e20(int) __asm__("FUN_00213260");
extern float rnda_2a7e20(void) __asm__("FUN_00213308");
extern void build_spherical_offset(void *, float, float, float) __asm__("FUN_00214db0");
extern float spread_k(float, float) __asm__("FUN_L00_00257c48");
extern int fr_2a7e20(int) __asm__("FUN_001f96f8");
extern void emit_2a7e20(float *, int, int, int, int, void *, float, float,
                        float) __asm__("FUN_L00_00272060");

void FUN_L00_002a7e20(float *pos, int n) {
    OvlQuad dir[1];
    OvlQuad old[1];
    int i;
    for (i = 0; i < n; i++) {
        float s = rndf_2a7e20(0.1f, 2.0f);
        int k = rndi_2a7e20(2);
        float a, b;
        if (k == 0)
            k--;
        a = rnda_2a7e20();
        b = rndf_2a7e20(0.34906584f, 1.53588974f);
        build_spherical_offset(dir, rndf_2a7e20(0.05f, 0.1f), a, b);
        qcopy(old, pos);
        pos[0] += spread_k(0.0f, 0.15f);
        pos[1] += spread_k(0.0f, 0.15f);
        pos[2] += spread_k(0.0f, 0.15f);
        emit_2a7e20(pos, fr_2a7e20(0x1E), 0x7F207F7F, 0, k, dir, s * 0.1f, s, 0.003f);
        k = -k;
        emit_2a7e20(pos, fr_2a7e20(0x1E), 0x7F7F7F7F, 1, k, dir, s * 0.07f, s * 0.7f, 0.003f);
    }
}
typedef union {
    u128 q;
    f32 f[4];
} V2a8028;
extern V2a8028 D_L00_00166DC0_2a8028 __asm__("D_L00_00166DC0") __attribute__((section(".data")));
extern V2a8028 D_L00_00173E60_2a8028 __asm__("D_L00_00173E60") __attribute__((section(".data")));
extern f32 D_L00_00173E40_2a8028[] __asm__("D_L00_00173E40") __attribute__((section(".data")));
extern f32 vector_length_xy(void *) __asm__("FUN_001f9b20");
extern f32 rnd_2a8028(f32, f32) __asm__("FUN_L00_00257c48");
extern f32 ang_2a8028(f32, f32) __asm__("FUN_001fa580");
extern void dir_2a8028(void *, f32, f32, f32) __asm__("FUN_00214db0");
extern f32 rndf_2a8028(f32, f32) __asm__("FUN_002132a8");
extern void spawn_2a8028(void *, void *) __asm__("FUN_L00_0026c6e8");
extern s32 fr_2a8028(s32) __asm__("FUN_001f96f8");
extern s32 rndi_2a8028(s32, s32) __asm__("FUN_L00_00257b90");
extern void spark_cbb0(void *, void *, s32, s32, s32, s32, f32) __asm__("FUN_L00_0026cbb0");
extern void fin_2a8028(void *, s32) __asm__("FUN_L00_002a7e20");
void FUN_L00_002a8028(u8 *o) {
    V2a8028 v;
    V2a8028 w;
    f32 pitch;
    f32 a;
    s32 i;
    s32 n;
    subtract_vector_xyz(&v, &D_L00_00166DC0_2a8028, &D_L00_00173E60_2a8028);
    pitch = -angle_atan2(vector_length_xy(&v), v.f[2]);
    angle_atan2(v.f[0], v.f[1]);
    for (i = 19; i >= 0; i--) {
        a = ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch);
        dir_2a8028(&v, 0.2f, ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch), a);
        scale_vector_xyz(&w, &v, rndf_2a8028(1.0f, 3.0f));
        add_vector_xyz(&w, &w, &D_L00_00173E60_2a8028);
        spawn_2a8028(&w, &v);
    }
    for (i = 9; i >= 0; i--) {
        w.f[0] = D_L00_00173E40_2a8028[8] + rnd_2a8028(0.0f, 0.1f);
        w.f[1] = D_L00_00173E40_2a8028[9] + rnd_2a8028(0.0f, 0.1f);
        w.f[2] = D_L00_00173E40_2a8028[10] + rnd_2a8028(0.0f, 0.1f);
        a = ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch);
        dir_2a8028(&v, 0.05f, ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch), a);
        n = fr_2a8028(10);
        spark_cbb0(&w, &v, 0x4F007FFF, 0x1FFFFFFF, rndi_2a8028(n, fr_2a8028(20)), 1, 20000.0f);
    }
    if (*(s16 *)(*(u8 **)(o + 0x78) + 0x78) == 0x2B) {
        fin_2a8028(&D_L00_00173E60_2a8028, 10);
    }
}
typedef struct N_2a82c0 {
    char p0[0x20];
    unsigned char type;
    char p1[3];
    char *info;
    struct N_2a82c0 *next;
} N_2a82c0;
extern N_2a82c0 *D_L00_0015FFE4;
extern float FUN_001f9b48(void *, void *);
extern float random_float_between(float, float) __asm__("FUN_002132a8");
extern int FUN_L00_002a7210(void *, void *, float, float);
extern int FUN_L00_0025e3f8(void *);
extern int FUN_L00_002c5be8(void *);

void FUN_L00_002a82c0(unsigned char *m) {
    N_2a82c0 *n = D_L00_0015FFE4;
    struct Hero *g;
    int r;
    if (n == 0)
        return;
    g = &hero;
    do {
        if (n->type == 0xFE)
            return;
        if (n->type == 0xFD)
            return;
        if (n && n->info && *(short *)(n->info + 0x46) == 0x13) {
            if (FUN_001f9b48((char *)n + 0x10, m + 0x10) < 2.7f) {
                r = FUN_L00_002a7210(n, ((void *)g->moby),
                                     random_float_between(-30.0f, 30.0f) * DEG_TO_RAD, 0.0f);
                goto check;
            }
        } else if (FUN_L00_0025e3f8(n) && FUN_001f9b48((char *)n + 0x10, m + 0x10) < 2.7f) {
            r = FUN_L00_002c5be8(n);
        check:
            if (r)
                return;
        }
        n = n->next;
    } while (n);
}
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002A96B8), where it is exact; names translated to the US level program. */

extern float FUN_001f9e90(float, float);
extern void FUN_001f9bf8_u(float *, float *, float) __asm__("FUN_001f9bf8");

void FUN_L00_002a8418(float *v) {
    float k = 1.8325957f;
    float a = FUN_001f9e90(v[0], v[1]);
    float t = fast_difference_between_rotations(hero.motion.rot.f[2], a);
    if (t > k)
        t = k;
    FUN_001f9bf8_u(v, v, vector_length_xyz(v) * ((k - t) / k * 0.3f + 0.7f));
}
#include "rnc/gameplay/entities/moby.h"

#include "sda.h"

#include "qcopy.h"

/* Updates normal wrench swings and its thrown/returning collision sweep. */
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002A9768), where it is exact; names translated to the US level program. */

typedef unsigned int WrenchQuad __attribute__((mode(TI)));

typedef float WrenchVec[4] __attribute__((aligned(16)));

typedef struct WrenchMoby WrenchMoby;

typedef struct { char pad0[0x46]; short kind; } WrenchClass;

typedef struct {
    char pad0[0x40]; WrenchVec direction,target;
    float speed,acceleration; int pad68,timer; float hit_blend;
    short animation_count,collision,animation78,pad7A,previous_count,aim_hit;
} WrenchVars;

struct WrenchMoby {
    char pad0[0x10]; WrenchVec position; unsigned char state,pad21[3]; WrenchClass *model;
    char pad28[0x28]; unsigned char frame,frame_end,animation,current_animation;
    float animation_time,animation_scale; char pad5C[0x14]; unsigned char animation_flags;
    char pad71[7]; WrenchVars *data; char pad7C[0x2A]; unsigned short class_id;
    char padA8[0x10]; WrenchMoby *parent;
};

typedef struct {
    char pad0[0x80]; WrenchVec position; char pad90[8]; float yaw; char pad9C[0xA4]; WrenchVec velocity; char pad150[0x48];
    int state_timer; char pad19C[0x854]; WrenchVec sweep_start,sweep_end,previous_start,previous_end;
    char padA30[0x30]; int attack_index,attack_cooldown; float reaction_yaw; char padA6C[0x10];
    unsigned short hit_index; char padA7E[0x12]; float animation_scale; char padA94[8]; int blocked;
    char padAA0[8]; float animation_frame; unsigned char padAAC[4]; int selected_weapon,weapon_animation;
    char padAB8[0x5F2]; unsigned char thrown,pad10AB,wrench_state; char pad10AD[7]; int mode;
    char pad10B8[0xFC8]; WrenchMoby *moby; int state,pad2088,move_mode;
    char pad2090[0x1E]; unsigned char alternate; char pad20AF[4]; unsigned char no_ground_adjust;
    char pad20B4[0x168]; int thrown_sound;
} WrenchHero;

typedef struct { char pad0[0x140]; WrenchVec position; float pad150,pitch,yaw; } PlayerCamera;

typedef struct { int pad0,side; char pad8[0x14]; int first_frame,last_frame; char pad24[8]; } WrenchAttack;

typedef struct { char pad0[0x18]; WrenchMoby *moby; int surface; WrenchVec position; } WrenchHit;

typedef struct { char pad0[0x14]; short hit_index; char pad16[6]; short hit_count; } MobyHitState;

typedef struct {
    char pad0[8]; float force,range; char pad10[8]; unsigned char flags,enabled; unsigned short class_id;
} HitQuery;

typedef union {
    WrenchVec v[8]; WrenchQuad q[8]; HitQuery query;
    struct { WrenchVec pad0; HitQuery query; } shifted;
} WrenchScratch;

extern WrenchAttack D_L00_0017BC28[];
extern WrenchMoby *D_L00_00177F00[];
extern char *FUN_002141f8(void *);
extern char D_0013A4E0[];
extern char D_0013E533[];
extern f32 fast_add_rotations(f32, f32) __asm__("func_001FA580");
extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern f32 fast_sin(f32) __asm__("func_001F9DE0");
extern f32 vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern float D_0015ED6C MACRO_ADDR;
extern float D_0015ED70 MACRO_ADDR;
extern float D_0015ED74 MACRO_ADDR;
extern float FUN_001f9e90(float, float);
extern float approach_value_alt(float*,float,float) __asm__("FUN_00213ed8");
extern float fast_difference_between_rotations(float, float) __asm__("func_001FA688");
extern float probe_ground_height(void *, int, float) __asm__("func_00213508");
extern int D_L00_00173E40_u[] __asm__("D_L00_00173E40");
extern int FUN_001efa68(void*,void*,int,int,int);
extern int FUN_001f0b58(void);
extern int FUN_L00_001f2868();
extern int FUN_L00_00211870(float);
extern int FUN_L00_00216de8(int,int);
extern int FUN_L00_002223f8(int,int);
extern int FUN_L00_00259d08(void*,void*,void*,void*,void*,void*,int);
extern int FUN_L00_0025e368(char*);
extern int FUN_L00_0025e3b8(int);
extern int allocate_voice_for_target_entry_alt(int, int, int) __asm__("FUN_0022da68");
extern int scale_game_frames_alt(int) __asm__("FUN_001f96f8");
extern int tick_countdown_32_alt(int*) __asm__("FUN_001f9740");
extern void FUN_001f9c48(void*,void*,float);
extern void FUN_L00_00232640(int);
extern void FUN_L00_002336e8(float*,float*,float);
extern void FUN_L00_0024f7c8(void*,int,void*);
extern void FUN_L00_00259888(void*,void*,int,float,void*);
extern void FUN_L00_00259bc8(void*,int,int,void*,void*,float);
extern void FUN_L00_0025b6b8(void*,void*,void*,float);
extern void FUN_L00_00262480(char*,float,float,float);
extern void FUN_L00_00262608(void*,int);
extern void FUN_L00_00262840(char*);
extern void FUN_L00_002a7780(void);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void blend_moby_animation(void *, s32, s32, s32) __asm__("FUN_00212f90");
extern void build_spherical_offset(void *, f32, f32, f32) __asm__("func_00214DB0");
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");
extern void scale_vector_xyz(void *, void *, float) __asm__("FUN_001f9a68");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
int FUN_L00_002a7d90(void);
int FUN_L00_002a7de0(void);
void FUN_L00_001edf60(int a, int b, void *pos, int kind, int mode, float x, float y, float z);
void FUN_L00_002a7c70_c(void *m) __asm__("FUN_L00_002a7c70");
void FUN_L00_002a7e20(float *pos, int n);
void FUN_L00_002a8028(u8 *o);
void FUN_L00_002a82c0(unsigned char *m);
void FUN_L00_002a8418(float *v);
extern char D_0013CAE0[];
extern char D_00140B00[];
extern char D_001403C0[];
extern PlayerCamera player_camera __asm__("D_L00_00166C80");
extern WrenchHit collision_hit __asm__("D_L00_00173E40");
extern void draw_target_reticle(int,int,float,float,int,int,int,float,int) __asm__("FUN_L00_001edf60");
extern int collide_sphere(void*,float,int,void*,void*) __asm__("FUN_L00_001f2868");


extern char D_0013F350[];
extern unsigned char D_0013E550[];
static __inline__ WrenchHero *wrench_hero(void) { return (WrenchHero*)D_0013F350; }
static __inline__ float *sweep_end(void) { return (float*)(D_0013E533+0x181D); }
static __inline__ unsigned long combo_step(int animation) { return (unsigned char)(animation-15); }
static __inline__ float *hero_velocity(void) { return (float*)(D_0013E533+0xF5D); }
static __inline__ unsigned char *voice_slot(int slot) { return D_0013E550+slot*0x70; }
static __inline__ WrenchHero *sweep_hero(void) { return (WrenchHero*)((char*)sweep_end()-0xA00); }

void FUN_L00_002a84c8(WrenchMoby *m) {
    WrenchVars *d=m->data;
    WrenchScratch work;
    WrenchHero *player=wrench_hero();
    player->wrench_state=0;
    if (player->mode==3) return;
    switch (m->state) {
    case 0: {
        int player_state;
        int anim;
        WrenchMoby *player_moby;
        WrenchAttack *attack;
        int active;
        int reaction;
        float difference,yaw;
        m->parent=player->moby;
        player_state=player->state;
        if (player_state==1) {
            if (*(int*)(((char *)&D_0013CAE0))&0xA)
                draw_target_reticle((int)m,0xFF917267,1.0f,0.0f,0,0x25,-1,90.0f,4);
            d->aim_hit=0;
            build_spherical_offset(work.v[0],10.0f,player_camera.yaw,-player_camera.pitch);
            add_vector_xyz(work.v[0],work.v[0],player_camera.position);
            if (FUN_001efa68(player_camera.position,work.v[0],4,(int)player->moby,0)) {
                d->aim_hit=player_state; qcopy(d->target,collision_hit.position);
            }
        }
        enqueue_callback_list_1_alt(FUN_L00_002a7780,m);
        anim=m->current_animation;
        if ((unsigned char)anim!=0) {
            if ((unsigned char)anim==14) {
                if (m->animation_flags&2) blend_moby_animation(m,1,0,scale_game_frames_alt(5));
                return;
            } else if (wrench_hero()->alternate) {
                if (combo_step(anim)>=2U) blend_moby_animation(m,15,0,scale_game_frames_alt(4));
                else if ((m->animation_flags&2) && (unsigned char)anim==15)
                    blend_moby_animation(m,16,0,scale_game_frames_alt(5));
                return;
            } else if (combo_step(anim)<2U) {
                blend_moby_animation(m,14,0,scale_game_frames_alt(2)); return;
            }
        }
        if ((m->animation_flags&2) && wrench_hero()->state!=0x3B && m->current_animation!=1)
            blend_moby_animation(m,1,0,scale_game_frames_alt(5));
        FUN_L00_002a7c70_c((char*)m);
        {
        int current_state=wrench_hero()->state;
        if (current_state!=19 && current_state!=33 && current_state!=43 && current_state!=112 && current_state!=20) {
            int current=m->current_animation;
            if ((unsigned int)current>=3 && m->current_animation<6)
                blend_moby_animation(m,1,0,scale_game_frames_alt(4));
        }
        }
        player_moby=wrench_hero()->moby;
        if (player_moby->current_animation!=player_moby->animation || (int)player_moby->frame_end-player_moby->frame>=3)
            d->animation_count++;
        m->animation_scale=wrench_hero()->animation_scale;
        attack=&D_L00_0017BC28[wrench_hero()->attack_index];
        if (wrench_hero()->move_mode!=6 && wrench_hero()->state!=43) break;
        active=1; reaction=0;
        if (wrench_hero()->blocked || wrench_hero()->animation_frame<(float)attack->first_frame || (float)attack->last_frame<wrench_hero()->animation_frame) active=0;
        {
            int reset=0;
            if (d->previous_count!=d->animation_count) {
                WrenchMoby *pm=wrench_hero()->moby;
                int a=pm->animation;
                if (a==pm->current_animation) {
                    if (a==23) reset=0.0f<=wrench_hero()->animation_frame;
                    else if (a==24) reset=0.0f<=wrench_hero()->animation_frame;
                    else if (a==25) reset=12.0f<=wrench_hero()->animation_frame;
                    else if (a==43) reset=23.0f<=wrench_hero()->animation_frame;
                }
            }
            if (reset) { d->hit_blend=1.0f; d->previous_count=d->animation_count; }
        }
        difference=0.0f; yaw=wrench_hero()->yaw;
        qcopy(wrench_hero()->previous_end,wrench_hero()->sweep_end);
        qcopy(wrench_hero()->previous_start,wrench_hero()->sweep_start);
        FUN_L00_0024f7c8(m,1,wrench_hero()->sweep_end);
        FUN_L00_0024f7c8(wrench_hero()->moby,0,wrench_hero()->sweep_start);
        if (wrench_hero()->state==19 || wrench_hero()->state==112 || wrench_hero()->state==43) {
            yaw=FUN_001f9e90(wrench_hero()->sweep_end[0]-wrench_hero()->position[0],wrench_hero()->sweep_end[1]-wrench_hero()->position[1]);
            if (D_L00_0017BC28[wrench_hero()->attack_index].side==1)
                yaw=fast_add_rotations(yaw,-1.5707964f);
            else yaw=fast_add_rotations(yaw,1.5707964f);
        }
        subtract_vector_xyz(work.v[0],sweep_end(),(sweep_end()-4));
        normalize_vector_xyz(work.v[0],work.v[0],vector_length_xyz(work.v[0])+0.17f);
        if (sweep_hero()->move_mode!=15 && sweep_hero()->state!=112 && sweep_hero()->state!=20) {
            difference=fast_difference_between_rotations(sweep_hero()->yaw,FUN_001f9e90(sweep_hero()->sweep_end[0]-sweep_hero()->position[0],sweep_hero()->sweep_end[1]-sweep_hero()->position[1]));
            if (difference>1.5707964f) active=0;
            FUN_L00_002a8418(work.v[0]);
        }
        add_vector_xyz(sweep_end(),(sweep_end()-4),work.v[0]);
        if (sweep_hero()->state!=43 && sweep_hero()->state!=112 && difference<1.2217305f && scale_game_frames_alt(10)<sweep_hero()->state_timer) {
            float angle;
            qcopy(work.v[0],sweep_hero()->position); work.v[0][2]+=0.5f;
            angle=FUN_001f9e90(sweep_hero()->sweep_end[0]-sweep_hero()->position[0],sweep_hero()->sweep_end[1]-sweep_hero()->position[1]);
            qcopy(work.v[1],sweep_hero()->position); work.v[1][2]+=0.5f;
            work.v[2][0]=fast_cos(angle)*1.4f; work.v[2][1]=fast_sin(angle)*1.4f; work.v[2][2]=0.0f;
            FUN_L00_002a8418(work.v[2]); add_vector_xyz(work.v[1],work.v[1],work.v[2]);
            if (!sweep_hero()->attack_cooldown && FUN_001efa68(work.v[0],work.v[1],2,0,0) && FUN_001f0b58()) {
                if (!collision_hit.moby || FUN_L00_0025e368((char*)collision_hit.moby)) {
                    sweep_hero()->attack_cooldown=1; allocate_voice_for_target_entry_alt(2,0,(int)m); FUN_L00_002a8028((char*)m);
                    if (collision_hit.moby) {
                        work.v[3][0]=fast_cos(yaw); work.v[3][1]=fast_sin(yaw); work.v[3][2]=0.0f;
                        FUN_L00_00259bc8(collision_hit.moby,(int)m,0x10000,collision_hit.position,work.v[3],1.0f);
                    }
                }
            }
        }
        if (wrench_hero()->state==20 && FUN_L00_00211870(27.0f)) {
            allocate_voice_for_target_entry_alt(2,0,(int)m);
            qcopy(work.v[0],wrench_hero()->sweep_end); qcopy(work.v[1],work.v[0]);
            FUN_L00_002336e8(work.v[0],work.v[0],0.7f); FUN_L00_002336e8(work.v[1],work.v[1],-0.9f);
            if (FUN_001efa68(work.v[0],work.v[1],2,0,0)) FUN_L00_002a8028((char*)m);
        }
        if (active) {
            int count=1;
            float scale=1.0f,radius;
            if (wrench_hero()->state==20) { scale=1.55f; count=2; }
            work.v[3][0]=fast_cos(yaw); work.v[3][1]=fast_sin(yaw); work.v[3][2]=0.0f;
            FUN_L00_00259888(work.v[0],m,0x10000,(float)count,work.v[3]); FUN_001f9c48(work.v[0],work.v[0],scale);
            work.query.force=1.0f; work.query.range=5627.925f; work.query.enabled=1; work.query.class_id=m->class_id; work.query.flags=0;
            if (FUN_L00_00259d08(wrench_hero()->sweep_start,wrench_hero()->sweep_end,wrench_hero()->previous_start,wrench_hero()->previous_end,wrench_hero()->moby,&work,5) && collision_hit.moby) {
                if (FUN_L00_002a7de0()) reaction=1;
                else if (!wrench_hero()->attack_cooldown) {
                    if (!collision_hit.moby || !collision_hit.moby->model || collision_hit.moby->model->kind!=20) {
                        wrench_hero()->attack_cooldown=1; allocate_voice_for_target_entry_alt(FUN_L00_002a7d90(),0,(int)m); FUN_L00_002a8028((char*)m);
                    }
                }
            }
            subtract_vector_xyz(work.v[5],sweep_end(),(sweep_end()-4));
            normalize_vector_xyz(work.v[5],work.v[5],vector_length_xyz(work.v[5])-0.085f);
            add_vector_xyz(work.v[4],work.v[5],(sweep_end()-4));
            radius=0.35f;
            if (sweep_hero()->move_mode==15) radius=0.7f;
            if (sweep_hero()->state==20) radius=0.47f;
            if (collide_sphere(work.v[4],radius,0,sweep_hero()->moby,work.v[0]) && (!D_L00_00177F00[0] || !D_L00_00177F00[0]->model || D_L00_00177F00[0]->model->kind!=18)) {
                if (FUN_L00_002a7de0()) reaction=1;
                else if (!wrench_hero()->attack_cooldown) { wrench_hero()->attack_cooldown=1; allocate_voice_for_target_entry_alt(FUN_L00_002a7d90(),0,(int)m); FUN_L00_002a8028((char*)m); }
            }
        }
        if (reaction) {
            FUN_L00_002223f8(33,1);
            if (collision_hit.moby) {
                WrenchMoby *target=collision_hit.moby;
                wrench_hero()->reaction_yaw=FUN_001f9e90(wrench_hero()->position[0]-target->position[0],wrench_hero()->position[1]-target->position[1]);
            } else wrench_hero()->reaction_yaw=fast_add_rotations(wrench_hero()->yaw,3.1415927f);
        }
        break;
    }
    case 10: case 11: {
        int collided;
        float *position;
        float radius;
        {
        char *control=((char *)&D_00140B00);
        WrenchHero *control_player=(WrenchHero*)(control-0x17B0);
        FUN_L00_00262608(control,0);
        m->parent=control_player->moby; control_player->wrench_state=2;
        if (m->state==10 && control_player->thrown_sound==-1) control_player->thrown_sound=allocate_voice_for_target_entry_alt(14,4,(int)control_player->moby);
        }
        FUN_L00_00262480((char*)m,0.0f,0.0f,D_0015ED6C*24.434608f);
        if (wrench_hero()->attack_cooldown && tick_countdown_32_alt(&d->timer)) wrench_hero()->attack_cooldown=0;
        position=m->position;
        if (!wrench_hero()->no_ground_adjust) {
            float ground=probe_ground_height(position,0,0.5f);
            if (m->position[2]-ground<0.8f) {
                ground+=0.55f;
                if (m->position[2]<ground) approach_value_alt(&m->position[2],ground,D_0015ED6C*4.0f);
                else approach_value_alt(&m->position[2],ground,D_0015ED6C);
            }
        }
        qcopy(work.v[0],position);
        if (m->state==10) {
            qcopy(work.v[1],hero_velocity());
            scale_vector_xyz(work.v[1],work.v[1],0.7f);
            add_vector_xyz(position,position,work.v[1]);
            normalize_vector_xyz(work.v[1],d->direction,d->speed); add_vector_xyz(position,position,work.v[1]);
            d->acceleration+=D_0015ED74*170.0f;
            approach_value_alt(&d->speed,0.0f,d->acceleration);
            if (d->speed==0.0f) m->state=11;
        } else {
            int arrived=0;
            float length,steps;
            FUN_L00_002a82c0((char*)m);
            subtract_vector_xyz(work.v[1],((char *)&D_001403C0),position);
            d->acceleration+=D_0015ED70*0.9f; d->speed+=d->acceleration;
            length=vector_length_xyz(work.v[1]); steps=d->speed; steps=length/steps;
            if (steps<(float)scale_game_frames_alt(5) && m->current_animation!=1) blend_moby_animation(m,1,0,scale_game_frames_alt(5));
            if (length<=d->speed) { d->speed=length; arrived=1; }
            normalize_vector_xyz(work.v[1],work.v[1],d->speed); add_vector_xyz(position,position,work.v[1]);
            if (length/d->speed<(float)scale_game_frames_alt(4) && wrench_hero()->selected_weapon!=-1) {
                int sound;
                FUN_L00_00232640(2); wrench_hero()->weapon_animation=26;
                sound=wrench_hero()->thrown_sound;
                if (sound!=-1) { unsigned char *audio=voice_slot(sound); if (*(WrenchMoby**)(audio+0x88)==wrench_hero()->moby && audio[0x74]) release_voice_slot(sound); }
                wrench_hero()->thrown_sound=-1;
            }
            if (arrived) {
                int sound;
                FUN_L00_00216de8(5,0);
                sound=wrench_hero()->thrown_sound;
                if (sound!=-1) { unsigned char *audio=voice_slot(sound); if (*(WrenchMoby**)(audio+0x88)==wrench_hero()->moby && audio[0x74]) release_voice_slot(sound); }
                wrench_hero()->thrown_sound=-1; FUN_L00_00262840((char*)wrench_hero()+0x17B0); wrench_hero()->thrown=0; m->state=0;
            }
        }
        collided=0;
        if (FUN_001efa68(work.v[0],position,2,0,0) && FUN_001f0b58() && (!collision_hit.moby || !FUN_L00_0025e3b8((int)collision_hit.moby))) collided=collision_hit.surface!=0;
        if (collided || d->collision) {
            d->collision=0;
            if (!wrench_hero()->attack_cooldown) { d->timer=scale_game_frames_alt(30); wrench_hero()->attack_cooldown=1; allocate_voice_for_target_entry_alt(2,0,(int)m); }
            if (m->state==10) { FUN_L00_002a8028((char*)m); d->speed*=0.5f; m->state=11; }
        }
        radius=1.2f; if (m->state==11) radius=-0.37f;
        normalize_vector_xyz(work.v[4],d->direction,radius);
        FUN_L00_00259888(work.v[1],m,0x10000,1.0f,work.v[4]);
        work.shifted.query.force=1.0f; work.shifted.query.range=5627.925f;
        work.shifted.query.enabled=1; work.shifted.query.class_id=wrench_hero()->hit_index+1; work.shifted.query.flags=0;
        FUN_L00_0024f7c8(m,1,work.v[5]);
        if (collide_sphere(work.v[5],0.4f,0,wrench_hero()->moby,work.v[1]) || (FUN_L00_0024f7c8(m,0,work.v[5]),collide_sphere(work.v[5],0.4f,0,wrench_hero()->moby,work.v[1]))) {
            if (!wrench_hero()->attack_cooldown && collision_hit.moby && (!collision_hit.moby->model || collision_hit.moby->model->kind!=20)) {
                MobyHitState *hit=(MobyHitState*)FUN_002141f8(collision_hit.moby);
                if (!hit || hit->hit_count<2 || hit->hit_index!=work.shifted.query.class_id) {
                    work.q[7]=*(WrenchQuad*)collision_hit.moby->position;
                    FUN_L00_0025b6b8(work.v[6],work.v[5],work.v[7],0.5f); FUN_L00_002a7e20(work.v[6],5);
                    d->timer=scale_game_frames_alt(30); wrench_hero()->attack_cooldown=1; allocate_voice_for_target_entry_alt(FUN_L00_002a7d90(),0,(int)m);
                }
            }
        }
        break;
    }
    default: break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a96f8.s", FUN_L00_002a96f8);
/* Creates a moby at a position with a scale, colour and a few data fields. */
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002AAC50), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m(int);
extern void FUN_L00_002502f0(void *, int, int, int);

void *FUN_L00_002a99b0(int unused, void *pos, int c, float scale, float a, float b) {
    char *m = func_0020D348_m(0x593);
    if (m != 0) {
        char *d;
        float s;
        qcopy(m + 0x10, pos);
        FUN_L00_002502f0(m, 0x80, 0x80, 0x70);
        d = *(char **)(m + 0x78);
        s = scale + scale;
        *(float *)d = a;
        *(float *)(m + 0x2C) = s;
        *(float *)(m + 0x2C) = s * *(float *)(*(char **)(m + 0x24) + 0x24);
        *(int *)(d + 4) = c;
        *(int *)(d + 8) = c;
        *(float *)(d + 0xC) = b;
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        *(unsigned char *)(m + 0x31) = 1;
        *(unsigned char *)(m + 0x20) = 0;
    }
    return m;
}

/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002AAD40), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m_q(int) __asm__("func_0020D348_m");
extern int D_L00_0015F320_q __asm__("D_L00_0015F320");
extern int D_L00_0015F324_q __asm__("D_L00_0015F324");
extern int D_L00_0015F330_q __asm__("D_L00_0015F330");
extern int D_L00_0015F334_q __asm__("D_L00_0015F334");
extern int FUN_L00_0023e5e0_q(float *pos, float radius, float intensity,
                              int color) __asm__("FUN_L00_0023e5e0");
extern long D_L00_0015F328_q __asm__("D_L00_0015F328");
extern long D_L00_0015F338_q __asm__("D_L00_0015F338");
extern short D_L00_001613C8_q __asm__("D_L00_001613C8") __attribute__((sda));

void *FUN_L00_002a9aa0(int unused, float *pos) {
    char *m = func_0020D348_m_q(0x5F3);
    if (m != 0 && *(int *)&D_L00_001613C8_q == 0) {
        char *d;
        m[0x20] = 0;
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        d = *(char **)(m + 0x78);
        *(OvlQuad *)(m + 0x10) = *(OvlQuad *)pos;
        D_L00_0015F324_q = 0xFF;
        D_L00_0015F334_q = 0xFFFFFF;
        D_L00_0015F338_q = 0x1F00000042L;
        *(int *)&D_L00_001613C8_q = (int)m;
        D_L00_0015F328_q = 0;
        D_L00_0015F320_q = 0;
        D_L00_0015F330_q = 0;
        *(int *)(d + 0x10) = 0;
        *(short *)(d + 0x2C) = FUN_L00_0023e5e0_q(pos, 0.0f, 0.0f, 0);
    }
    return m;
}
extern u8 *D_L00_001613C8 __attribute__((sda));
void FUN_L00_002a9aa0_u(void *, OvlQuad *) __asm__("FUN_L00_002a9aa0");
void FUN_L00_002a9b80(void *a, OvlQuad *v) {
    OvlQuad t = *v;
    u8 *p;
    u8 *q;
    u8 *g;
    g = D_L00_001613C8;
    if (g == 0) {
        FUN_L00_002a9aa0_u(a, &t);
        g = D_L00_001613C8;
        if (g == 0)
            return;
    }
    p = D_L00_001613C8;
    q = *(u8 **)(p + 0x78);
    if (*(s16 *)(p + 0xA6) == 0x5F3) {
        *(OvlQuad *)(p + 0x10) = t;
        *(s16 *)(q + 0x2E) = 1;
    }
}
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002AAE80), where it is exact; names translated to the US level program. */

extern int D_L00_0015F320;
extern int D_L00_0015F330;
extern short D_L00_001613C8_d __asm__("D_L00_001613C8") __attribute__((sda));
extern void FUN_L00_0023e838(int);
void mark_moby_for_removal(struct Obj *obj) __asm__("FUN_0020c828");

void FUN_L00_002a9be0(void) {
    char *m = *(char **)&D_L00_001613C8_d;
    if (m != 0) {
        if (*(short *)(m + 0xA6) == 0x5F3) {
            char *data;
            int idx;
            if (*(unsigned char *)(m + 0x20) != 0)
                return;
            data = *(char **)(m + 0x78);
            D_L00_0015F320 = 0;
            D_L00_0015F330 = 0;
            idx = *(short *)(data + 0x2C);
            if (idx != -1)
                FUN_L00_0023e838(idx);
            mark_moby_for_removal(*(char **)&D_L00_001613C8_d);
        }
        *(int *)&D_L00_001613C8_d = 0;
    }
}
typedef union {
    u128 q;
    f32 f[4];
} V_2a9c50;
typedef struct {
    V_2a9c50 corner[4];
    u32 color[4];
    f32 uv[8];
    s64 unk70;
    s64 tex;
    s64 unk80;
    s64 unk88;
} Q_2a9c50;
typedef struct {
    u8 pad0[0x10];
    V_2a9c50 pos;
    f32 f20, f24, f28;
} PV_2a9c50;
typedef struct {
    u8 pad0[0x78];
    PV_2a9c50 *pv;
} M_2a9c50;
extern s32 D_L00_0015F5C4;
extern s32 D_L00_0015F5CC;
/* Spin angles of the second quad: x is read through $gp, the rest as an
   array through the unsplit address macro (from rac1-decomp's form). */
extern f32 spin_angles_x __asm__("D_L00_001613E0") __attribute__((sda));
extern f32 spin_angles[] __asm__("D_L00_001613E0") __attribute__((section(".sdata")));
extern f32 seg_sqrt(f32) __asm__("FUN_001f9988");
extern f32 appr_2a9c50(f32, f32) __asm__("FUN_001fa580");
int scale_game_frames(int) __asm__("FUN_001f96f8");
float FUN_001fa6c0(int);
extern f32 scale_time(f32) __asm__("FUN_001f96b0");
extern f32 fast_normalize_angle(f32) __asm__("FUN_001fa610");
extern void rotation_matrix(void *, void *) __asm__("FUN_001fa050");
extern void mmul_2a9c50(void *, void *, void *) __asm__("FUN_001fa378");
extern s64 get_effect_texture(s32) __asm__("FUN_001f44b8");
extern void draw_geometry_quad(void *, void *, s32) __asm__("FUN_001f7d30");
void FUN_L00_002a9c50(M_2a9c50 *m) {
    Q_2a9c50 quad;
    V_2a9c50 mat[4];
    V_2a9c50 mz[4];
    V_2a9c50 rot;
    PV_2a9c50 *pv = m->pv;
    s32 i;
    s32 odd;
    f32 a, t;
    if (D_L00_0015F5C4 == 2) {
        return;
    }
    for (i = 0; i < 2; i++) {
        odd = i & 1;
        a = angle_atan2(seg_sqrt(pv->f20 * pv->f20 + pv->f28 * pv->f28), pv->f24);
        rot.f[0] = appr_2a9c50(-a, 1.57079637f);
        rot.f[1] = angle_atan2(pv->f28, pv->f20);
        rot.f[2] = 0.0f;
        rot.f[3] = 0.0f;
        spin_angles_x = 0.0f;
        t = FUN_001fa6c0(D_L00_0015F5CC % scale_game_frames(180));
        {
            f32 d = scale_time(180.0f);
            f32 r;
            t *= 6.28318548f;
            r = fast_normalize_angle(t / d);
            if (odd) {
                r = -r;
            }
            spin_angles[1] = r;
        }
        spin_angles[2] = 0.0f;
        spin_angles[3] = 0.0f;
        rotation_matrix(mz, &spin_angles_x);
        rotation_matrix(mat, &rot);
        mmul_2a9c50(mat, mat, mz);
        qcopy(&mat[3], &pv->pos);
        quad.color[0] = 0x80808080;
        quad.color[1] = 0x80808080;
        quad.color[2] = 0x80808080;
        quad.color[3] = 0x80808080;
        quad.tex = get_effect_texture(odd ? 0x12 : 0x11);
        quad.unk80 = 0xFF9000000260L;
        quad.unk88 = 0x8000000048L;
        quad.unk70 = 0;
        quad.corner[0].f[0] = -1.0f;
        quad.corner[0].f[1] = 0.0f;
        quad.corner[0].f[2] = 1.0f;
        quad.corner[0].f[3] = 1.0f;
        quad.corner[1].f[0] = 1.0f;
        quad.corner[1].f[1] = 0.0f;
        quad.corner[1].f[2] = 1.0f;
        quad.corner[1].f[3] = 1.0f;
        quad.corner[2].f[0] = -1.0f;
        quad.corner[2].f[1] = 0.0f;
        quad.corner[2].f[2] = -1.0f;
        quad.corner[2].f[3] = 1.0f;
        quad.corner[3].f[0] = 1.0f;
        quad.corner[3].f[1] = 0.0f;
        quad.corner[3].f[2] = -1.0f;
        quad.corner[3].f[3] = 1.0f;
        quad.uv[0] = 0.0f;
        quad.uv[1] = 1.0f;
        quad.uv[2] = 1.0f;
        quad.uv[3] = 1.0f;
        quad.uv[4] = 0.0f;
        quad.uv[5] = 0.0f;
        quad.uv[6] = 1.0f;
        quad.uv[7] = 0.0f;
        draw_geometry_quad(&quad, mat, 1);
    }
}
extern float D_0015ED6C_2a9ed0 __asm__("D_0015ED6C");
extern int D_L00_0015F5CC_2a9ed0 __asm__("D_L00_0015F5CC");
float FUN_002132a8_2a9ed0(float, float) __asm__("FUN_002132a8");
void FUN_L00_00250df8_2a9ed0(void *) __asm__("FUN_L00_00250df8");
unsigned char *FUN_L00_002a9ed0(int owner, OvlQuad *pos) {
    unsigned char *m = create_moby(0x4A);
    if (m) {
        unsigned char *v = *(unsigned char **)(m + 0x78);
        m[0x30] = 0xFF;
        *(short *)(m + 0x32) = 0x7F;
        m[0x31] = 1;
        *(float *)(m + 0x2C) = *(float *)(m + 0x2C) * 0.5f;
        m[0x20] = 0;
        *(int *)(v + 0x30) = owner;
        *(short *)(v + 0x36) = 0;
        *(int *)(v + 0x78) = 0;
        qcopy(m + 0x10, pos);
        clear_u64_value(v);
        {
            float a =
                FUN_002132a8_2a9ed0(D_0015ED6C_2a9ed0 * 1.0471976f, D_0015ED6C_2a9ed0 * 3.1415927f);
            float d = D_0015ED6C_2a9ed0;
            float b;
            int x;
            float z;
            *(float *)(v + 0x38) = a;
            b = FUN_002132a8_2a9ed0(d * 1.0471976f, d * 3.1415927f);
            x = D_L00_0015F5CC_2a9ed0;
            z = 0.0f;
            *(float *)(v + 0x3C) = b;
            *(float *)(v + 0x64) = z;
            *(float *)(v + 0x60) = z;
            *(float *)(v + 0x70) = z;
            *(float *)(v + 0x6C) = z;
            *(int *)(v + 0x5C) = x;
            *(int *)(v + 0x74) = 0;
            *(int *)(v + 0x68) = -1;
            *(int *)(m + 0x94) = 0;
        }
        FUN_L00_00250df8_2a9ed0(m);
    }
    return m;
}
typedef union {
    u128 q;
    f32 f[4];
} V_2aa008;
typedef struct {
    u8 pad[0x5C];
    s32 i5C;
} D_2aa008;
typedef struct {
    u8 pad[0x34];
    s16 h34;
} M_2aa008;
typedef struct N_2aa008 {
    u8 pad[0x10];
    V_2aa008 v10;
    u8 b20;
    u8 pad2[0x28 - 0x21];
    struct N_2aa008 *p28;
    f32 f2C;
    u8 pad3[0x78 - 0x30];
    void *p78;
    u8 pad4[0xA6 - 0x7C];
    s16 hA6;
} N_2aa008;
typedef struct {
    u8 pad[0x10];
    V_2aa008 v10;
} Q_2aa008;
extern f32 D_0015ED6C_2aa008 __asm__("D_0015ED6C");
extern f32 D_0015ED70_2aa008 __asm__("D_0015ED70");
extern N_2aa008 *D_L00_0015FFE4_2aa008 __asm__("D_L00_0015FFE4");
extern V_2aa008 D_L00_00173E60_2aa008[] __asm__("D_L00_00173E60") __attribute__((section(".data")));
f32 FUN_002132a8_2aa008(f32, f32) __asm__("FUN_002132a8");
void FUN_001f9bf8_2aa008(void *, void *, f32) __asm__("FUN_001f9bf8");
s32 FUN_L00_002603d0_2aa008(void *) __asm__("FUN_L00_002603d0");
s32 FUN_001f96f8_2aa008(s32) __asm__("FUN_001f96f8");
s32 collision_line(void *, void *, s32, void *, s32) __asm__("FUN_001efa68");
void FUN_L00_001ff660_2aa008(void *, void *, void *) __asm__("FUN_L00_001ff660");
void FUN_L00_002aa008(V_2aa008 *pos, N_2aa008 *self, void *arg) {
    V_2aa008 d;
    V_2aa008 t;
    V_2aa008 e;
    M_2aa008 *m;
    struct Hero *P;
    N_2aa008 *n;
    s32 count;
    N_2aa008 *best;
    s32 bestv;
    V_2aa008 *k;
    t.q = 0;
    m = self->p78;
    t.f[0] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    t.f[1] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    t.f[2] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    self->b20 = 1;
    self->f2C = self->f2C / 0.65f;
    d.q = t.q;
    FUN_001f9bf8_2aa008(&d, &d,
                        FUN_002132a8_2aa008(D_0015ED6C_2aa008 * 0.01f, D_0015ED6C_2aa008 * 0.1f));
    add_vector_xyz(m, &d, arg);
    P = &hero;
    if (P->ground_moby && FUN_L00_002603d0_2aa008(P->ground_moby)) {
        add_vector_xyz(m, m, &P->motion.unk100);
    }
    m->h34 = FUN_001f96f8_2aa008(0x78);
    count = 0;
    best = 0;
    bestv = 0;
    for (n = D_L00_0015FFE4_2aa008; n; n = n->p28) {
        if (n->b20 != 0xFE)
            if (n->b20 != 0xFD)
                if (n->hA6 == self->hA6)
                    if (n != self) {
                        if (best == 0 || ((D_2aa008 *)n->p78)->i5C < bestv) {
                            bestv = ((D_2aa008 *)n->p78)->i5C;
                            best = n;
                        }
                        count++;
                    }
    }
    if (count >= 8)
        ((D_2aa008 *)best->p78)->i5C = -1;
    qcopy(&self->v10, pos);
    t.q = ((Q_2aa008 *)hero.moby)->v10.q;
    t.f[2] = pos->f[2];
    if (collision_line(&t, pos, 0, hero.moby, 0)) {
        k = D_L00_00173E60_2aa008;
        qcopy(&self->v10, &k[0]);
        FUN_001f9bf8_2aa008(&e, &k[2], D_0015ED70_2aa008 * 9.7f);
        add_vector_xyz(&self->v10, &self->v10, &e);
        FUN_L00_001ff660_2aa008(m, m, &k[2]);
        scale_vector_xyz(m, m, 0.6f);
    }
}
/* Ported from rac1-decomp (src/overlays/shared/vendor_002A5138.c: func_L00_002AB548), where it is exact; names translated to the US level program. */

typedef float V[4] __attribute__((aligned(16)));


extern V D_L00_00166DC0;
extern char *FUN_L00_002603d0_u(void *) __asm__("FUN_L00_002603d0");
extern char D_0013F350[];
extern f32 fast_add_rotations_c(f32, f32) __asm__("func_001FA580");
extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern float D_0015ED70;
extern float D_L00_00173E80[];
extern int D_L00_0015F5C4_c __asm__("D_L00_0015F5C4");
extern int D_L00_00173E40_u[] __asm__("D_L00_00173E40");
extern int FUN_001efa68(void*,void*,int,int,int);
extern int FUN_001f0b58(void);
extern int scale_game_frames_alt(int) __asm__("FUN_001f96f8");
extern int fast_dec_timer(int*) __asm__("FUN_001f9740");
extern void *D_L00_00173E58_c[] __asm__("D_L00_00173E58");
extern void FUN_L00_002a9c50_c(void) __asm__("FUN_L00_002a9c50");
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");
extern void scale_vector_xyz_c(void *, void *, float) __asm__("FUN_001f9a68");

int FUN_L00_002aa2a8(char *a0, char *o, int mode) {
    float w[4];
    float B[4];
    float C[4];
    float box[4];
    int x;
    char *base = D_0013F350;
    int i;
    char *tmp;
    if (*(int *)(base + 0x2084) == 0x72) return 0;
    if (D_L00_0015F5C4_c != 0) return 0;
    qcopy(C, o + 0x10);
    if (*(unsigned char *)(o + 0x20) == 0) {
        w[0] = fast_cos(fast_add_rotations_c(-0.36196801f, FUN_001f9e90(*(float *)(base + 0x670), *(float *)(base + 0x674)))) * 0.859039f;
        w[1] = fast_sin(fast_add_rotations_c(-0.36196801f, FUN_001f9e90(*(float *)(base + 0x670), *(float *)(base + 0x674)))) * 0.859039f;
        *(int *)&w[2] = 0;
        add_vector_xyz(w, w, base + 0x80);
        w[2] = w[2] + 0.49082f;
        qcopy(B, a0);
        if (*(int *)(base + 0x2FC) != 0 && FUN_L00_002603d0_u((void *)*(int *)(base + 0x2FC)) != 0 && mode != 0) {
            add_vector_xyz(B, B, base + 0x100);
        }
        x = scale_game_frames_alt(0x78);
    } else {
        tmp = *(char **)(*(char **)(a0 + 0x30) + 0x78);
        qcopy(w, o + 0x10);
        qcopy(B, a0);
        {
            short xs = *(short *)(a0 + 0x34);
            int c50 = *(int *)(tmp + 0x50);
            x = xs;
            if (c50 != 0) *(short *)(a0 + 0x36) = 1;
        }
    }
    {
        char *base2 = D_0013F350;
        char *b2 = *(char **)(base2 + 0x2080);
        *(u128 *)box = *(u128 *)(b2 + 0x10);
        box[2] = w[2];
        if (FUN_001efa68(box, w, 0x10, (int)b2, 0) != 0) {
            if (FUN_001f0b58() != 0 && D_L00_00173E40_u[7] > 0) {
                qcopy(a0 + 0x10, (char *)D_L00_00173E40_u + 0x20);
            }
        }
    }
    while (fast_dec_timer(&x) == 0) {
        qcopy(C, w);
        i = 9;
        do {
            add_vector_xyz(w, w, B);
            B[2] = B[2] - D_0015ED70 * 9.8f;
        } while (--i >= 0);
        if (FUN_001efa68(C, w, 0x12, (int)o, 0) == 0) continue;
        if (FUN_001f0b58() == 0 && 0.0f < B[2]) continue;
        if (D_L00_00173E40_u[7] > 0) {
            qcopy(a0 + 0x10, (char *)D_L00_00173E40_u + 0x20);
            break;
        }
    }
    if (x != 0) {
        if (mode == 0) {
            if (D_L00_00173E58_c[0] == 0) return 0;
            if (FUN_L00_002603d0_u(D_L00_00173E58_c[0]) == 0) return 0;
        }
        if (mode != 2 || D_L00_00173E58_c[0] == 0 || FUN_L00_002603d0_u(D_L00_00173E58_c[0]) == 0) {
            enqueue_callback_list_1_alt(FUN_L00_002a9c50_c, o);
        }
        {
            char *g = (char *)&D_L00_00166DC0;
            char *a10 = a0 + 0x10;
            *(u128 *)(a0 + 0x20) = *(u128 *)D_L00_00173E80;
            subtract_vector_xyz(C, a10, g);
            scale_vector_xyz_c(C, C, 0.95f);
            add_vector_xyz(a10, C, g);
        }
        return 1;
    }
    return 0;
}
