/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"
#include "qcopy.h"

/* Oltanis (level 14) vendor code.  Both bodies below were written from the
 * retail disassembly and reproduce it byte for byte on the game compiler
 * route (cc1, Ps2EeAs). */

extern int D_001413DC __attribute__((section(".data")));
extern u8 *D_L14_00167500 __attribute__((section(".data")));

/* 0x003135B8, 80 bytes.  When the level record's field at 0x86 is 7, seed the
 * sub-record reached through +0x70 with the caller's argument and two float
 * constants, and set both floats on the record itself. */
void FUN_L14_003135b8(u8 *arg0)
{
    u8 *g = D_L14_00167500;
    u8 *q;
    u8 *p;

    if (*(s16 *)(g + 0x86) != 7) {
        return;
    }
    q = *(u8 **)(g + 0x70) + 0x40;
    *(s32 *)(q + 0x40) = 1;
    *(s32 *)(q + 0x44) = (s32)arg0;
    *(f32 *)(q + 0x4C) = 2.0f;
    p = *(u8 **)(g + 0x70);
    *(f32 *)(p + 0xA0) = 7.0f;
    *(f32 *)(p + 0xB0) = 2.0f;
}

/* 0x003167E0, 36 bytes.  While the executable's mode word is not 0xF, mark the
 * object's field at 0x7E as 3. */
void FUN_L14_003167e0(u8 *arg0)
{
    if (D_001413DC != 0x0F) {
        *(s16 *)(arg0 + 0x7E) = 3;
    }
}


extern u8 *FUN_0020c4f8(s32);
extern void FUN_L00_00250df8(u8 *);

/* Allocate 0x574 bytes, copy the two 16-byte records out of the caller, stamp
 * the header fields and hand it to the level's post-create hook.  Returns the
 * allocation, null when it failed.  The two 16-byte copies go through $2 with
 * each address in its own register -- the qcopy idiom, see include/qcopy.h. */
u8 *FUN_L14_00306158(u8 *self)
{
    u8 *o = FUN_0020c4f8(0x574);

    if (o != 0) {
        qcopy(o + 0x10, self + 0x10);
        qcopy(o + 0x40, self + 0x40);
        o[0x30] = 0x40;
        o[0x20] = 0;
        *(s16 *)(o + 0x32) = 0x40;
        o[0x31] = 1;
        FUN_L00_00250df8(o);
    }
    return o;
}

INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00300e00.s", FUN_L14_00300e00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003014e0.s", FUN_L14_003014e0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305408.s", FUN_L14_00305408);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305600.s", FUN_L14_00305600);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305680.s", FUN_L14_00305680);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305758.s", FUN_L14_00305758);
#define NOT_SDA

#define MACRO_ADDR

/* Updates and draws four scrolling particle streaks for an Oltanis moby. */
/* Ported from rac1-decomp (PAL, src/overlays/l14_oltanis/vendor_002FF358.c: func_L14_00306FA0), where it is exact; names translated to the US level program. */

typedef struct {
    float pad[2];
    float z;
    float pad2[5];
    float a[4];
    float b[4];
    int t[4];
    float c[4];
} FxData14;

extern char D_L14_001674C0[];
extern f32 ConvertIntegerToFloat(s32) __asm__("func_001FA6C0");
extern int FUN_001fa6e0(int, int, float);
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern unsigned char *FUN_L00_00272f68(float f, void *pos, int a1, unsigned char a2, int idx, int flag, int s, int mode);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
extern void tick_countdown_32(void *) __asm__("func_001F9740");
float AbsoluteFloat(float input) __asm__("func_001F99C0");
extern int func_001F9908_r(int *arg0) __asm__("FUN_001f9740");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L14_00305b18(char *p) {
    float v[8];
    FxData14 *m = *(FxData14 **)(p + 0x78);
    float *a;
    int *t;
    int i, j, c, k;
    float f, g;
    j = 0;
    m->z += 0.1f;
    subtract_vector_xyz(v, D_L14_001674C0, m);
    t = m->t;
    a = m->a;
    normalize_vector_xyz(v, v, -0.3f);
    normalize_vector_xyz(&v[4], v, 0.1f);
    add_vector_xyz(v, v, m);
    m->z -= 0.1f;
    for (i = 3; i >= 0; i--) {
        f = *a + m->b[j];
        *a = f;
        if (f >= 255.0f) {
            *a = f - 255.0f;
        } else if (f <= 0.0f) {
            *a = f + 255.0f;
        }
        if (func_001F9908_r(t)) {
            m->t[j] = scale_game_frames(255);
        }
        t++;
        g = ConvertIntegerToFloat(scale_game_frames(255) - m->t[j]);
        g = g / (float)scale_game_frames(255);
        c = FUN_001fa6e0(0x4040FFFF, 0x1040FFFF, AbsoluteFloat(0.5f - g));
        k = func_001FA898_r(*a++);
        FUN_L00_00272f68(m->c[j], v, c, k, 0x35, 1, 2, 0);
        j++;
        add_vector_xyz(v, v, &v[4]);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00305d28.s", FUN_L14_00305d28);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003061d8.s", FUN_L14_003061d8);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l14_oltanis/vendor_002FF358.c: func_L14_00307680), where it is exact; names translated to the US level program. */

void FUN_L14_003061f8(int unused, char *moby) {
    char *d = *(char **)(moby + 0x78);
    d[0x28] = 4;
    *(int *)(d + 0x20) = 0;
    *(short *)(d + 0x24) = 0;
    *(short *)(d + 0x3E) = 0;
    moby[0x20] = 1;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00306b78.s", FUN_L14_00306b78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00306ee0.s", FUN_L14_00306ee0);
/* Precomputes per-point segment values of a path and snaps the moby to its first point. */
/* Ported from rac1-decomp (PAL, src/overlays/l14_oltanis/vendor_002FF358.c: func_L14_00308998), where it is exact; names translated to the US level program. */

extern char *D_L14_001B0BB0[];
extern float FUN_001f9b48(void *, void *);
extern float FUN_001f9e90(float, float);

void FUN_L14_00307510(char *moby) {
    char *d = *(char **)(moby + 0x78);
    char *p = D_L14_001B0BB0[*(int *)(d + 0x78)];
    int i;
    for (i = 0; i < *(int *)p; i++) {
        int o = i * 16;
        float f = FUN_001f9b48(p + (o + 0x10), p + (((i + 1) % *(int *)p) * 16 + 0x10));
        *(float *)(p + o + 0x1C) = f;
    }
    *(int *)(d + 0x70) = 0;
    *(int *)(d + 0x74) = 0;
    qcopy(moby + 0x10, p + 0x10);
    *(float *)(moby + 0x48) = FUN_001f9e90(*(float *)(p + 0x20) - *(float *)(p + 0x10), *(float *)(p + 0x24) - *(float *)(p + 0x14));
    *(float *)(d + 0x90) = *(float *)(d + 0x94) = *(float *)(d + 0x98) = *(float *)(d + 0x80) = *(float *)(d + 0x84) = *(float *)(d + 0x88) = 0.0f;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00307620.s", FUN_L14_00307620);
extern void FUN_L12_002e71b0(void);
void enqueue_callback_list_1(int arg0, int arg1) __asm__("FUN_001f4600");
/* 0x00307a80, 84 bytes.
 * Ported from rac1-decomp (PAL, src/overlays/l14_oltanis/vendor_002FF358.c:
 * func_L14_00308F08), where it is exact; names translated to the US level
 * program. The size-matched PAL neighbour was the callback this one enqueues,
 * not this body. */
void FUN_L14_00307a80(unsigned char *moby) {
    switch (moby[0x20]) {
    case 0:
        moby[0x20] = 1;
        moby[0x30] = 0xFF;
        break;
    case 1:
        enqueue_callback_list_1((int)FUN_L12_002e71b0, (int)moby);
        break;
    }
}

/* Play the level sound once on first update, then handle the two-state moby. */
/* Ported from rac1-decomp (PAL, src/overlays/l14_oltanis/vendor_002FF358.c: func_L14_00309C48), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x30];
    int state;
    char pad34[0x144];
    int v178[2];
} Level14State;

extern Level14State D_L14_0016CF60;
extern int D_L14_0015F5C4;
extern int FUN_L01_0026e008(int, int);
extern unsigned char D_0013D408[];
extern void FUN_L00_002637f8(int);
extern void FUN_L00_00263d40(int arg0, int arg1);
s32 allocate_voice_for_bank_entry(s32 arg1, s32 arg0, s32 arg2) __asm__("FUN_0022db10");

void FUN_L14_003087c0(unsigned char *moby) {
    int *d = *(int **)(moby + 0x78);
    unsigned v;
    int i;
    if (d[0] != -1) {
        if (FUN_L01_0026e008(d[0], -1) == 0) {
            if (D_0013D408[0x17] == 0) {
                D_0013D408[0x17] = 1;
                allocate_voice_for_bank_entry(1, 0, 0);
                FUN_L00_00263d40(0x53d6, -1);
            }
        }
    }
    switch (moby[0x20]) {
    case 0:
        moby[0x30] = 0xFF;
        moby[0x20] = 1;
        break;
    case 1:
        if (D_L14_0015F5C4 == 2) {
            v = D_L14_0016CF60.state - 3;
            if (v < 3) {
                i = 0;
                if (v <= D_L14_0015F5C4) i = moby[0x20];
                FUN_L00_002637f8(D_L14_0016CF60.v178[i]);
            }
        }
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00314f00.s", FUN_L14_00314f00);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00315290.s", FUN_L14_00315290);
#ifndef NOT_SDA
#define NOT_SDA __attribute__((section(".data")))
#endif
#ifndef MACRO_ADDR
#define MACRO_ADDR __attribute__((section(".sdata")))
#endif
extern int func_L10_002F6E38_15920(void *) __asm__("FUN_L10_002f5a78");
extern char *D_L14_0015F050_15920 __asm__("D_L14_0015EF50") MACRO_ADDR;
extern char D_0013E633_15920[] __asm__("D_001413DC");
int FUN_L14_00315920(char *a, char *b) {
    char *rec = *(char **)(D_L14_0015F050_15920 + *(short *)(a + 0x84) * 32 + 0x1C);
    int t, u;
    if (*(unsigned char *)(rec + 0x38) != 0) return -1;
    if (b != 0 && *(short *)(b + 0x7E) == 0) {
        if (*(int *)(D_0013E633_15920) != 15) return 0;
    }
    if (func_L10_002F6E38_15920(a) == 0) return 0;
    t = *(int *)(rec + 0x48);
    if (t >= 0 && *(int *)(D_0013E633_15920) != t) return 0;
    u = *(int *)(rec + 0x44);
    if (u >= 0 && *(int *)(D_0013E633_15920 - 0x8) != u) return 0;
    return 1;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_003159d8.s", FUN_L14_003159d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00315d48.s", FUN_L14_00315d48);
INCLUDE_ASM("config/us/overlays/asm/FUN_L14_00316748.s", FUN_L14_00316748);
