/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002d9e08, 108 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
// Walks a moby index list and, for each moby of one type, sets its state to 2 and a float to 1.0.
void FUN_L06_002d9e08(int index)
{
    short *p = D_L06_001ABFC0[index];
    if (p != 0) {
        do {
            char *moby = (char *)(((*(unsigned short *)p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d);
            if (*(short *)(moby + 0xA6) == 0x16F) {
                moby[0x20] = 2;
                *(float *)(*(char **)(moby + 0x78) + 0x28) = 1.0f;
            }
        } while (*p++ >= 0);
    }
}

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002d9e78, 100 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
void FUN_L06_002d9e78(int idx)
{
    short *p = D_L06_001ABFC0[idx];
    if (p != 0) {
        do {
            char *moby = (char *)(((*p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d);
            if (*(short *)(moby + 0xA6) == 0x16F) {
                char *data = *(char **)(moby + 0x78);
                moby[0x20] = 2;
                *(int *)(data + 0x28) = 0;
            }
        } while (*p++ >= 0);
    }
}

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002e9e30, 108 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
/* Switches every moby listed in a table into state 15 until a negative entry. */
void FUN_L06_002e9e30(int index) {
    short *p = D_L06_001ABFC0[index];
    do {
        char *moby = D_L06_0015FFD8_d + ((*(unsigned short *)p & 0x7FFF) << 8);
        if ((unsigned char)moby[0x20] < 0x7F) {
            unsigned short flags = *(unsigned short *)(moby + 0x34);
            moby[0x20] = 15;
            flags |= 0x41;
            *(int *)(moby + 0x94) = 0;
            flags &= 0xEFFF;
            *(unsigned short *)(moby + 0x34) = flags;
        }
    } while (*p++ >= 0);
}

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f45a0, 80 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
/* Clears state 4 from every moby in the selected table. */
void FUN_L06_002f45a0(int idx)
{
    short *p = D_L06_001ABFC0[idx];
    do {
        char *moby = (char *)(((*p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d);
        if ((unsigned char)moby[0x20] == 4) {
            moby[0x20] = 0;
        }
    } while (*p++ >= 0);
}

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f45f0, 72 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
/* Sets each moby in the selected table to state 4 until its terminal entry. */
void FUN_L06_002f45f0(int idx)
{
    short *p = D_L06_001ABFC0[idx];
    do {
        char *moby = (char *)(((*p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d);
        moby[0x20] = 4;
    } while (*p++ >= 0);
}

#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002F6790), where it is exact; names translated to the US level program. */

extern void FUN_0022da68(int, int, int);

void FUN_L06_002f5360(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char **p;
    int i;
    moby[0xBC] = 1;
    if ((unsigned char)moby[0x20] == 2) {
        FUN_0022da68(0, 0, (int)moby);
        moby[0x20] = 4;
        p = (char **)(data + 0x24);
        *(int *)(data + 0x14) = 0;
        *(int *)(data + 0x18) = 0;
        for (i = 6; i >= 0; i--) {
            (*p++)[0x20] = 5;
        }
    }
}
/* Switches a moby from state 6 to 8 and sets its ten children to state 9. */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002F6818), where it is exact; names translated to the US level program. */

void FUN_L06_002f53e8(char *moby)
{
    char *data = *(char **)(moby + 0x78);
    int i;
    char **p;
    moby[0xBC] = 1;
    if ((unsigned char)moby[0x20] == 6) {
        unsigned short fl;
        FUN_0022da68(0, 0, (int)moby);
        fl = *(unsigned short *)(moby + 0x34);
        moby[0x31] = 1;
        fl &= 0xFFFE;
        moby[0x20] = 8;
        *(unsigned short *)(moby + 0x34) = fl;
        *(int *)(data + 0x18) = 0;
        p = (char **)(data + 0x24);
        for (i = 6; i >= 0; i--) {
            char *c = *p;
            c[0x20] = 9;
            *(unsigned short *)(*p + 0x34) &= 0xFFFE;
            (*p)[0x31] = 1;
            p++;
        }
    }
}
extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f9698, 96 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
void FUN_L06_002f9698(char *arg)
{
    short *table = D_L06_001ABFC0[(unsigned char)arg[0x21]];
    if (table != 0) {
        short *p = table;
        do {
            char *moby = (char *)(((*p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d);
            if ((unsigned char)moby[0x20] == 1) {
                moby[0x20] = 2;
            }
        } while (*p++ >= 0);
    }
}

#define NOT_SDA

#define MACRO_ADDR

/* angle from a moby to its owner, clamped to the gaps between obstacles in its list */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FAB28), where it is exact; names translated to the US level program. */

extern char *D_L06_0015FFD8;
extern char D_0013E533[];
extern float FUN_001f9b48(void *, void *);
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float FUN_001fa580(float, float);
extern float FUN_001fa5c8(float, float);
extern float FUN_001fa688(float, float);
extern float FUN_001f9e90(float, float);
extern short *D_L06_001ABFC0_p[] __asm__("D_L06_001ABFC0");
extern short D_L06_00161ED8_d __asm__("D_L06_00161ED8") __attribute__((sda));
extern void FUN_001f9a10(void *, void *, void *);

float FUN_L06_002f96f8(char *self) {
    char *owner = *(char **)(*(char **)(self + 0x78) + 0x160);
    float hi, lo, ang, dist, v[3];
    short *p;
    if ((unsigned char)self[0x21] == 0xFF) {
        return FUN_001f9e90(*(float *)(self + 0x10) - *(float *)(owner + 0x10),
                                 *(float *)(self + 0x14) - *(float *)(owner + 0x14));
    }
    lo = -(*(float *)&D_L06_00161ED8_d * 0.017453292f);
    hi = *(float *)&D_L06_00161ED8_d * 0.017453292f;
    ang = FUN_001f9e90(*(float *)(self + 0x10) - *(float *)(owner + 0x10),
                            *(float *)(self + 0x14) - *(float *)(owner + 0x14));
    dist = FUN_001f9b48(owner + 0x10, self + 0x10);
    v[0] = FUN_001f9dc8(ang) * 2.0f;
    v[1] = FUN_001f9de0(ang) * 2.0f;
    v[2] = 0.0f;
    FUN_001f9a10(v, v, D_0013E533 + 0xE9D);
    p = D_L06_001ABFC0_p[(unsigned char)self[0x21]];
    if (p == 0) {
        return 0.0f;
    }
    do {
        int idx = *(unsigned short *)p & 0x7FFF;
        char *e = (char *)(idx * 256 + (int)D_L06_0015FFD8);
        if ((unsigned char)e[0x20] == 8 || FUN_001f9b48(e + 0x10, owner + 0x10) < dist) {
            float d = FUN_001f9e90(*(float *)(D_L06_0015FFD8 + idx * 256 + 0x10) - *(float *)(owner + 0x10),
                                        *(float *)(D_L06_0015FFD8 + idx * 256 + 0x14) - *(float *)(owner + 0x14));
            float r = FUN_001fa5c8(d, ang);
            if (r > 0.0f && r < hi) {
                hi = r;
            } else if (r < 0.0f && r > lo) {
                lo = r;
            }
        }
    } while (*p++ >= 0);
    return FUN_001fa580(FUN_001fa580(lo, FUN_001fa688(hi, lo) * 0.5f), ang);
}
extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f9948, 100 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
void FUN_L06_002f9948(int idx)
{
    short *p = D_L06_001ABFC0[idx];
    if (p != 0) {
        do {
            char *moby = D_L06_0015FFD8_d + ((*p & 0x7FFF) << 8);
            unsigned short flags = *(unsigned short *)(moby + 0x34);
            moby[0x20] = 0x12;
            flags |= 1;
            *(int *)(moby + 0x94) = 0;
            flags &= 0xEFFF;
            *(unsigned short *)(moby + 0x34) = flags;
        } while (*p++ >= 0);
    }
}

extern int D_L06_001ABFC0[];
extern int D_L06_0015FFD8_d __asm__("D_L06_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f99b0, 120 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
// Resets every moby of a list that is in state 0x12.
void FUN_L06_002f99b0(int index)
{
    short *p = D_L06_001ABFC0[index];
    if (p != 0) {
        do {
            char *moby = (char *)((*(unsigned short *)p & 0x7FFF) << 8) + (int)D_L06_0015FFD8_d;
            if ((unsigned char)moby[0x20] == 0x12) {
                unsigned short flags = *(unsigned short *)(moby + 0x34);
                moby[0x20] = 0;
                flags &= 0xFFFE;
                flags |= 0x1000;
                *(int *)(moby + 0x94) = *(int *)(*(char **)(moby + 0x24) + 0x10);
                *(unsigned short *)(moby + 0x34) = flags;
            }
        } while (*p++ >= 0);
    }
}

#include "qcopy.h"

/* raise each listed moby's position z by a fixed amount and notify it */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FC4C0), where it is exact; names translated to the US level program. */

extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_L06_002e9d10(void *, void *);
extern short *D_L06_001ABFC0_c[] __asm__("D_L06_001ABFC0");

void FUN_L06_002fb090(char *moby) {
    char *data = *(char **)(moby + 0x78);
    short *q = D_L06_001ABFC0_c[*(int *)(data + 0xF0)];
    short *p;
    if (q != 0) {
        p = q;
        do {
            int off = (*(unsigned short *)p & 0x7FFF) << 8;
            float v[4];
            qcopy(v, (char *)(off + (int)D_L06_0015FFD8) + 0x10);
            v[2] = v[2] + random_float_between_alt(15.0f, 20.0f);
            FUN_L06_002e9d10((char *)((int)D_L06_0015FFD8 + off), v);
        } while (*p++ >= 0);
    }
}
#include "qcopy.h"

/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FC6D8), where it is exact; names translated to the US level program. */

extern char D_0013F350[];
extern char D_L06_00167540[] __attribute__((section(".data")));
extern float D_0015ED6C __attribute__((section(".sdata")));
extern short D_0015ED70_s __asm__("D_0015ED70");
extern float FUN_001f9b80(void *, void *);
extern float FUN_00213f38(float *, float *, float, float, float, float);
extern float FUN_001f9e90(float, float);
extern void FUN_001f99f8(void *);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a40(void *, void *, void *, float);
extern void FUN_001f9bf8(void *, void *, float);
extern void FUN_L00_002ea9d8(void *);

int FUN_L06_002fb2a8(char *moby) {
    float v0[4], m[4], v1[4], v2[4];
    char *data;
    char *pos;
    char *x;
    float t;
    data = *(char **)(moby + 0x78);
    FUN_001f99f8(m);
    if (*(unsigned char *)(moby + 0x53) == 8) {
        qcopy(v0, D_L06_00167540);
        pos = moby + 0x10;
    } else {
        t = *(float *)&D_0015ED70_s * 3.0f;
        FUN_00213f38((float *)(data + 0x118), (float *)(data + 0x11C), 1.0f, t, t, D_0015ED6C + D_0015ED6C);
        FUN_001f9bf8(v1, moby + 0xC0, 8.0f);
        FUN_001f9a10(v1, v1, moby + 0x10);
        x = D_0013F350;
        v1[2] = *(float *)(x + 0x88) + 2.0f;
        FUN_001f9bf8(v2, x, -7.0f);
        FUN_001f9a10(v2, v2, x + 0x80);
        v2[2] += 4.0f;
        pos = moby + 0x10;
        FUN_001f9a40(v0, v1, v2, *(float *)(data + 0x118));
    }
    m[2] = FUN_001f9e90(*(float *)(moby + 0x10) - v0[0], *(float *)(moby + 0x14) - v0[1]);
    m[1] = -FUN_001f9e90(FUN_001f9b80(v0, pos), *(float *)(moby + 0x18) - v0[2])
         - (1.0f - *(float *)(data + 0x118)) * 30.0f * 0.017453293f;
    FUN_L00_002ea9d8(v0);
    FUN_L00_002ea9d8(m);
    if (*(float *)(data + 0x118) >= 1.0f && *(unsigned char *)(moby + 0x53) == 1) return 1;
    return 0;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FC8E0), where it is exact; names translated to the US level program. */

extern int *D_L06_001B0C30[];
extern void FUN_L00_002eac18(int);
extern void FUN_L06_002356a0(int, int);

void FUN_L06_002fb4b0(char *arg) {
    char *data = *(char **)(arg + 0x78);
    FUN_L06_002356a0(0, 0);
    *D_L06_001B0C30[*(int *)(data + 0xEC)] = *(int *)(data + 0x114);
    FUN_L00_002eac18(2);
}
/* Steers a moby's camera-like orientation toward a target point, returns 1 when done. */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FCA98), where it is exact; names translated to the US level program. */

extern char D_L06_00167540[];
extern float D_0015ED6C;
extern float D_0015ED70;
extern void FUN_L06_00312a78(void *);
extern void FUN_L06_00312ad0(void *);

int FUN_L06_002fb668(char *moby) {
    float v0[4], m[4], v1[4], v2[4];
    char *data;
    char *pos;
    char *x;
    float t;
    data = *(char **)(moby + 0x78);
    FUN_001f99f8(m);
    if (*(unsigned char *)(moby + 0x53) == 6) {
        qcopy(v0, D_L06_00167540);
        pos = moby + 0x10;
    } else {
        t = D_0015ED70 * 0.5f;
        FUN_00213f38((float *)(data + 0x118), (float *)(data + 0x11C), 1.0f, t, t, D_0015ED6C * 0.5f);
        FUN_001f9bf8(v1, moby + 0xC0, 8.0f);
        FUN_001f9a10(v1, v1, moby + 0x10);
        x = D_0013F350;
        v1[2] = *(float *)(x + 0x88) + 2.0f;
        FUN_001f9bf8(v2, x, -7.0f);
        FUN_001f9a10(v2, v2, x + 0x80);
        v2[2] += 4.0f;
        pos = moby + 0x10;
        FUN_001f9a40(v0, v1, v2, *(float *)(data + 0x118));
    }
    m[2] = FUN_001f9e90(*(float *)(moby + 0x10) - v0[0], *(float *)(moby + 0x14) - v0[1]);
    m[1] = -FUN_001f9e90(FUN_001f9b80(v0, pos), *(float *)(moby + 0x18) - v0[2])
         - (1.0f - *(float *)(data + 0x118)) * 30.0f * 0.017453293f;
    FUN_L06_00312a78(v0);
    FUN_L06_00312ad0(m);
    if (*(float *)(data + 0x118) >= 1.0f && *(unsigned char *)(moby + 0x53) == 1) return 1;
    return 0;
}
/* Registers the moby's draw callbacks, choosing by its four slot ids. */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FE4B8), where it is exact; names translated to the US level program. */

extern int is_point_inside_clip_volume_alt(void *, int) __asm__("FUN_00214720");
extern void FUN_L06_002fd1a0(void);
extern void FUN_L06_002fd460(void);
extern void FUN_L06_002fd748(void);
void enqueue_callback_list_1(s32 arg0, s32 arg1) __asm__("FUN_001f4600");

void FUN_L06_002fd088(char *moby) {
    int *data = *(int **)(moby + 0x78);
    int *p;
    int i;
    enqueue_callback_list_1((void *)FUN_L06_002fd460, moby);
    p = data;
    for (i = 0; i < 4; p++, i++) {
        if (*p < 0) continue;
        if (is_point_inside_clip_volume_alt(D_L06_00167540, *p)) {
            enqueue_callback_list_1((void *)FUN_L06_002fd1a0, moby);
            break;
        }
    }
    p = data + 0x10;
    for (i = 0; i < 4; p++, i++) {
        char *g = (char *)D_0013E533 + 0xE1D;
        if (*(int *)(g + 0x208C) == 15 || (*p >= 0 && is_point_inside_clip_volume_alt(D_L06_00167540, *p))) {
            enqueue_callback_list_1((void *)FUN_L06_002fd748, moby);
            return;
        }
    }
}

INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002b4770.s", FUN_L06_002b4770);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002d9d10.s", FUN_L06_002d9d10);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002e9d10.s", FUN_L06_002e9d10);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002e9ea0.s", FUN_L06_002e9ea0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f3ad8.s", FUN_L06_002f3ad8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f3d70.s", FUN_L06_002f3d70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f4130.s", FUN_L06_002f4130);
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002F57C0), where it is exact; names translated to the US level program. */

extern char D_001404A8[];
extern float fast_cos(float) __asm__("func_001F9DC8");
extern float fast_sin(float) __asm__("func_001F9DE0");
extern int FUN_001efa68(void *, void *, int, void *, void *);
extern short D_L06_00161CEC_d __asm__("D_L06_00161CEC") __attribute__((sda));
extern short D_L06_00161CF0_d __asm__("D_L06_00161CF0") __attribute__((sda));
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");

void FUN_L06_002f4390(char *m)
{
    struct {
        int pad0[2];
        float f8;
        float fC;
        char *owner;
        int flags;
        char b18;
        char b19;
        short s1A;
        float f1C;
        int i20;
    } q;
    float v[4];
    float w[4];
    char *d;
    float sp;
    int fl;

    fl = 0x10000;
    if (*(int *)(D_001404A8) != 6) fl = 0x10001;
    q.flags = fl;
    d = *(char **)(m + 0x78);
    q.owner = m;
    q.f1C = 1.0f;
    q.i20 = 1;
    FUN_001f99f8(&q);
    q.f8 = 1.0f;
    q.fC = 5627.9248046875f;
    q.b18 = 3;
    q.b19 = 1;
    q.s1A = *(unsigned short *)(m + 0xA6);
    sp = (*(float *)(d + 0x70) * 60.0f - (float)*(int *)(d + 0x88)) * (*(float *)&D_L06_00161CEC_d * D_0015ED6C);
    if (*(float *)&D_L06_00161CF0_d < sp) sp = *(float *)&D_L06_00161CF0_d;
    normalize_vector_xyz(v, m + 0xD0, 0.125f);
    add_vector_xyz(v, v, m + 0x10);
    v[2] = v[2] + 0.125f;
    w[0] = fast_cos(*(float *)(m + 0x48)) * sp;
    w[1] = fast_sin(*(float *)(m + 0x48)) * sp;
    w[2] = 0;
    add_vector_xyz(w, w, v);
    FUN_001efa68(v, w, 0, m, &q);
    normalize_vector_xyz(v, m + 0xD0, -0.125f);
    add_vector_xyz(v, v, m + 0x10);
    v[2] = v[2] + 0.125f;
    w[0] = fast_cos(*(float *)(m + 0x48)) * sp;
    w[1] = fast_sin(*(float *)(m + 0x48)) * sp;
    w[2] = 0;
    add_vector_xyz(w, w, v);
    FUN_001efa68(v, w, 0, m, &q);
}
/* Puts a moby in state 2 and its seven linked mobys in state 3, resetting each one's heading. */
/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002F68D0), where it is exact; names translated to the US level program. */

extern f32 fast_subtract_rotations(f32, f32) __asm__("func_001FA5C8");
extern void FUN_L00_00250df8(void *);

void FUN_L06_002f54a0(char *a) {
    char *data = *(char **)(a + 0x78);
    char **p;
    int i;
    a[0xBC] = 1;
    if (*(unsigned char *)(a + 0x20) == 6) {
        a[0x20] = 2;
        a[0x31] = 1;
        *(unsigned short *)(a + 0x34) &= 0xFFFE;
        *(int *)(data + 0x14) = 0;
        *(float *)(a + 0x40) = fast_subtract_rotations(*(float *)(data + 0x10), *(float *)(data + 0x14));
        FUN_L00_00250df8(a);
        p = (char **)(data + 0x24);
        for (i = 0; i < 7; i++) {
            char *c = p[i];
            char *d;
            c[0x20] = 3;
            d = *(char **)(c + 0x78);
            *(unsigned short *)(p[i] + 0x34) &= 0xFFFE;
            p[i][0x31] = 1;
            *(int *)(d + 0x14) = 0;
            *(float *)(p[i] + 0x40) = fast_subtract_rotations(*(float *)(d + 0x10), *(float *)(d + 0x14));
            FUN_L00_00250df8(p[i]);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f55a0.s", FUN_L06_002f55a0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f5d78.s", FUN_L06_002f5d78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f6470.s", FUN_L06_002f6470);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f6dd0.s", FUN_L06_002f6dd0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f7000.s", FUN_L06_002f7000);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f7d78.s", FUN_L06_002f7d78);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f91e8.s", FUN_L06_002f91e8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002f9a28.s", FUN_L06_002f9a28);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002fa9c0.s", FUN_L06_002fa9c0);
#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/l06_blarg/vendor_002B5990.c: func_L06_002FC578), where it is exact; names translated to the US level program. */

extern char *D_L06_0016016C __asm__("D_L06_001600EC") MACRO_ADDR;
extern char D_0013E633[] __asm__("D_0013F3D0");
extern int *D_L06_001B0FB0[] __asm__("D_L06_001B0C30");
extern void FUN_L00_00216f90(void *, void *, int, int);
extern void FUN_L00_002eaaa0(void *, void *, int, int, int);
extern void clear_vector(void *) __asm__("FUN_001f99f8");

void FUN_L06_002fb148(char *moby) {
    float v0[4], m[4], v1[4];
    char *data = *(char **)(moby + 0x78);
    char *base = D_L06_0016016C + (*(int *)(data + 0xF8) << 7);
    *(int *)(data + 0x118) = 0;
    FUN_L00_00216f90(base + 0x30, base + 0x70, 0x72, 0);
    qcopy(v0, moby + 0x10);
    v0[2] = *(float *)(D_0013E633 + 0x8) + 2.0f;
    normalize_vector_xyz(v1, moby + 0xC0, 8.0f);
    add_vector_xyz(v0, v0, v1);
    clear_vector(m);
    m[2] = FUN_001f9e90(*(float *)(moby + 0x10) - v0[0], *(float *)(moby + 0x14) - v0[1]);
    m[1] = -FUN_001f9e90(FUN_001f9b80(v0, moby + 0x10), *(float *)(moby + 0x18) - v0[2]) - 0.5235988f;
    FUN_L00_002eaaa0(v0, m, 1, 0, 0);
    FUN_L00_002ea9d8(v0);
    FUN_L00_002ea9d8(m);
    *D_L06_001B0FB0[*(int *)(data + 0xEC)] = 0;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002fbc88.s", FUN_L06_002fbc88);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002fbfb0.s", FUN_L06_002fbfb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L06_002fc640.s", FUN_L06_002fc640);
