/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

typedef struct {
    unsigned char pad0[0x10];
    int flags;
    float f14;
    unsigned char pad18[4];
    float f1C;
    unsigned char pad20[4];
    float f24;
} S_2e89b0;
typedef struct {
    unsigned char pad0[0x40];
    unsigned short u40;
    unsigned short u42;
    int i44;
} G_2e89b0;
extern float D_0013CA40_2e89b0[] __asm__("D_0013CA40") __attribute__((section(".data")));
extern int D_0015EDE0_2e89b0 __asm__("D_0015EDE0");
extern int D_0015EDDC_2e89b0 __asm__("D_0015EDDC");
extern int D_0015EEA4_2e89b0 __asm__("D_0015EEA4");
extern int D_0015ED84_2e89b0 __asm__("D_0015ED84");
extern float D_L00_0015EF44_2e89b0 __asm__("D_L00_0015EF44");
extern int D_L00_00161D8C_2e89b0 __asm__("D_L00_00161D8C") __attribute__((sda));
extern int D_L00_00161D90_2e89b0 __asm__("D_L00_00161D90") __attribute__((sda));
extern G_2e89b0 D_00141848_2e89b0 __asm__("D_00141848");
extern int FUN_001f96f8_2e89b0(int) __asm__("FUN_001f96f8");

void FUN_L00_002e89b0(char *o, float *a, float *b) {
    S_2e89b0 *s = (S_2e89b0 *)(*(char **)(o + 0x70) + 0x1A8);
    G_2e89b0 *g;

    if (s->flags & 1) {
        *a = 0.0f;
    } else {
        *a = D_0013CA40_2e89b0[0];
        if (D_0015EDE0_2e89b0 == 0) {
            *a = -*a;
        }
    }
    if (*a == 0.0f) {
        D_L00_00161D8C_2e89b0 = 0;
        D_L00_00161D90_2e89b0 = 0;
        if (s->f1C != 0.0f) {
            *a = s->f1C;
        }
    } else {
        s->f14 = D_L00_0015EF44_2e89b0;
        g = &D_00141848_2e89b0;
        if (g->u40 < 3) {
            D_L00_00161D8C_2e89b0++;
            if (D_L00_00161D90_2e89b0 == 0 && FUN_001f96f8_2e89b0(0x3C) < D_L00_00161D8C_2e89b0) {
                if (g->u40 <= 0xFFFE) {
                    g->u40++;
                }
                if (FUN_001f96f8_2e89b0(D_0015EEA4_2e89b0) / 600 > g->u42) {
                    g->u42 = FUN_001f96f8_2e89b0(D_0015EEA4_2e89b0) / 600;
                }
                D_L00_00161D90_2e89b0 = 1;
                g->i44 = g->i44 | (1 << D_0015ED84_2e89b0) | 0x80000000;
            }
        }
    }
    if (s->flags & 2) {
        *b = 0.0f;
        *b = s->f24 / 0.6981317f;
    } else {
        float t = D_0013CA40_2e89b0[1];
        *b = -t;
        if (D_0015EDDC_2e89b0 == 0) {
            *b = t;
        }
        if (*b == 0.0f) {
            *b = s->f24 / 0.6981317f;
        }
    }
}
typedef float V_2e8bb8[4] __attribute__((aligned(16)));
extern float D_L00_00161CAC_2e8bb8 __asm__("D_L00_00161CAC") __attribute__((sda));
extern float D_L00_00161CB0_2e8bb8 __asm__("D_L00_00161CB0") __attribute__((sda));
extern float D_L00_00161CBC_2e8bb8 __asm__("D_L00_00161CBC") __attribute__((sda));
extern float D_L00_00161CC0_2e8bb8 __asm__("D_L00_00161CC0") __attribute__((sda));
extern float D_L00_00161CC4_2e8bb8 __asm__("D_L00_00161CC4") __attribute__((sda));
extern unsigned char D_L00_00166E10_2e8bb8[] __asm__("D_L00_00166E10") __attribute__((section(".data")));
extern float FUN_001ebd78_2e8bb8(void *, float, float, float, float, float) __asm__("FUN_001ebd78");
extern float FUN_001f99c0_2e8bb8(float) __asm__("FUN_001f99c0");
extern void FUN_00214890_2e8bb8(void *, void *, void *, float) __asm__("FUN_00214890");
extern float FUN_001f9ab0_2e8bb8(void *, void *) __asm__("FUN_001f9ab0");
extern float FUN_001f9af0_2e8bb8(void *) __asm__("FUN_001f9af0");
extern void FUN_001f9ad8_2e8bb8(void *, void *, void *) __asm__("FUN_001f9ad8");
extern void FUN_001f9bf8_2e8bb8(void *, void *, float) __asm__("FUN_001f9bf8");
extern float FUN_001f9e90_2e8bb8(float, float) __asm__("FUN_001f9e90");
extern float FUN_001fa580_2e8bb8(float, float) __asm__("FUN_001fa580");
extern float FUN_001fa5c8_2e8bb8(float, float) __asm__("FUN_001fa5c8");

void FUN_L00_002e8bb8(unsigned char *o, float k, float in) {
    V_2e8bb8 axis;
    unsigned char *e;
    unsigned char *base;
    unsigned char *s;
    unsigned char *c;
    float r;
    float lim;
    float sel;
    float a;
    float b;
    float ang;
    float z;

    e = *(unsigned char **)(o + 0x70);
    base = D_L00_00166E10_2e8bb8;
    s = e + 0x1A8;
    c = e + 0x130;
    r = FUN_001ebd78_2e8bb8(e + 0x1AC, *(float *)(e + 0x1A8), k, D_L00_00161CAC_2e8bb8, D_L00_00161CB0_2e8bb8, 0.0f);
    *(float *)(e + 0x1A8) = r;
    *(float *)(c + 0x34) = *(float *)(s + 0x14) * r;
    if (in < -0.3f) {
        in = (in + 0.3f) * 1.4285715f;
    } else if (0.3f < in) {
        in = (in - 0.3f) * 1.4285715f;
    } else {
        in = 0.0f;
    }
    z = 0.0f;
    if (in == z) {
        sel = D_L00_00161CC0_2e8bb8;
    } else if (!(FUN_001f99c0_2e8bb8(in) < FUN_001f99c0_2e8bb8(*(float *)(s + 8)))) {
        sel = D_L00_00161CBC_2e8bb8;
    } else if (z < in && z < *(float *)(s + 8)) {
        sel = D_L00_00161CC0_2e8bb8;
    } else if (in < z && *(float *)(s + 8) < z) {
        sel = D_L00_00161CC0_2e8bb8;
    } else {
        sel = D_L00_00161CBC_2e8bb8;
    }
    *(float *)(s + 8) = FUN_001ebd78_2e8bb8(s + 0xC, *(float *)(s + 8), in, D_L00_00161CAC_2e8bb8, D_L00_00161CB0_2e8bb8, sel);
    lim = *(float *)(s + 8) * 0.69813168f;
    if (k == 0.0f) {
        FUN_00214890_2e8bb8(c, c, base + 0x20, *(float *)(s + 0x20));
    } else {
        FUN_00214890_2e8bb8(c, c, base + 0x20, *(float *)(c + 0x34));
    }
    a = FUN_001f9ab0_2e8bb8(c, base + 0x20);
    b = FUN_001f9af0_2e8bb8(c);
    FUN_001f9ad8_2e8bb8(axis, base + 0x20, c);
    FUN_001f9bf8_2e8bb8(axis, axis, 1.0f);
    ang = FUN_001f9e90_2e8bb8(b, a);
    if (FUN_001f99c0_2e8bb8(ang) < FUN_001f99c0_2e8bb8(lim) && sel == D_L00_00161CC0_2e8bb8) {
        *(float *)(s + 8) = ang / 0.69813168f;
    }
    if (ang < lim) {
        if (lim < FUN_001fa580_2e8bb8(ang, D_L00_00161CC4_2e8bb8)) {
            *(float *)(c + 0x38) = FUN_001fa5c8_2e8bb8(lim, ang);
        } else {
            *(float *)(c + 0x38) = D_L00_00161CC4_2e8bb8;
        }
    } else if (lim < ang) {
        if (*(short *)(*(unsigned char **)(o + 0x70) + 0x208) < 0) {
            *(float *)(c + 0x38) = 0.0f;
        } else if (FUN_001fa580_2e8bb8(ang, -D_L00_00161CC4_2e8bb8) < lim) {
            *(float *)(c + 0x38) = FUN_001fa5c8_2e8bb8(lim, ang);
        } else {
            *(float *)(c + 0x38) = -D_L00_00161CC4_2e8bb8;
        }
    } else {
        *(float *)(c + 0x38) = 0.0f;
    }
    if (lim < 0.0f) {
        *(short *)(*(unsigned char **)(o + 0x70) + 0x22) = 1;
    }
    FUN_00214890_2e8bb8(c, c, axis, *(float *)(c + 0x38));
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002E1660.c: func_L00_002EA3F0), where it is exact; names translated to the US level program. */

extern float D_L00_0015EF40;
extern float FUN_001f9af0(void *);
extern void FUN_001f9a28(float *, float *, float *);
extern void FUN_001f9a40(float, void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);

void FUN_L00_002e8f40(int m) {
    char *p = *(char **)(m + 0x70);
    char *r = p + 0x1D0;
    char *q = p + 0x130;
    if (*(short *)(p + 0x10) > 0) {
        float v[4];
        float f;
        float lim;
        FUN_001f9a28(v, (float *)p, (float *)(p + 0x90));
        FUN_001f9a40(D_L00_0015EF40, q, q, v);
        f = FUN_001f9af0(q);
        lim = *(float *)(q + 0x2C);
        if (lim < f) {
            f = lim;
            FUN_001f9bf8(q, q, f);
            *(float *)(r + 0x30) = *(float *)(q + 0x2C) - f;
        } else {
            float t = lim - *(float *)(r + 0x30);
            if (f < t) {
                f = t;
                FUN_001f9bf8(q, q, f);
            }
            *(float *)(r + 0x30) = *(float *)(q + 0x2C) - f;
        }
    }
}
