/* Level overlay code after ui/text; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

struct G { char pad[0x10B8]; int mode; char pad2[0x20A4 - 0x10BC]; unsigned char flag; };
extern struct G D_0013F350;
extern unsigned char D_0013E529[];
void FUN_L00_00235ea0(char *);
int FUN_001f96f8(int);
void FUN_L00_002377b8(char *p) {
    FUN_L00_00235ea0(p);
    if (D_0013E529[0] != 0) *(int *)(p + 8) = 10; else *(int *)(p + 8) = 5;
    if (D_0013F350.mode == 9 && D_0013F350.flag == 0) {
        *(int *)(p + 0x7C) = FUN_001f96f8(0x78) + 30;
    } else if (*(int *)(p + 0x7C) > 30) {
        *(int *)(p + 0x7C) = 30;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00237840.s", FUN_L00_00237840);
typedef struct { u8 pad[0x48]; s16 x48; s16 x4a; u8 p4c[0xC]; s32 x58; s32 x5c; u8 p60[0x10]; s32 x70; s32 x74; s32 x78; } O00237ae8;
typedef struct { s32 x0; u8 p[0x14]; s32 x18; } D00237ae8;
typedef struct { u8 p[0x38]; u16 x38; u8 p2[0x12]; } E00237ae8;
extern s32 D_L00_0015FA90;
extern void *D_L00_0015FAC0;
extern s32 D_L00_0015F738 __attribute__((sda));
extern s32 D_L00_0015F718 __attribute__((sda));
extern s32 D_L00_0015F71C __attribute__((sda));
extern s32 D_L00_0015F72C __attribute__((sda));
extern D00237ae8 D_L00_0017DAC0[];
extern E00237ae8 D_L00_00179AC0[];
extern s32 D_00141EA0[];
s32 FUN_001f96f8(s32);
void FUN_L00_00237ae8(O00237ae8 *o) {
    s32 i;
    D00237ae8 *d;
    s32 *s;
    E00237ae8 *tab;
    D_L00_0015FA90 = 8;
    D_L00_0015FAC0 = &D_L00_0015F738;
    o->x48 = 0;
    o->x4a = 0;
    o->x58 = D_L00_0015F718; o->x5c = D_L00_0015F71C; o->x74 = -2;
    o->x78 = FUN_001f96f8(0x1E);
    o->x70 = 0;
    D_L00_0015F72C = 0;
    d = D_L00_0017DAC0;
    tab = D_L00_00179AC0;
    s = D_00141EA0;
    for (i = 7; i >= 0; i--) {
        d->x18 = *s;
        d->x0 = tab[*s].x38;
        s++;
        d++;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00237ba0.s", FUN_L00_00237ba0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002382a0.s", FUN_L00_002382a0);
extern int D_L00_0015FA90 __attribute__((section(".sdata")));
extern void *D_L00_0015FAC0 __attribute__((section(".sdata")));
extern int D_L00_0015F718 __attribute__((sda));
extern int D_L00_0015F71C __attribute__((sda));
extern int D_L00_0015F72C __attribute__((sda));
extern int D_L00_0015F740 __attribute__((sda));
int FUN_001f96f8(int);
void FUN_L00_00238b18(char *p) {
 int a, b; D_L00_0015FA90 = 4; D_L00_0015FAC0 = &D_L00_0015F740; a = D_L00_0015F718; b = D_L00_0015F71C; *(short *)(p + 0x48) = 0; *(short *)(p + 0x4A) = 0; *(int *)(p + 0x58) = a; *(int *)(p + 0x5C) = b; *(int *)(p + 0x74) = -2; *(int *)(p + 0x78) = FUN_001f96f8(30); D_L00_0015F72C = 0; }
typedef struct { int f0, f4, f8, fC, f10, f14, f18; } Ent;
typedef struct {
    u8 p0[0x64]; int w64; u8 p68[4]; int w6C; u8 b70; u8 b71; u8 p72[2]; int w74; int w78; int w7C;
} Obj;
typedef struct { u8 p0[0x148]; float f148; float f14C; u8 p150[0x70]; int w1C0; int w1C4; u8 p1C8[4]; int w1CC; } G_t;
extern G_t D_0013C940;
extern int D_L00_0017E504 __attribute__((section(".data")));
extern int D_L00_0015FA90_c __asm__("D_L00_0015FA90") __attribute__((sda));
extern int D_L00_0015F780 __attribute__((sda));
extern int D_L00_0015FA9C __attribute__((sda));
extern Ent **D_L00_0015FAC0_c __asm__("D_L00_0015FAC0");
extern int D_L00_0017DC38 __attribute__((section(".data")));
extern int D_L00_0017DC3C __attribute__((section(".data")));
extern int D_L00_0017DC40 __attribute__((section(".data")));
extern int D_L00_0017DC44 __attribute__((section(".data")));
extern int D_00141610[];
extern int D_L00_0015FA98;
extern int D_L00_0015FA94;
extern int D_L00_0015F3F8 __attribute__((section(".sdata")));
extern int FUN_001f96f8(int);
extern float FUN_001f9988(float);
extern float FUN_001f9e90(float, float);
extern int FUN_001ff480(int);

void FUN_L00_00238b80(Obj *o) {
    float x, y, len, ang;
    int old, cur, n, t;
    u8 *c = &o->b70;

    o->w7C = FUN_001f96f8(0xB4);
    o->w6C = 0x18;
    D_0013C940.w1CC = 2;
    x = D_0013C940.f148;
    y = D_0013C940.f14C;
    len = FUN_001f9988(x * x + y * y);
    if (len != 0.0f) {
        x /= len;
        y /= len;
    }
    ang = FUN_001f9e90(x, y);
    if ((o->w78 >> 24) == 0 && D_L00_0017E504 != 0) {
        if ((D_0013C940.w1C4 & 0xF000) || len < 0.5f || --o->w78 == -1) {
            o->w74 = -1;
            o->w78 = 0x10000FF;
        }
    }
    old = o->w74;
    if (*((s8 *)o + 0x7B) == 1) {
        if (0.9f < len) {
            n = D_L00_0015FA90_c;
            o->w74 = (int)((ang + 3.1415927f + 3.1415927f + 1.5707964f + 3.1415927f / (float)n) * ((float)n / 6.2831855f)) % n;
        }
        if (D_0013C940.w1C4 & 0xF000) {
            cur = o->w74;
            if (D_0013C940.w1C4 & 0x1000) {
                if (cur == -1) t = D_L00_0017DC40; else t = D_L00_0015FAC0_c[D_L00_0015F72C][cur].f10;
                cur = t;
            }
            if (D_0013C940.w1C4 & 0x4000) {
                if (cur == -1) t = D_L00_0017DC44; else t = D_L00_0015FAC0_c[D_L00_0015F72C][cur].f14;
                cur = t;
            }
            if (D_0013C940.w1C4 & 0x8000) {
                if (cur == -1) t = D_L00_0017DC38; else t = D_L00_0015FAC0_c[D_L00_0015F72C][cur].f8;
                cur = t;
            }
            if (D_0013C940.w1C4 & 0x2000) {
                if (cur == -1) t = D_L00_0017DC3C; else t = D_L00_0015FAC0_c[D_L00_0015F72C][cur].fC;
                cur = t;
            }
            o->w74 = cur;
        }
    }
    if (o->w74 != old) {
        c[1] = 0;
    } else if (c[1] < D_L00_0015F780) {
        c[1]++;
    }
    if (!(D_0013C940.w1C0 & 0x10)) {
        if (o->w74 == -1) D_00141610[0] = 0;
        else D_00141610[0] = D_L00_0015FAC0_c[D_L00_0015F72C][o->w74].f18;
        if (c[0] != 0) c[0]--;
    } else if (c[0] < D_L00_0015F780) {
        c[0]++;
    }
    if (c[0] == 0) {
        { int a = o->w78; int b = o->w74; D_L00_0015FA9C = b; D_L00_0015FA98 = a; }
        FUN_001ff480(o->w64);
        o->w6C = -6;
        D_L00_0015FA94 = D_L00_0015F3F8;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00238f88.s", FUN_L00_00238f88);
typedef struct { short a, b, c, d; } Q2395b0;
extern Q2395b0 D_L00_0015FAB0;
int FUN_001f96f8(int);
void FUN_L00_00235c80();
void FUN_L00_002395b0(char *p) {
    int r = FUN_001f96f8(0xB4);
    *(int *)(p + 0x7C) = r + 30;
    *(int *)(p + 0x58) = 64;
    *(int *)(p + 0x5C) = 64;
    *(short *)(p + 0x48) = 32;
    *(short *)(p + 0x4A) = 0;
    FUN_L00_00235c80(p);
    *(Q2395b0 **)(p + 0x80) = &D_L00_0015FAB0;
    D_L00_0015FAB0.d = 1;
    D_L00_0015FAB0.a = 0;
    D_L00_0015FAB0.b = 0;
    D_L00_0015FAB0.c = 0;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00239630.s", FUN_L00_00239630);
typedef struct { s16 x; s16 y; } Pt;
typedef struct {
    u8 pad0[0x50]; s32 x; u8 pad54[4]; s32 ret; u8 pad5c[0x14];
    u8 ab[2]; u8 pad72[6]; s32 cnt; u8 pad7c[4]; s16 *p;
} Hud;
typedef struct { u8 p0[0x2084]; s32 w2084; u8 p2088[0x20A4 - 0x2088]; u8 b20A4; u8 p20A5[0x22AC - 0x20A5]; s32 w22AC; } GS;
extern GS D_0013F350_c __asm__("D_0013F350");

extern f32 FUN_001fa6c0(s32);
extern s32 FUN_001fa6d0(f32);
extern s32 FUN_001ff960_c(s32, s32) __asm__("FUN_001ff960");
extern void FUN_001ffe18(s32, s32, s32, s32, s32, s32);
extern void FUN_001ffc30_c(s32, s32, s32, s32, s32, s32) __asm__("FUN_001ffc30");
extern void FUN_L00_0023b120_c(Hud *, s32, s32, s32, s32, s32) __asm__("FUN_L00_0023b120");
extern s32 D_0015ED80_c __asm__("D_0015ED80") __attribute__((sda));
extern s32 D_0015EDA0;
extern s32 D_L00_0015F808 __attribute__((sda));
extern s32 D_L00_0015F7F0 __attribute__((sda));
extern s32 D_L00_0015F820 __attribute__((sda));
extern s32 D_L00_0015F810 __attribute__((sda));
extern s32 D_L00_0015F80C __attribute__((sda));
extern s32 D_L00_0015F81C __attribute__((sda));
extern s32 D_L00_0015F7F8[1] __attribute__((sda));
extern Pt D_L00_0017E478[];
extern Pt D_L00_0017E460[];

s32 FUN_L00_00239810(Hud *m)
{
    s32 x;
    s32 y;
    s32 cnt;
    f32 f21;
    f32 f22;
    s32 alpha;
    s32 w;
    s16 *p;
    s32 sel;
    Pt *tab;
    s32 mode;
    s32 a;
    s32 b;
    s32 x0;
    s32 yy;
    s32 h1;
    s32 h2;
    s32 i;
    s32 r;
    Pt *e;
    u8 *q;

    if (D_0013F350_c.b20A4 == 2) goto out;
    if (D_0013F350_c.w2084 == 0x32) goto out;
    x = m->x;
    if (D_0015ED80_c != 0) y = D_L00_0015F808 + 10;
    else y = D_L00_0015F808 + 0x12;
    cnt = m->cnt;
    q = m->ab;
    if (q[0] == 0) goto out;
    f21 = FUN_001fa6c0(q[0]) / FUN_001fa6c0(D_L00_0015F7F0);
    if (1.0f < f21) f21 = 1.0f;
    else if (f21 < 0.0f) f21 = 0.0f;
    f22 = FUN_001fa6c0(q[1]) / FUN_001fa6c0(D_L00_0015F7F0);
    if (1.0f < f22) f22 = 1.0f;
    else if (f22 < 0.0f) f22 = 0.0f;
    alpha = FUN_001fa6d0(f22 * 128.0f);
    w = FUN_001fa6d0((f32)D_L00_0015F820 * f21);
    p = m->p;
    sel = p[0] >> 1;
    mode = D_0015EDA0;
    if (cnt == 0) sel = 0x1E;
    if (D_0013F350_c.b20A4 == 1) mode = D_0013F350_c.w22AC;
    if (mode == 8) {
        tab = D_L00_0017E478;
        a = FUN_001fa6d0(f21 * 48.0f);
        b = FUN_001fa6d0(f21 * 48.0f);
    } else if (mode == 5) {
        tab = D_L00_0017E460;
        a = FUN_001fa6d0(f21 * 32.0f);
        b = FUN_001fa6d0(f21 * 16.0f);
    } else {
        b = 0;
        tab = (Pt *)D_L00_0015F7F8;
        a = FUN_001fa6d0(f21 * 48.0f);
    }
    yy = y + D_L00_0015F810;
    h1 = FUN_001ff960_c(0x7580, 1);
    h2 = FUN_001ff960_c(0x7580, 0);
    FUN_001ffe18(h1, x + a, yy, D_L00_0015F81C, D_L00_0015F81C, w);
    FUN_001ffc30_c(h2, x - a, yy, a * 2, D_L00_0015F81C, w);
    FUN_001ffc30_c(h1, x - a - D_L00_0015F81C, yy, D_L00_0015F81C, D_L00_0015F81C, w);
    if (b != 0) {
        yy += D_L00_0015F80C;
        FUN_001ffe18(h1, x + b, yy, D_L00_0015F81C, D_L00_0015F81C, w);
        x0 = x - b;
        FUN_001ffc30_c(h2, x0, yy, b * 2, D_L00_0015F81C, w);
        FUN_001ffc30_c(h1, x0 - D_L00_0015F81C, yy, D_L00_0015F81C, D_L00_0015F81C, w);
    }
    for (i = 0; i < mode; i++) {
        r = FUN_001ff960_c(0x7536, sel);
        FUN_L00_0023b120_c(m, r, x + tab[i].x, y + tab[i].y, 1, alpha);
        if (sel != 0x1E) {
            r = FUN_001ff960_c(0x7536, 0x1E);
            FUN_L00_0023b120_c(m, r, x + tab[i].x, y + tab[i].y, 1, alpha);
            r = FUN_001ff960_c(0x7536, 0x1F);
            FUN_001ffc30_c(r, x + tab[i].x + 0xE, y + tab[i].y - 0x11, 0x22, 0x22, FUN_001fa6d0((f32)(p[1] >> 4) * f22));
            if (cnt == i + 1) sel = 0x1E;
            else sel = (sel + 6) % 30;
        }
    }
out:
    return m->ret;
}
#define NOT_SDA

#define MACRO_ADDR

/* Sets E up with func_L00_0023B0F8, points +0x80 at the shorts of
   D_L00_0015FB70 (declared like D_L00_0015FB68, out of $gp's reach) and
   clears the first. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/hud_00235960.c: func_L00_0023A658), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x8];
    int unk08;
    int *unk0C;
    char pad10[0x38];
    short unk48;
    short unk4A;
    char pad4C[0x4];
    int unk50;
    int unk54;
    int w;
    int h;
    int flags;
    char pad64[0x8];
    int unk6C;
    unsigned char cnt[4];
    int unk74;
    int unk78;
    int unk7C;
    void *unk80;
} HudElem;

typedef struct {
    short unk0;
    short unk2;
    short unk4;
    short unk6;
} HudCounter;

extern HudCounter D_L00_0015FAB8;
extern void FUN_L00_0023a760(HudElem *);

void FUN_L00_00239cc8(HudElem *e) {
    FUN_L00_0023a760(e);
    e->unk80 = &D_L00_0015FAB8;
    D_L00_0015FAB8.unk0 = 0;
}
typedef struct T00239d00 {
    u8 pad[0x6c];
    s32 state;
    u8 a;
    u8 b;
    u8 pad72[2];
    s32 frame;
    s32 pad78;
    s32 thr;
    s16 *ctr;
} T00239d00;
extern s32 D_0015ED98;
extern s32 D_L00_0015F824 __attribute__((sda));
extern s32 D_L00_0015F828 __attribute__((sda));
extern s32 FUN_001f96f8_c(s32) __asm__("FUN_001f96f8");
void FUN_L00_00239d00(T00239d00 *o)
{
    u8 *p = &o->a;
    s32 n = 60;
    s32 f;
    f = D_0015ED98;
    *(volatile s16 *)o->ctr = (*o->ctr + 1) % n;
    if (o->frame != f) {
        o->frame = f;
        o->thr = FUN_001f96f8_c(90);
    }
    if (FUN_001f96f8_c(5) <= o->thr) {
        if (o->a < D_L00_0015F824) {
            o->a++;
        } else if (p[1] < D_L00_0015F828) {
            p[1]++;
        }
    } else {
        o->state = 1;
        if (p[1] != 0) {
            p[1]--;
        } else if (o->a != 0) {
            o->a--;
        } else {
            o->state = -6;
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00239df8.s", FUN_L00_00239df8);
#include "sda.h"
extern s32 D_00141398 NOT_SDA;
extern s32 D_L00_0015F7F0 __attribute__((sda));
s32 FUN_001f96f8(s32);
void FUN_L00_0023a218(u8 *m) {
    u8 *q = m + 0x70;
    if (D_00141398) {
        s32 r = FUN_001f96f8(10);
        s32 lim = D_L00_0015F7F0;
        *(s32 *)(m + 0x7C) = r;
        if (m[0x70] < lim) {
            m[0x70]++;
        } else if (q[1] < lim) {
            q[1]++;
        }
    } else {
        *(s32 *)(m + 0x7C) = 0;
        *(s32 *)(m + 0x6C) = 1;
        if (q[1]) {
            q[1]--;
        } else if (m[0x70]) {
            m[0x70]--;
        } else {
            *(s32 *)(m + 0x6C) = -6;
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0023a2d0.s", FUN_L00_0023a2d0);
extern short D_00140986 __attribute__((section(".data")));
int FUN_L00_00235a70(char *, int *, int *);
void FUN_L00_00235ad8(char *, int *, int *, int, int);
int FUN_001ff960(int, int);
void FUN_L00_0023b6c0(int, int, int, int, int, int);
void FUN_001ffc30(int, int, int, int, int, int);
int FUN_L00_0023a640(char *rec) {
    int x, y;
    int n;
    x = *(int *)(rec + 0x50);
    y = *(int *)(rec + 0x54);
    *(int *)(rec + 0x58) = 0x100;
    *(int *)(rec + 0x5C) = 0x40;
    FUN_L00_00235a70(rec, &x, &y);
    FUN_L00_00235ad8(rec, &x, &y, *(int *)(rec + 0x6C), 0);
    n = *(int *)(rec + 0x74) * 0xDD / *(int *)(rec + 0x8) + 0x1B;
    FUN_L00_0023b6c0(FUN_001ff960(0x7558, 1), x, y, n, 0x40, 0x80);
    FUN_001ffc30(FUN_001ff960(0x7558, 0), x, y, 0x100, 0x40, 0x80);
    FUN_001ffc30(FUN_001ff960(0x7558, 2), x, y, 0x20, 0x20, D_00140986 ? 0x80 : 0);
    return *(int *)(rec + 0x58);
}
/* func_L00_00236750 without the offsets: a 32 x 32 element with a timer
   of 30 + func_001F9850(120). */
/* Ported from rac1-decomp (PAL, src/overlays/shared/hud_00235960.c: func_L00_0023B0F8), where it is exact; names translated to the US level program. */

extern int FUN_001f96f8(int);
extern void FUN_L00_00235c80(HudElem *);

void FUN_L00_0023a760(HudElem *e) {
    e->unk7C = FUN_001f96f8(0x78) + 0x1E;
    e->w = 0x20;
    e->h = 0x20;
    FUN_L00_00235c80(e);
}
