/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

/* per-frame level ambience (wind/sway) state machine: picks a random target, then eases toward it */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002A5B20), where it is exact; names translated to the US level program. */

struct Amb {
    float f0;
    float f4;
    float f8;
    short hC;
    short hE;
    float f10;
    float f14;
    float f18;
    short h1C;
    short h1E;
};

extern f32 ConvertIntegerToFloat(s32) __asm__("func_001FA6C0");
extern float D_0015ED6C;
extern float FUN_001fa580(float, float);
extern float FUN_001fa5c8(float, float);
extern float FUN_001f96b0(float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001f9770(void *);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern struct Amb D_L00_001CB7C0;
float AbsoluteFloat(float input) __asm__("func_001F99C0");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L00_002a4890(void) {
    struct Amb *s = &D_L00_001CB7C0;
    float a, b, c, d, e;
    switch (s->hC) {
    case 1:
        break;
    case 2:
        switch (s->hE) {
        case 0:
            if (FUN_001f9770(&s->h1E)) {
                a = ConvertIntegerToFloat(s->h1C) * random_float_between_alt(0.5f, 1.5f);
                c = FUN_001fa580(s->f0, random_float_between_alt(-1.0471976f, 1.0471976f));
                b = random_float_between_alt(s->f10 * 0.5f, s->f10 * 1.5f);
                s->f8 = FUN_001fa5c8(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 1;
            }
            break;
        case 1:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(ConvertIntegerToFloat(s->h1C) * random_float_between_alt(2.0f, 3.0f));
                s->hE = 0;
            } else {
                s->f4 = FUN_001fa580(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = AbsoluteFloat(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f) e = -e;
                    s->f14 = e;
                }
            }
            break;
        }
        break;
    case 3:
        switch (s->hE) {
        case 0:
            if (FUN_001f9770(&s->h1E)) {
                a = FUN_001f96b0(random_float_between_alt(45.0f, 60.0f));
                c = FUN_001fa580(s->f0, random_float_between_alt(-1.5707964f, 1.5707964f));
                b = random_float_between_alt(s->f10 * 1.5f, s->f10 + s->f10);
                s->f8 = FUN_001fa5c8(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 1;
            }
            break;
        case 1:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(ConvertIntegerToFloat(s->h1C) * random_float_between_alt(1.0f, 1.5f));
                s->hE = 2;
            } else {
                s->f4 = FUN_001fa580(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = AbsoluteFloat(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f) e = -e;
                    s->f14 = e;
                }
            }
            break;
        case 2:
            if (FUN_001f9770(&s->h1E)) {
                a = FUN_001f96b0(random_float_between_alt(45.0f, 60.0f));
                c = FUN_001fa580(s->f0, random_float_between_alt(-0.785398f, 0.785398f));
                b = random_float_between_alt(s->f10 * 0.8f, s->f10 * 1.2f);
                s->f8 = FUN_001fa5c8(c, s->f4) / a;
                s->f18 = (b - s->f14) / a;
                s->h1E = func_001FA898_r(a);
                s->hE = 3;
            }
            break;
        case 3:
            if (FUN_001f9770(&s->h1E)) {
                s->h1E = func_001FA898_r(ConvertIntegerToFloat(s->h1C) * random_float_between_alt(3.0f, 5.0f));
                s->hE = 0;
            } else {
                s->f4 = FUN_001fa580(s->f4, s->f8);
                s->f14 = s->f14 + s->f18;
                d = AbsoluteFloat(s->f14);
                e = D_0015ED6C * 9.6f;
                if (e < d) {
                    if (s->f14 < 0.0f) e = -e;
                    s->f14 = e;
                }
            }
            break;
        }
        break;
    }
}
extern int D_L00_00161390;
#define SDA __attribute__((sda))
extern int D_L00_00161368 SDA, D_L00_0016136C SDA, D_L00_00161370 SDA;
extern int D_L00_0016137C SDA, D_L00_00161380 SDA, D_L00_00161388;
extern float D_L00_00161374 SDA, D_L00_00161378 SDA, D_L00_00161384 SDA, D_L00_0016138C SDA;
extern float D_0015ED60;
int FUN_001f96f8(int);
float FUN_001fa6c0(int);
void FUN_L00_002a4cd8(unsigned char *p) {
    float one;
    int r;
    switch (p[0x20]) {
    case 0:
        D_L00_00161390 = 0;
        p[0x20] = 1;
        p[0x30] = 0xFF;
        one = 1.0f;
        D_L00_0016137C = FUN_001f96f8(D_L00_00161368);
        r = FUN_001f96f8(D_L00_0016136C);
        D_L00_00161380 = r;
        D_L00_00161384 = one / FUN_001fa6c0(r);
        r = FUN_001f96f8(D_L00_00161370);
        D_L00_00161388 = r;
        D_L00_0016138C = one / (float)r;
        break;
    case 1:
        D_L00_00161374 -= D_L00_00161378 * D_0015ED60;
        if (D_L00_00161374 <= -8.0f) D_L00_00161374 += 8.0f;
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a4dc8.s", FUN_L00_002a4dc8);
#include "eetypes.h"
#include "qcopy.h"
unsigned char *FUN_0020c4f8(int);
void FUN_L00_00250df8(unsigned char *);
unsigned char *FUN_L00_002a4de0(u128 *v) { unsigned char *m = FUN_0020c4f8(0x3ef); if (m) { m[0x30] = 0xff; *(unsigned short *)(m + 0x34) |= 0x41; qcopy(m + 0x10, v); FUN_L00_00250df8(m); } return m; }
typedef int ti_2a4e48 __attribute__((mode(TI)));
typedef struct {
    char p0[0x98];
    float f98;
    char p1[0x164 - 0x9C];
    float f164;
    char p2[0x2080 - 0x168];
    char *obj;
    char p3[0x208C - 0x2084];
    int w208C;
} G_2a4e48;
typedef struct {
    char p0[0x158];
    float f158;
    char p1[0x180 - 0x15C];
    char *c;
} C_2a4e48;
extern C_2a4e48 D_166C80_2a4e48 __asm__("D_L00_00166C80") __attribute__((section(".data")));
extern char D_0013F3D0_2a4e48[] __asm__("D_0013F3D0");
extern float D_0015ED6C_2a4e48 __asm__("D_0015ED6C") __attribute__((section(".sdata")));
extern void f9a28_2a4e48(void *, void *, void *) __asm__("FUN_001f9a28");
extern float f9ab0_2a4e48(void *, void *) __asm__("FUN_001f9ab0");
extern void f9a68_2a4e48(void *, void *, float) __asm__("FUN_001f9a68");
extern float f99c0_2a4e48(float) __asm__("FUN_001f99c0");
extern float f9af0_2a4e48(void *) __asm__("FUN_001f9af0");
extern float fa688_2a4e48(float, float) __asm__("FUN_001fa688");
extern void f9a10_2a4e48(void *, void *, void *) __asm__("FUN_001f9a10");

void FUN_L00_002a4e48(char *o) {
    ti_2a4e48 d[1];
    ti_2a4e48 e[1];
    C_2a4e48 *C = &D_166C80_2a4e48;
    char *s;
    char *pos;
    G_2a4e48 *P;
    float f;

    if (C->c != 0) {
        s = o + 0x10;
        qcopy(s, C->c + 0x30);
        pos = D_0013F3D0_2a4e48;
        f9a28_2a4e48(d, s, pos);
        P = (G_2a4e48 *)(pos - 0x80);
        f = f9ab0_2a4e48(d, P->obj + 0xE0);
        f9a68_2a4e48(e, P->obj + 0xE0, f);
        f9a28_2a4e48(d, d, e);
        if (f99c0_2a4e48(f) < 2.5f) {
            f = 0.1f;
            if (f9af0_2a4e48(d) < f
                || fa688_2a4e48(P->f98, C->f158) < 2.3561945f
                || P->f164 < D_0015ED6C_2a4e48 * f) {
                *(float *)(o + 0x18) = 15.0f;
                *(float *)(o + 0x14) = 15.0f;
                *(float *)(o + 0x10) = 15.0f;
            } else {
                f = f9ab0_2a4e48(s, P->obj + 0xE0);
                f9a68_2a4e48(e, P->obj + 0xE0, f);
                f9a28_2a4e48(d, s, e);
                f = f9ab0_2a4e48(pos, P->obj + 0xE0);
                if (P->w208C != 0x11) {
                    f9a68_2a4e48(e, P->obj + 0xE0, f);
                    f9a10_2a4e48(s, d, e);
                }
            }
        }
    } else {
        *(float *)(o + 0x18) = 5.0f;
        *(float *)(o + 0x14) = 5.0f;
        *(float *)(o + 0x10) = 5.0f;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a5040.s", FUN_L00_002a5040);
typedef struct { f32 f[4]; } V_2a57a8;
typedef struct { u8 p0[0x24]; f32 f24; } N_2a57a8;
typedef struct { u8 p0[0x10]; f32 f10, f14, f18; u8 p1C[0x24 - 0x1C]; N_2a57a8 *p24; u8 p28[4]; f32 f2C; u8 p30[2]; u16 h32; u16 h34; u8 p36[0x73 - 0x36]; u8 b73; } M_2a57a8;
typedef struct { s32 i0, i4; u8 p8[4]; M_2a57a8 *mC; u8 p10[0x90 - 0x10]; f32 f90; } Q_2a57a8;
typedef struct { u8 p0[0x10]; f32 f10, f14, f18; u8 p1C[4]; u8 b20; u8 p21[0x52 - 0x21]; u8 b52, b53; u8 p54[0x78 - 0x54]; Q_2a57a8 *q; u8 p7C[0x90 - 0x7C]; s32 i90; } P_2a57a8;
typedef struct { u8 p0[0x80]; f32 f80, f84; u8 p88[0x98 - 0x88]; f32 f98; u8 p9C[0x2084 - 0x9C]; s32 i2084; u8 p2088[4]; s32 i208C; u8 p2090[0x20A4 - 0x2090]; u8 b20A4; } G_2a57a8;
extern G_2a57a8 G_2a57a8_ __asm__("D_0013F350") __attribute__((section(".data")));
extern V_2a57a8 D_0013F3D0_2a57a8 __asm__("D_0013F3D0") __attribute__((section(".data")));
extern s32 D_0013CAE4_2a57a8 __asm__("D_0013CAE4") __attribute__((section(".data")));
extern s32 D_L00_0015F5CC_2a57a8 __asm__("D_L00_0015F5CC");
extern f32 D_L00_001613A4_2a57a8 __asm__("D_L00_001613A4") __attribute__((sda));
extern f32 D_L00_0016139C_2a57a8 __asm__("D_L00_0016139C") __attribute__((sda));
extern f32 D_L00_001613A0_2a57a8 __asm__("D_L00_001613A0") __attribute__((sda));
f32 FUN_001f9de0_2a57a8(f32) __asm__("FUN_001f9de0");
M_2a57a8 *FUN_0020c4f8_2a57a8(s32) __asm__("FUN_0020c4f8");
void FUN_0020cb10_2a57a8(M_2a57a8 *, s32, void *) __asm__("FUN_0020cb10");
f32 FUN_001f9b80_2a57a8(void *, void *) __asm__("FUN_001f9b80");
f32 FUN_001f99c0_2a57a8(f32) __asm__("FUN_001f99c0");
void FUN_00212f90_2a57a8(P_2a57a8 *, s32, s32, s32) __asm__("FUN_00212f90");
void FUN_L00_002a5040_2a57a8(void) __asm__("FUN_L00_002a5040");
void FUN_001f4600_2a57a8(void *, P_2a57a8 *) __asm__("FUN_001f4600");
void FUN_L00_001fff28_2a57a8(void *, s32, f32) __asm__("FUN_L00_001fff28");
f32 FUN_001fa580_2a57a8(f32, f32) __asm__("FUN_001fa580");
void FUN_L00_00250df8_2a57a8(M_2a57a8 *) __asm__("FUN_L00_00250df8");
f32 FUN_001f9e90_2a57a8(f32, f32) __asm__("FUN_001f9e90");
f32 FUN_001fa688_2a57a8(f32, f32) __asm__("FUN_001fa688");
s32 FUN_00215130_2a57a8(s32, s32) __asm__("FUN_00215130");
void FUN_L00_0029a6b0_2a57a8(P_2a57a8 *) __asm__("FUN_L00_0029a6b0");

void FUN_L00_002a57a8(P_2a57a8 *p) {
    Q_2a57a8 *q = p->q;
    s32 i, a, b, c;
    u8 *v;
    f32 d, z;

    D_L00_001613A4_2a57a8 += 0.05f;
    if (D_L00_001613A4_2a57a8 > 3.14f) D_L00_001613A4_2a57a8 = -3.14f;
    p->i90 = (((s32)(FUN_001f9de0_2a57a8(D_L00_001613A4_2a57a8) * 48.0f) + 0x60) * 0x10101) | 0x80000000;
    switch (p->b20) {
    case 0:
        p->b20 = 1;
        q->i0 = 0;
        q->i4 = 0;
        q->mC = FUN_0020c4f8_2a57a8(0x477);
        q->mC->h34 |= 2;
        q->mC->h32 = 0x40;
        q->mC->f10 = p->f10;
        q->mC->f14 = p->f14;
        q->mC->f18 = p->f18 + 2.95f;
        q->mC->b73 = 0x20;
        q->f90 = 0.0f;
        for (i = 0; i < 2; i++) {
            FUN_0020cb10_2a57a8(q->mC, i, (u8 *)q + 0x10 + i * 0x40);
        }
        FUN_L00_00250df8_2a57a8(q->mC);
        break;
    case 1:
        if (q->f90 > 0.0f) q->f90 -= 0.1f;
        if (q->f90 <= 0.0f) q->mC->h34 |= 1;
        if (!(D_L00_0015F5CC_2a57a8 & 7)
            && FUN_001f9b80_2a57a8(&p->f10, &D_0013F3D0_2a57a8) <= 16.0f
            && FUN_001f99c0_2a57a8(p->f18 - D_0013F3D0_2a57a8.f[2]) <= 8.0f) {
            p->b20 = 2;
            if (p->b53 != 1) FUN_00212f90_2a57a8(p, 1, 0, 10);
            q->mC->h34 &= 0xFFFE;
        }
        FUN_001f4600_2a57a8(FUN_L00_002a5040_2a57a8, p);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x20, 2, D_L00_0016139C_2a57a8);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x60, 2, D_L00_001613A0_2a57a8);
        D_L00_0016139C_2a57a8 = FUN_001fa580_2a57a8(D_L00_0016139C_2a57a8, 0.01f);
        D_L00_001613A0_2a57a8 = FUN_001fa580_2a57a8(D_L00_001613A0_2a57a8, -0.02f);
        q->mC->f2C = q->f90 * q->mC->p24->f24 * 2.5f;
        FUN_L00_00250df8_2a57a8(q->mC);
        break;
    case 2:
        if (q->f90 < 1.0f) q->f90 += 0.1f;
        d = FUN_001f9b80_2a57a8(&p->f10, &D_0013F3D0_2a57a8);
        z = FUN_001f99c0_2a57a8(p->f18 - D_0013F3D0_2a57a8.f[2]);
        if (!(D_L00_0015F5CC_2a57a8 & 7) && (d > 18.0f || z > 10.0f)) {
            p->b20 = 1;
            if (p->b53) FUN_00212f90_2a57a8(p, 0, 0, 10);
            break;
        }
        FUN_001f4600_2a57a8(FUN_L00_002a5040_2a57a8, p);
        a = 1;
        b = 1;
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x20, 2, D_L00_0016139C_2a57a8);
        FUN_L00_001fff28_2a57a8((u8 *)q + 0x60, 2, D_L00_001613A0_2a57a8);
        D_L00_0016139C_2a57a8 = FUN_001fa580_2a57a8(D_L00_0016139C_2a57a8, 0.01f);
        D_L00_001613A0_2a57a8 = FUN_001fa580_2a57a8(D_L00_001613A0_2a57a8, -0.02f);
        q->mC->f2C = q->f90 * q->mC->p24->f24 * 2.5f;
        FUN_L00_00250df8_2a57a8(q->mC);
        if (G_2a57a8_.i208C != 0 && G_2a57a8_.i2084 != 3 && G_2a57a8_.i208C != 1) { a = 0; b = 0; }
        if (G_2a57a8_.i2084 == 0x1D || G_2a57a8_.i2084 == 0x32) { a = 0; b = 0; }
        if (G_2a57a8_.b20A4) { a = 0; b = 0; }
        if (p->b52 != 1) a = 0;
        if (d > 4.0f || z > 2.0f) { a = 0; b = 0; }
        if (FUN_001fa688_2a57a8(G_2a57a8_.f98, FUN_001f9e90_2a57a8(p->f10 - G_2a57a8_.f80, p->f14 - G_2a57a8_.f84)) > 1.5707964f) { a = 0; b = 0; }
        c = 0;
        if (b) c = FUN_00215130_2a57a8(1, 0x53E3) != 0;
        if ((D_0013CAE4_2a57a8 & 0x10) && a && c) {
            FUN_L00_0029a6b0_2a57a8(p);
            p->b20 = 3;
        }
        break;
    case 3:
        if (q->mC) {
            q->f90 = 0.0f;
            q->mC->f2C = q->mC->p24->f24 * q->f90 * 2.5f;
            FUN_L00_00250df8_2a57a8(q->mC);
        }
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a5dd8.s", FUN_L00_002a5dd8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a6b70.s", FUN_L00_002a6b70);
#define NOT_SDA

#define MACRO_ADDR

/* Steers a thrown moby along its path: builds its orientation from the data's angles and, when done, releases the held target. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002A8088), where it is exact; names translated to the US level program. */

extern char *FUN_L00_002603d0_c(void *) __asm__("FUN_L00_002603d0");
extern float D_0015ED6C;
extern float FUN_001fa580(float, float);
extern float FUN_001fa5c8(float, float);
extern int FUN_L00_001f0d60(float, void *, int, void *);
extern int FUN_L00_002604f0(int x, char *o, float *p, float *q, float *r, float *s);
extern void FUN_001f99f8(void *);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a68(void *, void *, float);
extern void FUN_001fa030(void *, void *);
extern void FUN_001fa328(void *, void *, void *);
extern void FUN_001f9bf8(float *, float *, float);

void FUN_L00_002a6de8(char *moby, void *out1, void *out2) {
    char *data = *(char **)(moby + 0x78);
    float m0[12];
    float m1[12];
    float v60[4];
    float v70[4];
    float A[4];
    float B[4];
    float D[4];
    float C[4];
    float c1, c2, c3, c4, c5;

    if (*(char **)(data + 0x5C) != 0) {
        FUN_L00_002604f0((int)moby, *(char **)(data + 0x5C), (float *)data, (float *)(data + 0x10), A, B);
    } else {
        qcopy(A, data);
        qcopy(B, data + 0x10);
    }
    switch (*(short *)(moby + 0xA6)) {
    case 13:
        c1 = 0.04f; c2 = -0.25f; c3 = 0.04875f; c4 = 0.325f; c5 = 0.15f;
        break;
    case 14:
        c1 = 0.03f; c2 = -0.5f; c3 = 0.0245f; c4 = 0.35f; c5 = 0.23f;
        break;
    case 15:
        c1 = 0.025f; c2 = -0.4f; c3 = 0.05625f; c4 = 0.375f; c5 = 0.23f;
        break;
    default:
        c1 = 0.0175f; c2 = -0.35f; c3 = 0.135f; c4 = 0.3f; c5 = 0.25f;
        break;
    }
    if (*(unsigned char *)(data + 0x55) & 1) {
        *(float *)(data + 0x50) = FUN_001fa580(*(float *)(data + 0x50), c1);
        *(float *)(data + 0x58) = FUN_001fa580(*(float *)(data + 0x58), -0.0125f);
    } else {
        *(float *)(data + 0x50) = FUN_001fa5c8(*(float *)(data + 0x50), c1);
        *(float *)(data + 0x58) = FUN_001fa5c8(*(float *)(data + 0x58), -0.0125f);
    }
    qcopy(v60, data + 0x50);
    v60[1] = c2;
    FUN_001fa030(m0, v60);
    FUN_001fa030(m1, B);
    FUN_001fa328(moby + 0xC0, m1, m0);
    FUN_001f9a68(moby + 0x10, &m1[8], c3);
    FUN_001f9a68(v70, moby + 0xC0, c4);
    FUN_001f9a10(moby + 0x10, moby + 0x10, v70);
    FUN_001f9a10(moby + 0x10, moby + 0x10, A);
    if (out1 != 0) qcopy(out1, A);
    if (out2 != 0) qcopy(out2, B);
    if (*(unsigned char *)(moby + 0x20) == 3) {
        char *obj = *(char **)(data + 0x5C);
        if (obj != 0 && *(unsigned char *)(data + 0x57) == 0) {
            int r;
            char *x;
            if ((unsigned char)obj[0x20] == 0xFE || (*(unsigned char **)(data + 0x5C))[0x20] == 0xFD) {
                r = 1;
            } else {
                r = FUN_L00_001f0d60(c5, moby + 0x10, 0x22, moby) == 0;
            }
            if (r) {
                moby[0x20] = 1;
                FUN_001f99f8(data + 0x30);
                *(float *)(data + 0x3C) = 1.0f;
                x = FUN_L00_002603d0_c(*(char **)(data + 0x5C));
                if (x != 0) {
                    qcopy(data + 0x20, x + 0x10);
                } else {
                    FUN_001f99f8(data + 0x20);
                }
                FUN_001f9bf8(C, &m1[8], D_0015ED6C);
                FUN_001f9bf8(D, (float *)(moby + 0xC0), D_0015ED6C);
                FUN_001f9a10(C, C, D);
                FUN_001f9a10(data + 0x20, data + 0x20, C);
                FUN_001f9a10(moby + 0x10, moby + 0x10, data + 0x20);
                *(char **)(data + 0x5C) = 0;
            }
        }
    }
}
extern int D_1613AC_2a7210 __asm__("D_L00_001613AC") __attribute__((sda));
extern float D_1613A8_2a7210 __asm__("D_L00_001613A8") __attribute__((sda));
extern int D_15F5CC_2a7210 __asm__("D_L00_0015F5CC");
extern float D_15ED6C_2a7210 __asm__("D_0015ED6C");
extern int fr_2a7210(int) __asm__("FUN_001f96f8");
extern void snd_2a7210(int, int, char *) __asm__("FUN_0022da68");
extern float rndf_2a7210(float, float) __asm__("FUN_002132a8");
extern void mtx_2a7210(void *, void *) __asm__("FUN_001fa030");
extern void ff500_2a7210(void *, void *, float) __asm__("FUN_001f9bf8");
extern void sub_2a7210(void *, void *, void *) __asm__("FUN_001f9a28");
extern void cross_2a7210(void *, void *, void *) __asm__("FUN_001f9ad8");
extern void rot_2a7210(void *, void *, float) __asm__("FUN_00214530");

int FUN_L00_002a7210(void *ov, void *tv, float a, float b) {
    char *o = ov;
    char *t = tv;
    char *p = *(char **)(o + 0x78);
    int r, last, now;
    float k;
    float m[3][4] __attribute__((aligned(16)));

    if (*(unsigned char *)(o + 0x20) == 4) {
        return 0;
    }
    r = fr_2a7210(3);
    last = D_1613AC_2a7210;
    now = D_15F5CC_2a7210;
    if (last + r < now || now < last) {
        D_1613AC_2a7210 = now;
        snd_2a7210(0, 0x20, o);
    } else {
        if (a == 0.0f) a = rndf_2a7210(-30.0f, 30.0f) * 0.0174532924f;
        if (b == 0.0f) b = rndf_2a7210(0.0f, 30.0f) * 0.0174532924f;
    }
    if (*(unsigned char *)(o + 0x20) == 3) {
        mtx_2a7210(m, p + 0x10);
        ff500_2a7210(p + 0x20, m[2], rndf_2a7210(3.0f, 7.0f) * D_15ED6C_2a7210);
    }
    {
        *(float *)(p + 0x4C) = a;
        *(float *)(p + 0x48) = b;
        *(int *)(p + 0x64) = 0;
        *(char **)(p + 0x60) = t;
        sub_2a7210(m[1], t + 0x10, o + 0x10);
        cross_2a7210(m[0], p + 0x20, m[1]);
        ff500_2a7210(p + 0x30, m[0], 1.0f);
        k = rndf_2a7210(D_1613A8_2a7210 * 0.333000004f, D_1613A8_2a7210) * 0.0174532924f;
        rot_2a7210(p + 0x30, p + 0x30, k * D_15ED6C_2a7210);
    }
    *(unsigned char *)(o + 0x20) = 4;
    return 1;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a7438.s", FUN_L00_002a7438);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a7780.s", FUN_L00_002a7780);
typedef struct { char p0[0x50]; u8 b50; u8 b51; u8 b52; u8 b53; f32 f54; } O_002a7c70;
typedef struct { char p0[0x198]; s32 i198; char p1[0x2080 - 0x19C]; O_002a7c70 *p2080; s32 i2084; char p2[8]; s32 i2090; } G_002a7c70;
extern G_002a7c70 D_0013F350_002a7c70 __asm__("D_0013F350") __attribute__((section(".data")));
s32 FUN_001f96f8_002a7c70(s32) __asm__("FUN_001f96f8");
void FUN_00212f90_002a7c70(void *, s32, s32, s32) __asm__("FUN_00212f90");
void FUN_0020c880_002a7c70(void *) __asm__("FUN_0020c880");
void FUN_L00_002a7c70(O_002a7c70 *m) {
    G_002a7c70 *g = &D_0013F350_002a7c70;
    if (g->i2084 == 0x3B) {
        u8 c = g->p2080->b53;
        s32 k = 0xB;
        if (c == 0x40) k = 0x13;
        if (c == 0x41) k = 0x12;
        if (k == 0x12 || k == 0x13) {
            m->b52 = k;
            m->b53 = k;
            m->f54 = g->p2080->f54;
            m->b50 = g->p2080->b50;
            m->b51 = g->p2080->b51;
            if (g->p2080->b52 != g->p2080->b53) m->b50 = m->b51;
            FUN_0020c880_002a7c70(m);
        } else {
            FUN_00212f90_002a7c70(m, k, 0, FUN_001f96f8_002a7c70(7));
        }
    } else if (g->i2090 == 0x3B && g->i198 == 1) {
        FUN_00212f90_002a7c70(m, 1, 0, FUN_001f96f8_002a7c70(0x11));
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002A9030), where it is exact; names translated to the US level program. */

extern char *FUN_002141f8_002a7d90(void *) __asm__("FUN_002141f8");
extern void *D_L00_00173E58_002a7d90 __asm__("D_L00_00173E58") __attribute__((section(".data")));

int FUN_L00_002a7d90(void) {
    int r = 0;
    char *x = 0;
    if (D_L00_00173E58_002a7d90 != 0) x = FUN_002141f8_002a7d90(D_L00_00173E58_002a7d90);
    if (x != 0) r = *(unsigned char *)(x + 9) == 1;
    return r;
}
extern int D_L00_00173E58 __attribute__((section(".data")));
char *FUN_L00_0025c338(int);
int FUN_L00_002a7de0(void) { char *p = FUN_L00_0025c338(D_L00_00173E58); if (p && (*(unsigned short *)(p + 0x1e) & 2)) return 1; return 0; }
typedef int ti_2a7e20 __attribute__((mode(TI)));
extern float rndf_2a7e20(float, float) __asm__("FUN_002132a8");
extern int rndi_2a7e20(int) __asm__("FUN_00213260");
extern float rnda_2a7e20(void) __asm__("FUN_00213308");
extern void dir_2a7e20(void *, float, float, float) __asm__("FUN_00214db0");
extern float rnd_2a7e20(float, float) __asm__("FUN_L00_00257c48");
extern int fr_2a7e20(int) __asm__("FUN_001f96f8");
extern void emit_2a7e20(float *, int, int, int, int, void *, float, float, float) __asm__("FUN_L00_00272060");

void FUN_L00_002a7e20(float *pos, int n) {
    ti_2a7e20 dir[1];
    ti_2a7e20 old[1];
    int i;
    for (i = 0; i < n; i++) {
        float s = rndf_2a7e20(0.1f, 2.0f);
        int k = rndi_2a7e20(2);
        float a, b;
        if (k == 0) k--;
        a = rnda_2a7e20();
        b = rndf_2a7e20(0.34906584f, 1.53588974f);
        dir_2a7e20(dir, rndf_2a7e20(0.05f, 0.1f), a, b);
        qcopy(old, pos);
        pos[0] += rnd_2a7e20(0.0f, 0.15f);
        pos[1] += rnd_2a7e20(0.0f, 0.15f);
        pos[2] += rnd_2a7e20(0.0f, 0.15f);
        emit_2a7e20(pos, fr_2a7e20(0x1E), 0x7F207F7F, 0, k, dir, s * 0.1f, s, 0.003f);
        k = -k;
        emit_2a7e20(pos, fr_2a7e20(0x1E), 0x7F7F7F7F, 1, k, dir, s * 0.07f, s * 0.7f, 0.003f);
    }
}
typedef union { u128 q; f32 f[4]; } V2a8028;
extern V2a8028 D_L00_00166DC0_2a8028 __asm__("D_L00_00166DC0") __attribute__((section(".data")));
extern V2a8028 D_L00_00173E60_2a8028 __asm__("D_L00_00173E60") __attribute__((section(".data")));
extern f32 D_L00_00173E40_2a8028[] __asm__("D_L00_00173E40") __attribute__((section(".data")));
extern void sub_2a8028(void *, void *, void *) __asm__("FUN_001f9a28");
extern f32 len_2a8028(void *) __asm__("FUN_001f9b20");
extern f32 atan_2a8028(f32, f32) __asm__("FUN_001f9e90");
extern f32 rnd_2a8028(f32, f32) __asm__("FUN_L00_00257c48");
extern f32 ang_2a8028(f32, f32) __asm__("FUN_001fa580");
extern void dir_2a8028(void *, f32, f32, f32) __asm__("FUN_00214db0");
extern f32 rndf_2a8028(f32, f32) __asm__("FUN_002132a8");
extern void scale_2a8028(void *, void *, f32) __asm__("FUN_001f9a68");
extern void add_2a8028(void *, void *, void *) __asm__("FUN_001f9a10");
extern void spawn_2a8028(void *, void *) __asm__("FUN_L00_0026c6e8");
extern s32 fr_2a8028(s32) __asm__("FUN_001f96f8");
extern s32 rndi_2a8028(s32, s32) __asm__("FUN_L00_00257b90");
extern void spark_2a8028(void *, void *, s32, s32, s32, s32, f32) __asm__("FUN_L00_0026cbb0");
extern void fin_2a8028(void *, s32) __asm__("FUN_L00_002a7e20");
void FUN_L00_002a8028(u8 *o) {
    V2a8028 v;
    V2a8028 w;
    f32 pitch;
    f32 a;
    s32 i;
    s32 n;
    sub_2a8028(&v, &D_L00_00166DC0_2a8028, &D_L00_00173E60_2a8028);
    pitch = -atan_2a8028(len_2a8028(&v), v.f[2]);
    atan_2a8028(v.f[0], v.f[1]);
    for (i = 19; i >= 0; i--) {
        a = ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch);
        dir_2a8028(&v, 0.2f, ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch), a);
        scale_2a8028(&w, &v, rndf_2a8028(1.0f, 3.0f));
        add_2a8028(&w, &w, &D_L00_00173E60_2a8028);
        spawn_2a8028(&w, &v);
    }
    for (i = 9; i >= 0; i--) {
        w.f[0] = D_L00_00173E40_2a8028[8] + rnd_2a8028(0.0f, 0.1f);
        w.f[1] = D_L00_00173E40_2a8028[9] + rnd_2a8028(0.0f, 0.1f);
        w.f[2] = D_L00_00173E40_2a8028[10] + rnd_2a8028(0.0f, 0.1f);
        a = ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch);
        dir_2a8028(&v, 0.05f, ang_2a8028(rnd_2a8028(0.0f, 3.1415927f), pitch), a);
        n = fr_2a8028(10);
        spark_2a8028(&w, &v, 0x4F007FFF, 0x1FFFFFFF, rndi_2a8028(n, fr_2a8028(20)), 1, 20000.0f);
    }
    if (*(s16 *)(*(u8 **)(o + 0x78) + 0x78) == 0x2B) {
        fin_2a8028(&D_L00_00173E60_2a8028, 10);
    }
}
typedef struct N_2a82c0 { char p0[0x20]; unsigned char type; char p1[3]; char *info; struct N_2a82c0 *next; } N_2a82c0;
extern N_2a82c0 *D_L00_0015FFE4;
extern char D_0013F350[];
extern float FUN_001f9b48(void *, void *);
extern float FUN_002132a8(float, float);
extern int FUN_L00_002a7210(void *, void *, float, float);
extern int FUN_L00_0025e3f8(void *);
extern int FUN_L00_002c5be8(void *);

void FUN_L00_002a82c0(unsigned char *m) {
    N_2a82c0 *n = D_L00_0015FFE4;
    char *g;
    int r;
    if (n == 0) return;
    g = D_0013F350;
    do {
        if (n->type == 0xFE) return;
        if (n->type == 0xFD) return;
        if (n && n->info && *(short *)(n->info + 0x46) == 0x13) {
            if (FUN_001f9b48((char *)n + 0x10, m + 0x10) < 2.7f) {
                r = FUN_L00_002a7210(n, *(void **)(g + 0x2080), FUN_002132a8(-30.0f, 30.0f) * 0.017453292f, 0.0f);
                goto check;
            }
        } else if (FUN_L00_0025e3f8(n) && FUN_001f9b48((char *)n + 0x10, m + 0x10) < 2.7f) {
            r = FUN_L00_002c5be8(n);
check:
            if (r) return;
        }
        n = n->next;
    } while (n);
}
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002A96B8), where it is exact; names translated to the US level program. */

extern float D_0013F3E8[];
extern float FastDiffRots(float, float) __asm__("FUN_001fa688");
extern float FastVecLength(void *) __asm__("FUN_001f9af0");
extern float FUN_001f9e90(float, float);
extern void FUN_001f9bf8(float *, float *, float);

void FUN_L00_002a8418(float *v) {
    float k = 1.8325957f;
    float a = FUN_001f9e90(v[0], v[1]);
    float t = FastDiffRots(D_0013F3E8[0], a);
    if (t > k) t = k;
    FUN_001f9bf8(v, v, FastVecLength(v) * ((k - t) / k * 0.3f + 0.7f));
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a84c8.s", FUN_L00_002a84c8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002a96f8.s", FUN_L00_002a96f8);
/* Creates a moby at a position with a scale, colour and a few data fields. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002AAC50), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m(int);
extern void FUN_L00_002502f0(void *, int, int, int);

void *FUN_L00_002a99b0(int unused, void *pos, int c, float scale, float a, float b) {
    char *m = func_0020D348_m(0x593);
    if (m != 0) {
        char *d;
        float s;
        qcopy(m + 0x10, pos);
        FUN_L00_002502f0(m, 0x80, 0x80, 0x70);
        d = *(char **)(m + 0x78);
        s = scale + scale;
        *(float *)d = a;
        *(float *)(m + 0x2C) = s;
        *(float *)(m + 0x2C) = s * *(float *)(*(char **)(m + 0x24) + 0x24);
        *(int *)(d + 4) = c;
        *(int *)(d + 8) = c;
        *(float *)(d + 0xC) = b;
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        *(unsigned char *)(m + 0x31) = 1;
        *(unsigned char *)(m + 0x20) = 0;
    }
    return m;
}
typedef int u128_q __attribute__((mode(TI)));

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002AAD40), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m_q(int) __asm__("func_0020D348_m");
extern int D_L00_0015F320_q __asm__("D_L00_0015F320");
extern int D_L00_0015F324_q __asm__("D_L00_0015F324");
extern int D_L00_0015F330_q __asm__("D_L00_0015F330");
extern int D_L00_0015F334_q __asm__("D_L00_0015F334");
extern int FUN_L00_0023e5e0_q(float *pos, float radius, float intensity, int color) __asm__("FUN_L00_0023e5e0");
extern long D_L00_0015F328_q __asm__("D_L00_0015F328");
extern long D_L00_0015F338_q __asm__("D_L00_0015F338");
extern short D_L00_001613C8_q __asm__("D_L00_001613C8") __attribute__((sda));

void *FUN_L00_002a9aa0(int unused, float *pos) {
    char *m = func_0020D348_m_q(0x5F3);
    if (m != 0 && *(int *)&D_L00_001613C8_q == 0) {
        char *d;
        m[0x20] = 0;
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        d = *(char **)(m + 0x78);
        *(u128_q *)(m + 0x10) = *(u128_q *)pos;
        D_L00_0015F324_q = 0xFF;
        D_L00_0015F334_q = 0xFFFFFF;
        D_L00_0015F338_q = 0x1F00000042L;
        *(int *)&D_L00_001613C8_q = (int)m;
        D_L00_0015F328_q = 0;
        D_L00_0015F320_q = 0;
        D_L00_0015F330_q = 0;
        *(int *)(d + 0x10) = 0;
        *(short *)(d + 0x2C) = FUN_L00_0023e5e0_q(pos, 0.0f, 0.0f, 0);
    }
    return m;
}
typedef int q128_2a9b80 __attribute__((mode(TI)));
extern u8 *D_L00_001613C8 __attribute__((sda));
void FUN_L00_002a9aa0_u(void *, q128_2a9b80 *) __asm__("FUN_L00_002a9aa0");
void FUN_L00_002a9b80(void *a, q128_2a9b80 *v) { q128_2a9b80 t = *v; u8 *p; u8 *q; u8 *g;
 g = D_L00_001613C8; if (g == 0) { FUN_L00_002a9aa0_u(a, &t); g = D_L00_001613C8; if (g == 0) return; }
 p = D_L00_001613C8; q = *(u8 **)(p + 0x78);
 if (*(s16 *)(p + 0xA6) == 0x5F3) { *(q128_2a9b80 *)(p + 0x10) = t; *(s16 *)(q + 0x2E) = 1; } }
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_002A5138.c: func_L00_002AAE80), where it is exact; names translated to the US level program. */

extern int D_L00_0015F320;
extern int D_L00_0015F330;
extern short D_L00_001613C8_d __asm__("D_L00_001613C8") __attribute__((sda));
extern void FUN_L00_0023e838(int);
void mark_moby_for_removal(struct Obj *obj) __asm__("FUN_0020c828");

void FUN_L00_002a9be0(void) {
    char *m = *(char **)&D_L00_001613C8_d;
    if (m != 0) {
        if (*(short *)(m + 0xA6) == 0x5F3) {
            char *data;
            int idx;
            if (*(unsigned char *)(m + 0x20) != 0) return;
            data = *(char **)(m + 0x78);
            D_L00_0015F320 = 0;
            D_L00_0015F330 = 0;
            idx = *(short *)(data + 0x2C);
            if (idx != -1) FUN_L00_0023e838(idx);
            mark_moby_for_removal(*(char **)&D_L00_001613C8_d);
        }
        *(int *)&D_L00_001613C8_d = 0;
    }
}
typedef union { u128 q; f32 f[4]; } V_2a9c50;
typedef struct {
    V_2a9c50 corner[4];
    u32 color[4];
    f32 uv[8];
    s64 unk70;
    s64 tex;
    s64 unk80;
    s64 unk88;
} Q_2a9c50;
typedef struct {
    u8 pad0[0x10];
    V_2a9c50 pos;
    f32 f20, f24, f28;
} PV_2a9c50;
typedef struct {
    u8 pad0[0x78];
    PV_2a9c50 *pv;
} M_2a9c50;
extern s32 D_L00_0015F5C4;
extern s32 D_L00_0015F5CC;
extern f32 rzx_2a9c50 __asm__("D_L00_001613E0") __attribute__((sda));
extern f32 rzy_2a9c50 __asm__("D_L00_001613E4");
extern f32 rzz_2a9c50 __asm__("D_L00_001613E8");
extern f32 rzw_2a9c50 __asm__("D_L00_001613EC");
extern f32 sqrt_2a9c50(f32) __asm__("FUN_001f9988");
extern f32 atan2_2a9c50(f32, f32) __asm__("FUN_001f9e90");
extern f32 appr_2a9c50(f32, f32) __asm__("FUN_001fa580");
int FUN_001f96f8(int);
float FUN_001fa6c0(int);
extern f32 i2f_2a9c50(f32) __asm__("FUN_001f96b0");
extern f32 sin_2a9c50(f32) __asm__("FUN_001fa610");
extern void rmat_2a9c50(void *, void *) __asm__("FUN_001fa050");
extern void mmul_2a9c50(void *, void *, void *) __asm__("FUN_001fa378");
extern s64 tex_2a9c50(s32) __asm__("FUN_001f44b8");
extern void draw_2a9c50(void *, void *, s32) __asm__("FUN_001f7d30");
void FUN_L00_002a9c50(M_2a9c50 *m) {
    Q_2a9c50 quad;
    V_2a9c50 mat[4];
    V_2a9c50 mz[4];
    V_2a9c50 rot;
    PV_2a9c50 *pv = m->pv;
    s32 i;
    s32 odd;
    f32 a, t;
    if (D_L00_0015F5C4 == 2) {
        return;
    }
    for (i = 0; i < 2; i++) {
        odd = i & 1;
        a = atan2_2a9c50(sqrt_2a9c50(pv->f20 * pv->f20 + pv->f28 * pv->f28), pv->f24);
        rot.f[0] = appr_2a9c50(-a, 1.57079637f);
        rot.f[1] = atan2_2a9c50(pv->f28, pv->f20);
        rot.f[2] = 0.0f;
        rot.f[3] = 0.0f;
        rzx_2a9c50 = 0.0f;
        t = FUN_001fa6c0(D_L00_0015F5CC % FUN_001f96f8(180));
        {
            f32 d = i2f_2a9c50(180.0f);
            f32 r;
            t *= 6.28318548f;
            r = sin_2a9c50(t / d);
            if (odd) {
                r = -r;
            }
            rzy_2a9c50 = r;
        }
        rzz_2a9c50 = 0.0f;
        *(volatile f32 *)&rzw_2a9c50 = 0.0f;
        rmat_2a9c50(mz, &rzx_2a9c50);
        rmat_2a9c50(mat, &rot);
        mmul_2a9c50(mat, mat, mz);
        qcopy(&mat[3], &pv->pos);
        quad.color[0] = 0x80808080;
        quad.color[1] = 0x80808080;
        quad.color[2] = 0x80808080;
        quad.color[3] = 0x80808080;
        quad.tex = tex_2a9c50(odd ? 0x12 : 0x11);
        quad.unk80 = 0xFF9000000260L;
        quad.unk88 = 0x8000000048L;
        quad.unk70 = 0;
        quad.corner[0].f[0] = -1.0f;
        quad.corner[0].f[1] = 0.0f;
        quad.corner[0].f[2] = 1.0f;
        quad.corner[0].f[3] = 1.0f;
        quad.corner[1].f[0] = 1.0f;
        quad.corner[1].f[1] = 0.0f;
        quad.corner[1].f[2] = 1.0f;
        quad.corner[1].f[3] = 1.0f;
        quad.corner[2].f[0] = -1.0f;
        quad.corner[2].f[1] = 0.0f;
        quad.corner[2].f[2] = -1.0f;
        quad.corner[2].f[3] = 1.0f;
        quad.corner[3].f[0] = 1.0f;
        quad.corner[3].f[1] = 0.0f;
        quad.corner[3].f[2] = -1.0f;
        quad.corner[3].f[3] = 1.0f;
        quad.uv[0] = 0.0f;
        quad.uv[1] = 1.0f;
        quad.uv[2] = 1.0f;
        quad.uv[3] = 1.0f;
        quad.uv[4] = 0.0f;
        quad.uv[5] = 0.0f;
        quad.uv[6] = 1.0f;
        quad.uv[7] = 0.0f;
        draw_2a9c50(&quad, mat, 1);
    }
}
typedef int q128_2a9ed0 __attribute__((mode(TI)));
extern float D_0015ED6C_2a9ed0 __asm__("D_0015ED6C");
extern int D_L00_0015F5CC_2a9ed0 __asm__("D_L00_0015F5CC");
unsigned char *FUN_0020c4f8_2a9ed0(int) __asm__("FUN_0020c4f8");
void FUN_001f99f8_2a9ed0(void *) __asm__("FUN_001f99f8");
float FUN_002132a8_2a9ed0(float, float) __asm__("FUN_002132a8");
void FUN_L00_00250df8_2a9ed0(void *) __asm__("FUN_L00_00250df8");
unsigned char *FUN_L00_002a9ed0(int owner, q128_2a9ed0 *pos) {
    unsigned char *m = FUN_0020c4f8_2a9ed0(0x4A);
    if (m) {
        unsigned char *v = *(unsigned char **)(m + 0x78);
        m[0x30] = 0xFF;
        *(short *)(m + 0x32) = 0x7F;
        m[0x31] = 1;
        *(float *)(m + 0x2C) = *(float *)(m + 0x2C) * 0.5f;
        m[0x20] = 0;
        *(int *)(v + 0x30) = owner;
        *(short *)(v + 0x36) = 0;
        *(int *)(v + 0x78) = 0;
        qcopy(m + 0x10, pos);
        FUN_001f99f8_2a9ed0(v);
        {
        float a = FUN_002132a8_2a9ed0(D_0015ED6C_2a9ed0 * 1.0471976f, D_0015ED6C_2a9ed0 * 3.1415927f);
        float d = D_0015ED6C_2a9ed0;
        float b;
        int x;
        float z;
        *(float *)(v + 0x38) = a;
        b = FUN_002132a8_2a9ed0(d * 1.0471976f, d * 3.1415927f);
        x = D_L00_0015F5CC_2a9ed0;
        z = 0.0f;
        *(float *)(v + 0x3C) = b;
        *(float *)(v + 0x64) = z;
        *(float *)(v + 0x60) = z;
        *(float *)(v + 0x70) = z;
        *(float *)(v + 0x6C) = z;
        *(int *)(v + 0x5C) = x;
        *(int *)(v + 0x74) = 0;
        *(int *)(v + 0x68) = -1;
        *(int *)(m + 0x94) = 0;
        }
        FUN_L00_00250df8_2a9ed0(m);
    }
    return m;
}
typedef union { u128 q; f32 f[4]; } V_2aa008;
typedef struct { u8 pad[0x5C]; s32 i5C; } D_2aa008;
typedef struct { u8 pad[0x34]; s16 h34; } M_2aa008;
typedef struct N_2aa008 { u8 pad[0x10]; V_2aa008 v10; u8 b20; u8 pad2[0x28 - 0x21]; struct N_2aa008 *p28; f32 f2C; u8 pad3[0x78 - 0x30]; void *p78; u8 pad4[0xA6 - 0x7C]; s16 hA6; } N_2aa008;
typedef struct { u8 pad[0x10]; V_2aa008 v10; } Q_2aa008;
typedef struct { u8 pad[0x100]; u8 v100[0x2FC - 0x100]; void *p2FC; u8 pad2[0x2080 - 0x300]; Q_2aa008 *p2080; } P_2aa008;
extern P_2aa008 D_0013F350_2aa008 __asm__("D_0013F350");
extern f32 D_0015ED6C_2aa008 __asm__("D_0015ED6C");
extern f32 D_0015ED70_2aa008 __asm__("D_0015ED70");
extern N_2aa008 *D_L00_0015FFE4_2aa008 __asm__("D_L00_0015FFE4");
extern V_2aa008 D_L00_00173E60_2aa008[] __asm__("D_L00_00173E60") __attribute__((section(".data")));
f32 FUN_002132a8_2aa008(f32, f32) __asm__("FUN_002132a8");
void FUN_001f9bf8_2aa008(void *, void *, f32) __asm__("FUN_001f9bf8");
void FUN_001f9a10_2aa008(void *, void *, void *) __asm__("FUN_001f9a10");
s32 FUN_L00_002603d0_2aa008(void *) __asm__("FUN_L00_002603d0");
s32 FUN_001f96f8_2aa008(s32) __asm__("FUN_001f96f8");
s32 FUN_001efa68_2aa008(void *, void *, s32, void *, s32) __asm__("FUN_001efa68");
void FUN_L00_001ff660_2aa008(void *, void *, void *) __asm__("FUN_L00_001ff660");
void FUN_001f9a68_2aa008(void *, void *, f32) __asm__("FUN_001f9a68");
void FUN_L00_002aa008(V_2aa008 *pos, N_2aa008 *self, void *arg) {
    V_2aa008 d;
    V_2aa008 t;
    V_2aa008 e;
    M_2aa008 *m;
    P_2aa008 *P;
    N_2aa008 *n;
    s32 count;
    N_2aa008 *best;
    s32 bestv;
    V_2aa008 *k;
    t.q = 0;
    m = self->p78;
    t.f[0] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    t.f[1] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    t.f[2] = FUN_002132a8_2aa008(-1.0f, 1.0f);
    self->b20 = 1;
    self->f2C = self->f2C / 0.65f;
    d.q = t.q;
    FUN_001f9bf8_2aa008(&d, &d, FUN_002132a8_2aa008(D_0015ED6C_2aa008 * 0.01f, D_0015ED6C_2aa008 * 0.1f));
    FUN_001f9a10_2aa008(m, &d, arg);
    P = &D_0013F350_2aa008;
    if (P->p2FC && FUN_L00_002603d0_2aa008(P->p2FC)) {
        FUN_001f9a10_2aa008(m, m, P->v100);
    }
    m->h34 = FUN_001f96f8_2aa008(0x78);
    count = 0;
    best = 0;
    bestv = 0;
    for (n = D_L00_0015FFE4_2aa008; n; n = n->p28) {
        if (n->b20 != 0xFE) if (n->b20 != 0xFD) if (n->hA6 == self->hA6) if (n != self) {
            if (best == 0 || ((D_2aa008 *)n->p78)->i5C < bestv) {
                bestv = ((D_2aa008 *)n->p78)->i5C;
                best = n;
            }
            count++;
        }
    }
    if (count >= 8) ((D_2aa008 *)best->p78)->i5C = -1;
    qcopy(&self->v10, pos);
    t.q = D_0013F350_2aa008.p2080->v10.q;
    t.f[2] = pos->f[2];
    if (FUN_001efa68_2aa008(&t, pos, 0, D_0013F350_2aa008.p2080, 0)) {
        k = D_L00_00173E60_2aa008;
        qcopy(&self->v10, &k[0]);
        FUN_001f9bf8_2aa008(&e, &k[2], D_0015ED70_2aa008 * 9.7f);
        FUN_001f9a10_2aa008(&self->v10, &self->v10, &e);
        FUN_L00_001ff660_2aa008(m, m, &k[2]);
        FUN_001f9a68_2aa008(m, m, 0.6f);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_002aa2a8.s", FUN_L00_002aa2a8);
