/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002979d8.s", FUN_L15_002979d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00299880.s", FUN_L15_00299880);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029AC48), where it is exact; names translated to the US level program. */

extern float FUN_001f9e90(float, float);
extern void FUN_L15_00299880(void *, void *, void *, void *, float);

void FUN_L15_00299a68(char *moby, void *a, float *point, void *b, void *c)
{
    float angle = FUN_001f9e90(point[0] - *(float *)(moby + 0x10),
                                     point[1] - *(float *)(moby + 0x14));
    FUN_L15_00299880(moby, a, b, c, angle);
}
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029ACC0), where it is exact; names translated to the US level program. */

extern f32 approach_value(f32 *, f32, f32) __asm__("FUN_00213ed8");
extern float D_0015ED6C;
extern float D_0015ED70;
extern float FUN_001f9b80(float *, float *);
extern float FUN_001fa688(float, float);
extern float FUN_L00_0025be00(float *p, float *v, float a, float b, float c, float d);
extern float fast_cos(float) __asm__("func_001F9DC8");
extern float fast_sin(float) __asm__("func_001F9DE0");
extern void FUN_L00_00258830(int, int, float, float, float, int);

int FUN_L15_00299ae0(char *moby, float *point, float arg) {
    float *fp = (float *)(moby + 0x48);
    char *d = *(char **)(moby + 0x78);
    float vec[4];
    float a;
    float ang;
    a = FUN_001f9e90(point[0] - *(float *)(moby + 0x10), point[1] - *(float *)(moby + 0x14));
    FUN_L00_0025be00(fp, (float *)(d + 0x138), a, D_0015ED70 * 12.566371f, D_0015ED70 * 12.566371f, D_0015ED6C * 6.981317f);
    ang = FUN_001f9e90(point[0] - *(float *)(moby + 0x10), point[1] - *(float *)(moby + 0x14));
    if (FUN_001fa688(*(float *)(moby + 0x48), ang) < 0.7853982f) {
        approach_value(d + 0x134, arg, D_0015ED70 * 9.0f);
    } else {
        approach_value(d + 0x134, 0.0f, D_0015ED70 * 9.0f);
    }
    vec[0] = fast_cos(*(float *)(moby + 0x48)) * *(float *)(d + 0x134);
    vec[1] = fast_sin(*(float *)(moby + 0x48)) * *(float *)(d + 0x134);
    vec[2] = -(D_0015ED6C * 0.5f);
    FUN_L00_00258830((int)moby, (int)vec, 0.5f, 0.5f, 0.0f, 0);
    return FUN_001f9b80((float *)(moby + 0x10), point) < 0.2f;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00299ca0.s", FUN_L15_00299ca0);
#include "sda.h"

#include "qcopy.h"

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029AFB8), where it is exact; names translated to the US level program. */

extern float FUN_001f9b48(void *, void *);
extern int D_L15_0015FFD8_m __asm__("D_L15_0015FFD8") __attribute__((section(".sdata")));
extern int D_L15_001ABE40[];
extern int FUN_001efa68(void *, void *, int, void *, void *);

int FUN_L15_00299dd8(char *m) {
    char *d = *(char **)(m + 0x78);
    int best = 0;
    float bd;
    float a[4];
    float b[4];
    short *p;
    int idx = *(int *)(d + 0x17C);
    if (idx == -1) return 0;
    p = (short *)D_L15_001ABE40[idx];
    if (p == 0) return 0;
    qcopy(a, m + 0x10);
    a[2] += 1.0f;
    bd = 0.0f;
    do {
        int id = *(unsigned short *)p & 0x7FFF;
        char *o = (char *)((id << 8) + D_L15_0015FFD8_m);
        if (*(short *)(o + 0xA6) == 0x27B && *(unsigned char *)(o + 0x20) >= 6 && *(unsigned char *)(o + 0x20) < 0x10) {
            float f = FUN_001fa688(*(float *)(m + 0x48),
                FUN_001f9e90(*(float *)(o + 0x10) - *(float *)(m + 0x10), *(float *)(o + 0x14) - *(float *)(m + 0x14)));
            unsigned char st = ((char *)((id << 8) + D_L15_0015FFD8_m))[0x20];
            if (st == 7 || st == 0xF) *(short *)(d + 0x194) = 1;
            if (*(short *)(d + 0x194) != 0 || f < 1.2217305f) {
                qcopy(b, (char *)((id << 8) + D_L15_0015FFD8_m) + 0x10);
                a[2] += 1.0f;
                if (FUN_001efa68(a, b, 2, 0, 0) == 0) {
                    float dist = FUN_001f9b48(a, b);
                    if (best == 0 || dist < bd) {
                        bd = dist;
                        best = D_L15_0015FFD8_m + (id << 8);
                    }
                }
            }
        }
    } while (*p++ >= 0);
    if (*(short *)(d + 0x194) == 0) {
        if (bd > 8.0f) best = 0;
    }
    return best;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_00299ff8.s", FUN_L15_00299ff8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029a0d0.s", FUN_L15_0029a0d0);
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029B428), where it is exact; names translated to the US level program. */

extern int FUN_001f96f8(int);
s32 random_integer_below(s32 arg0) __asm__("FUN_00213260");

void FUN_L15_0029a248(char *a, char *b) {
    char *d;
    if (a != b) {
        d = *(char **)(b + 0x78);
        if (*(short *)(d + 0x19C) == 0 || random_integer_below(0x10) == 0) {
            *(char **)(d + 0x198) = a;
            *(short *)(d + 0x19C) = FUN_001f96f8(0xB4);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029a2a8.s", FUN_L15_0029a2a8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029a570.s", FUN_L15_0029a570);
#define NOT_SDA

#define MACRO_ADDR

/* Applies the same effect to three consecutive 16-byte slots of a moby's data, tagged with its colour word. */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029BD88), where it is exact; names translated to the US level program. */

extern void FUN_L00_00263618(void *, int, float, float);

void FUN_L15_0029aba8(char *m) {
    int v = (*(int *)(m + 0x90) & 0xFFFFFF) | 0x30000000;
    char *p = *(char **)(m + 0x78) + 0x2A0;
    int i;
    for (i = 2; i >= 0; i--) {
        FUN_L00_00263618(p, v, 0.2f, 0.08f);
        p += 0x10;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029ac30.s", FUN_L15_0029ac30);
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_0029BFF8), where it is exact; names translated to the US level program. */

extern char *FUN_00218888(void *, void *, void *, int, int, int, int, int, int);
extern float D_0015ED6C_c __asm__("D_0015ED6C") __attribute__((section(".sdata")));
extern float FUN_001f96b0(float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern short D_L15_00161418 __attribute__((sda));
extern short D_L15_00161428 __attribute__((sda));
extern short D_L15_00161438 __attribute__((sda));
extern short D_L15_00161448 __attribute__((sda));
extern short D_L15_0016141C __attribute__((sda));
extern short D_L15_00161420 __attribute__((sda));
extern short D_L15_00161424 __attribute__((sda));
extern short D_L15_0016142C __attribute__((sda));
extern short D_L15_00161430 __attribute__((sda));
extern short D_L15_00161434 __attribute__((sda));
extern short D_L15_0016143C __attribute__((sda));
extern short D_L15_00161440 __attribute__((sda));
extern short D_L15_00161444 __attribute__((sda));
extern short D_L15_0016144C __attribute__((sda));
extern short D_L15_00161454 __attribute__((sda));
extern void FUN_L00_00257d78(float *, float, float);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void scale_vector_xyz(void *out, void *a, f32 s) __asm__("FUN_001f9a68");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L15_0029ae18(char *moby) {
    float v2[4];
    float v0[4];
    float v1[4];
    char *data = *(char **)(moby + 0x78);
    float s;
    int a, b, c;
    s = *(float *)&D_L15_00161440;
    s *= D_0015ED6C_c;
    scale_vector_xyz(v0, data, *(float *)&D_L15_00161448);
    FUN_L00_00257d78(v2, s, s);
    add_vector_xyz(v0, v0, v2);
    s = *(float *)&D_L15_00161444;
    s *= D_0015ED6C_c;
    scale_vector_xyz(v1, data, *(float *)&D_L15_0016144C);
    FUN_L00_00257d78(v2, s, s);
    add_vector_xyz(v1, v1, v2);
    v0[3] = *(float *)&D_L15_00161420;
    v1[3] = *(float *)&D_L15_00161424;
    a = func_001FA898_r(FUN_001f96b0(random_float_between_alt(*(float *)&D_L15_00161428, *(float *)&D_L15_0016142C)));
    b = func_001FA898_r(FUN_001f96b0(random_float_between_alt(*(float *)&D_L15_00161430, *(float *)&D_L15_00161434)));
    c = func_001FA898_r(FUN_001f96b0(random_float_between_alt(*(float *)&D_L15_00161438, *(float *)&D_L15_0016143C)));
    FUN_00218888(moby + 0x10, v0, v1, *(int *)&D_L15_00161418, *(int *)&D_L15_0016141C, a, b, c, *(int *)&D_L15_00161454);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029af88.s", FUN_L15_0029af88);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029d6c0.s", FUN_L15_0029d6c0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029ead0.s", FUN_L15_0029ead0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_0029edb0.s", FUN_L15_0029edb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a2488.s", FUN_L15_002a2488);
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002A3A48), where it is exact; names translated to the US level program. */

typedef struct {
    char _pad00[0x10];
    unsigned char nframes; /* 0x10 */
} AnimSeq;

typedef struct {
    char _pad00[0x48];
    AnimSeq *seqs[1]; /* 0x48 */
} AnimClass;

typedef struct {
    char _pad00[0x24];
    AnimClass *pClass;       /* 0x24 */
    char _pad28[0x50 - 0x28];
    unsigned char frame;     /* 0x50 */
    unsigned char nextFrame; /* 0x51 */
    unsigned char seq;       /* 0x52 */
    unsigned char prevSeq;   /* 0x53 */
    char _pad54[0x5C - 0x54];
    float unk5C;             /* 0x5C */
    char _pad60[0x68 - 0x60];
    float *frameData;        /* 0x68 */
    char _pad6C[4];
    unsigned char unk70;     /* 0x70 */
} MobyAnim;

extern char D_0013F350[];
extern int D_L15_0015FFD8;
void blend_moby_animation(MobyAnim *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

int FUN_L15_002a2868(int idx, void *pos) {
    short *p = (short *)D_L15_001ABE40[idx];
    char *g = D_0013F350;
    do {
        unsigned char *m = (unsigned char *)D_L15_0015FFD8 + ((*(unsigned short *)p & 0x7FFF) << 8);
        unsigned char state = m[0x20];
        if (state == 1) {
            char *data;
            m[0x20] = 2;
            if (m[0x53] != 0) blend_moby_animation(m, 0, 0, 0);
            *(unsigned short *)(m + 0x34) |= 1;
            m[0x31] = 0;
            data = *(char **)(m + 0x78);
            *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
            *(float *)(data + 0x64) = random_float_between_alt(-15.0f, 15.0f) * 0.017453292f;
            *(int *)(data + 0x68) = FUN_001f96f8(0x3C);
            qcopy(m + 0x10, pos);
            *(float *)(m + 0x18) -= 1.0f;
            *(float *)(m + 0x48) = FUN_001f9e90(*(float *)(g + 0x80) - *(float *)(m + 0x10), *(float *)(g + 0x84) - *(float *)(m + 0x14));
            return 1;
        }
    } while (*p++ >= 0);
    return 0;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a29b8.s", FUN_L15_002a29b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a2bf0.s", FUN_L15_002a2bf0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a3138.s", FUN_L15_002a3138);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a35d8.s", FUN_L15_002a35d8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a6e68.s", FUN_L15_002a6e68);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002a7628.s", FUN_L15_002a7628);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002bddb0.s", FUN_L15_002bddb0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L15_002cb4c8.s", FUN_L15_002cb4c8);
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002CCE50), where it is exact; names translated to the US level program. */

extern int D_L15_0015FFD8_m __asm__("D_L15_0015FFD8");
extern int D_L15_001ABE40_q[] __asm__("D_L15_001ABE40") __attribute__((section(".data")));
extern s32 scale_game_frames_q(s32) __asm__("FUN_001f96f8");
extern short D_L15_00161ABC_q __asm__("D_L15_00161ABC") __attribute__((sda));

void FUN_L15_002cbac0(char *m, int a) {
    char *d = *(char **)(m + 0x78);
    int flag;
    short *p;
    if (a == -1) {
        *(int *)&D_L15_00161ABC_q = 0;
        a = 0;
    }
    flag = a != 0;
    if (((unsigned char *)m)[0x21] == 0xFF) {
        *(int *)(d + 0x18) = scale_game_frames_q(a);
        *(int *)(d + 8) = flag;
        return;
    }
    p = (short *)D_L15_001ABE40_q[((unsigned char *)m)[0x21]];
    if (p) {
        do {
            char *o = (char *)(((*(unsigned short *)p & 0x7FFF) << 8) + D_L15_0015FFD8_m);
            if (*(short *)(o + 0xA6) == 0x198) {
                char *e = *(char **)(o + 0x78);
                *(int *)(e + 8) = flag;
                *(int *)(e + 0x18) = scale_game_frames_q(a);
            }
        } while (*p++ >= 0);
    }
}
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002CCF30), where it is exact; names translated to the US level program. */




void blend_moby_animation(MobyAnim *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

void FUN_L15_002cbba0(unsigned char *moby) {
    char *data = *(char **)(moby + 0x78);
    if (moby[0x20] == 1) {
        moby[0x20] = 2;
        if (moby[0x53] != 1) {
            blend_moby_animation(moby, 1, 0, FUN_001f96f8(10));
        }
    }
    if (moby[0x20] == 3) {
        if (*(int *)(data + 8) == 0) {
            *(int *)(data + 0x18) = FUN_001f96f8(0x78);
        }
    }
}
#include "sda.h"

/* per-frame update of the level's looping effect: ramp the gauge, then start, run or stop the draw callback */
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002CCFC0), where it is exact; names translated to the US level program. */

extern char D_0013F350[];
extern float D_0015ED6C MACRO_ADDR;
extern int FUN_0022da68(int, int, int);
extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_L15_002cbac0_u() __asm__("FUN_L15_002cbac0");
extern short D_0015ED84_d __asm__("D_0015ED84") __attribute__((sda));
extern short D_L15_00161AB8_d __asm__("D_L15_00161AB8") __attribute__((sda));
extern short D_L15_00161ABC_d __asm__("D_L15_00161ABC") __attribute__((sda));
extern short D_L15_00161AC0_d __asm__("D_L15_00161AC0") __attribute__((sda));
extern short D_L15_00161AC4_d __asm__("D_L15_00161AC4") __attribute__((sda));
extern short D_L15_00161AC8_d __asm__("D_L15_00161AC8") __attribute__((sda));
extern void FUN_L15_002cbd88_u(void) __asm__("FUN_L15_002cbd88");
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");

void FUN_L15_002cbc30(void *arg) {
    char *base = D_0013F350;
    if (*(int *)(base + 0x2084) == 0x65) {
        approach_value(&D_L15_00161ABC_d, 0.0f, D_0015ED6C * 2);
        FUN_L15_002cbac0_u(arg, 0);
    } else if (*(int *)&D_L15_00161AB8_d != 0
               && (*(int *)&D_0015ED84_d != 0xF || 240.0f < *(float *)(base + 0x84))) {
        approach_value(&D_L15_00161ABC_d, 1.0f, D_0015ED6C * 2);
    } else {
        approach_value(&D_L15_00161ABC_d, 0.0f, D_0015ED6C * 2);
    }
    if (*(float *)&D_L15_00161ABC_d != 0.0f) {
        *(int *)&D_L15_00161AC0_d = 1;
        if (FUN_L00_0028d8c0(*(void **)&D_L15_00161AC8_d, *(int *)&D_L15_00161AC4_d) == 0) {
            *(int *)&D_L15_00161AC4_d = FUN_0022da68(5, 0x11, (int)arg);
            *(void **)&D_L15_00161AC8_d = arg;
        }
        enqueue_callback_list_1_alt(FUN_L15_002cbd88_u, arg);
    } else {
        if (FUN_L00_0028d8c0(*(void **)&D_L15_00161AC8_d, *(int *)&D_L15_00161AC4_d) != 0) {
            release_voice_slot(*(int *)&D_L15_00161AC4_d);
            *(int *)&D_L15_00161AC8_d = 0;
            *(int *)&D_L15_00161AC4_d = -1;
        }
        *(int *)&D_L15_00161AC0_d = 0;
    }
}
