/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"
#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002CD118), where it is exact; names translated to the US level program. */

extern float fast_sin(float) __asm__("func_001F9DE0");
extern f32 ConvertIntegerToFloat(s32) __asm__("func_001FA6C0");
extern int D_L15_0015F5CC MACRO_ADDR;
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern short D_L15_00161ABC_d __asm__("D_L15_00161ABC") __attribute__((sda));
extern short D_L15_00161ACC_d __asm__("D_L15_00161ACC") __attribute__((sda));
extern short D_L15_00161AD0_d __asm__("D_L15_00161AD0") __attribute__((sda));
extern short D_L15_00161AD4_d __asm__("D_L15_00161AD4") __attribute__((sda));
extern signed char D_L15_00161ACF[] MACRO_ADDR;
void emit_rgba_draw_packet(s32 r, s32 g, s32 b, s32 a) __asm__("FUN_001f5210");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L15_002cbd88(void) {
    int n = scale_game_frames(*(int *)&D_L15_00161AD4_d);
    float d = ConvertIntegerToFloat(n);
    float s = fast_sin((float)(D_L15_0015F5CC % n) / d * 6.28318f);
    float v = *(float *)&D_L15_00161ABC_d + *(float *)&D_L15_00161AD0_d * s;
    int r;
    int k;
    if (v < 0.0f) v = 0.0f;
    r = func_001FA898_r((float)D_L15_00161ACF[0] * v);
    k = *(int *)&D_L15_00161ACC_d;
    emit_rgba_draw_packet(k & 0xFF, k >= 9, k >= 17, r);
}
/* Ported from rac1-decomp (PAL, src/overlays/shared/vendor_00298BB8.c: func_L15_002D7B60), where it is exact; names translated to the US level program. */

typedef int u128 __attribute__((mode(TI)));

extern char D_0013F350[];
extern int FUN_001f0b58(void);
extern int FUN_L00_0020d568(void);
f32 probe_ground_height(void *arg0, s32 arg1, f32 arg2) __asm__("FUN_00213508");

int FUN_L15_002d6770(void) {
    char *p;
    float vec[4];
    float h;
    if (FUN_L00_0020d568() != 0) return 1;
    p = D_0013F350;
    if ((unsigned)(*(int *)(p + 0x2084) - 0x18) < 2) {
        *(u128 *)vec = *(u128 *)(p + 0x80);
        vec[2] = vec[2] + 2.0f;
        h = probe_ground_height(vec, 0, 0.5f);
        if (FUN_001f0b58() != 0) return 0;
        if (*(float *)(p + 0x88) <= h) return 1;
    }
    return 0;
}
