/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002efb88.s", FUN_L18_002efb88);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f0030.s", FUN_L18_002f0030);
#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002F1510), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float FUN_001f9af0(void *);
extern float FUN_001f9b20(void *);
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float FUN_001f9e90(float, float);
extern float FUN_001fa580(float, float);
extern float FUN_00213f38_c(float *, float *, float, float, float, float) __asm__("FUN_00213f38");
extern float FUN_L00_0025be00(float *, float *, float, float, float, float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001f9740(int *);
extern short D_L18_00162214_d __asm__("D_L18_00162214") __attribute__((sda));
extern short D_L18_0016222C_d __asm__("D_L18_0016222C") __attribute__((sda));
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9c48(void *, void *, float);

int FUN_L18_002f0120(char *moby, float *vec) {
    float buf[4];
    float v[4];
    char *d = *(char **)(moby + 0x78);
    char *p;
    float yaw;

    FUN_001f9a28(buf, vec, moby + 0x10);
    yaw = FUN_001fa580(FUN_001f9e90(buf[0], buf[1]), *(float *)(d + 0x148));
    FUN_L00_0025be00((float *)(moby + 0x48), (float *)(d + 0x140), yaw,
                      *(float *)(d + 0x150), *(float *)(d + 0x150), *(float *)(d + 0x154));
    *(float *)(moby + 0x10) += FUN_001f9dc8(*(float *)(moby + 0x48)) * (*(float *)&D_L18_00162214_d * D_0015ED6C);
    *(float *)(moby + 0x14) += FUN_001f9de0(*(float *)(moby + 0x48)) * (*(float *)&D_L18_00162214_d * D_0015ED6C);
    FUN_00213f38_c((float *)(moby + 0x18), (float *)(d + 0x144), vec[2], *(float *)(d + 0x158),
                  *(float *)(d + 0x158), *(float *)(d + 0x15C));
    *(float *)(moby + 0x44) = *(float *)&D_L18_0016222C_d * *(float *)(d + 0x144);
    if (FUN_001f9af0(buf) < 2.0f) {
        return 1;
    }
    if (FUN_001f9740((int *)(d + 0x160))) {
        return 1;
    }
    p = *(char **)(d + 0x16C);
    if (p) {
        FUN_001f9a28(v, moby + 0x10, p + 0x10);
        if (!(FUN_001f9b20(v) < 4.5f)) {
            return 0;
        }
        FUN_001f9c48(v, v, random_float_between_alt(15.0f, 20.0f));
        FUN_001f9a10(v, v, *(char **)(d + 0x16C) + 0x10);
        v[2] = vec[2];
        qcopy(vec, v);
    }
    return 0;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002F16D8), where it is exact; names translated to the US level program. */

extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float random_angle_radians(void) __asm__("FUN_00213308");
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001f96f8(int);
extern short D_L18_0016221C_d __asm__("D_L18_0016221C") __attribute__((sda));
extern short D_L18_00162220_d __asm__("D_L18_00162220") __attribute__((sda));
extern short D_L18_00162224_d __asm__("D_L18_00162224") __attribute__((sda));
extern short D_L18_00162228_d __asm__("D_L18_00162228") __attribute__((sda));
extern void FUN_001f9a10(void *, void *, void *);

void FUN_L18_002f02e8(char *moby, void *out) {
    char *data = *(char **)(moby + 0x78);
    float v[3];
    float r = random_float_between_alt(*(float *)&D_L18_00162224_d, *(float *)&D_L18_00162228_d);
    float ang = random_angle_radians();
    v[0] = FUN_001f9dc8(ang) * r;
    v[1] = FUN_001f9de0(ang) * r;
    v[2] = 0.0f;
    v[2] = random_float_between_alt(*(float *)&D_L18_0016221C_d, *(float *)&D_L18_00162220_d);
    FUN_001f9a10(out, v, data + 0x120);
    *(int *)(data + 0x160) = FUN_001f96f8(180);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f0390.s", FUN_L18_002f0390);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f06c0.s", FUN_L18_002f06c0);
#include "qcopy.h"

/* Advance a ring of recorded positions, store the moby's position, and register draw callbacks once per frame. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002F1C38), where it is exact; names translated to the US level program. */

extern int D_L18_0015F5CC;
extern short D_L18_00162230_d __asm__("D_L18_00162230") __attribute__((sda));
extern void FUN_L18_002f0390(void);
extern void FUN_L18_002f06c0(void);
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");

void FUN_L18_002f0848(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int off;
    int cur;
    int old;
    if ((D_L18_0015F5CC & 3) == 0) {
        *(unsigned short *)(data + 0x166) = (*(unsigned short *)(data + 0x166) + 1) & 0xF;
        if ((float)*(short *)(data + 0x164) < 4.0f) {
            *(unsigned short *)(data + 0x164) = *(unsigned short *)(data + 0x164) + 1;
        }
    }
    off = *(short *)(data + 0x166) << 4;
    qcopy((char *)(off + (int)data) + 0x10, moby + 0x10);
    cur = D_L18_0015F5CC;
    old = *(int *)&D_L18_00162230_d;
    *(float *)(data + off + 0x1C) = 1.0f;
    if (cur != old) {
        *(int *)&D_L18_00162230_d = cur;
        enqueue_callback_list_1_alt(FUN_L18_002f0390, moby);
        enqueue_callback_list_1_alt(FUN_L18_002f06c0, moby);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f16f0.s", FUN_L18_002f16f0);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F3038), where it is exact; names translated to the US level program. */

extern void FUN_L18_002f1d08_u(int, int) __asm__("FUN_L18_002f1d08");
extern void FUN_L18_002fa888(int, int);

void FUN_L18_002f1c38(unsigned char *moby) {
    char *state = *(char **)(moby + 0x78);
    if (*(short *)(moby + 0xA6) == 0x565 && moby[0x20] == 1) {
        if (*(int *)(state + 0xC) != -1) {
            FUN_L18_002f1d08_u(0x802, *(int *)(state + 0xC));
            FUN_L18_002f1d08_u(0x908, *(int *)(state + 0xC));
            FUN_L18_002f1d08_u(0x954, *(int *)(state + 0xC));
        }
        moby[0x20] = 2;
        FUN_L18_002fa888(moby[0x21], 1);
    }
}
/* Reset this vendor moby's counters before its per-frame update. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F30C8), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x20];
    unsigned char state;
    char pad21[0x57];
    struct L18VD_1cc8 *data;
    char pad7C[0x2A];
    short class_id;
} L18VM_1cc8;

typedef struct L18VD_1cc8 {
    char pad0[0x30];
    char update_data[0x300];
    int field330;
    char pad334[4];
    int field338;
    char pad33C[8];
    int field344;
} L18VD_1cc8;

extern void FUN_L12_0027b370(L18VM_1cc8 *, void *, int);

void FUN_L18_002f1cc8(L18VM_1cc8 *moby) {
    L18VD_1cc8 *data = moby->data;
    if (moby->class_id == 0x565) {
        moby->state = 1;
        data->field330 = 0;
        data->field344 = 0;
    }
    FUN_L12_0027b370(moby, data->update_data, data->field338);
}
/* For each entry of block D_L18_001C6480[D_L18_001C6780[A]]: runs func_001F9BF0 /
   func_001F9EC0 against the records at D_L18_0016016C + B * 0x80 (+0x30, +0x40)
   for the entry's vector and, when both of the result's first two components are
   within 1.0, clears the entry's +0x0C and sets its +0x14 to 1.0. The index is
   copied (k = i) for the two stores and the loop tests `n > i`, as decomp-permuter
   found for retail's register use. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F3108), where it is exact; names translated to the US level program. */

typedef struct { int pad[3]; int w0c; int pad2; float w14; int pad3[2]; } Ent;

typedef struct { char pad[0x26]; short n; Ent *e; } Blk;

extern char *D_L18_001600EC;
extern char *D_L18_001C6200[];
extern unsigned char D_L18_001C6500[];
extern void FUN_001f9cf8(void *, void *, void *);
float AbsoluteFloat(float input) __asm__("func_001F99C0");

void FUN_L18_002f1d08(int a, int b) {
    int i = 0;
    int k;
    if (((Blk *)D_L18_001C6200[D_L18_001C6500[a]])->n > i) do {
        float v[4];
        FUN_001f9a28(v, ((Blk *)D_L18_001C6200[D_L18_001C6500[a]])->e + i, D_L18_001600EC + (b << 7) + 0x30);
        FUN_001f9cf8(v, v, D_L18_001600EC + (b << 7) + 0x40);
        k = i;
        if (AbsoluteFloat(v[0]) < 1.0f && AbsoluteFloat(v[1]) < 1.0f) {
            ((Blk *)D_L18_001C6200[D_L18_001C6500[a]])->e[k].w0c = 0;
            ((Blk *)D_L18_001C6200[D_L18_001C6500[a]])->e[k].w14 = 1.0f;
        }
    } while (++i < ((Blk *)D_L18_001C6200[D_L18_001C6500[a]])->n);
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F3268), where it is exact; names translated to the US level program. */

extern char D_0013E550[];
extern f32 approach_value(f32 *, f32, f32) __asm__("FUN_00213ed8");
extern int FUN_0022da68(int, int, int);
extern int FUN_L00_0028d8c0(void *, int);
extern unsigned char *D_L18_0015FFD8;
extern void FUN_L18_002f1fd8(void);
extern void release_voice_slot(s32) __asm__("FUN_0022d798");

void FUN_L18_002f1e68(unsigned char *m)
{
    int *d = *(int **)(m + 0x78);
    switch (m[0x20]) {
    case 0:
        m[0x20] = 1;
        ((float *)d)[3] = 1.0f;
        break;
    case 1:
        enqueue_callback_list_1_alt(FUN_L18_002f1fd8, m);
        if (FUN_L00_0028d8c0(m, d[1]) == 0) {
            d[1] = FUN_0022da68(0, 4, (int)m);
        }
        if (d[0] != -1) {
            unsigned char *o = D_L18_0015FFD8 + (d[0] << 8);
            if (*(short *)(o + 0xA6) == 0x267 && o[0x20] >= 3) {
                *(int *)(m + 0x94) = 0;
                m[0x20] = 2;
                if (FUN_L00_0028d8c0(m, d[1]) != 0) {
                    int i = d[1];
                    if (i != -1) {
                        char *e = D_0013E550 + i * 0x70;
                        if (*(unsigned char **)(e + 0x88) == m && *(unsigned char *)(e + 0x74) != 0) {
                            release_voice_slot(i);
                        }
                    }
                    d[1] = -1;
                }
            }
        }
        break;
    case 2:
        approach_value((float *)(d + 3), 0.0f, D_0015ED6C + D_0015ED6C);
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f1fd8.s", FUN_L18_002f1fd8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f2310.s", FUN_L18_002f2310);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F39F8), where it is exact; names translated to the US level program. */

typedef struct { int pad[7]; int idx; } Lx;

typedef struct { char pad[0x18]; float f; char pad1[0x78 - 0x1C]; Lx *l; char pad2[0xA6 - 0x7C]; short kind; char pad3[0x100 - 0xA8]; } Mx;

typedef struct { int pad[2]; float f; char pad2[0x1190 - 12]; } E;

extern E D_L18_001DB500[];
extern short *D_L18_001AC240_c[] __asm__("D_L18_001AC240");
extern unsigned char *D_L18_0015FFD8;

void FUN_L18_002f2598(void *a)
{
    unsigned char *s = a;
    short *p = D_L18_001AC240_c[s[0x21]];
    E *e = D_L18_001DB500;
    do {
        Mx *m = (Mx *)(((*(unsigned short *)p & 0x7FFF) << 8) + (int)D_L18_0015FFD8);
        m->f = *(float *)(s + 0x18);
        if (m->kind == 0x57A) {
            e[m->l->idx].f = *(float *)(s + 0x18);
        }
    } while (*p++ >= 0);
}
#include "qcopy.h"

/* Draws 25 textured quads from the L18 tables, in the moby's frame. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F3A80), where it is exact; names translated to the US level program. */

typedef float FVec4[4] __attribute__((aligned(16)));
typedef struct {
    FVec4 v;
} FRow;
extern short D_L18_00162310 __attribute__((sda));
extern short D_L18_00162314 __attribute__((sda));
extern short D_L18_00162318 __attribute__((sda));
extern short D_L18_0016231C __attribute__((sda));
extern short D_L18_00162320 __attribute__((sda));
extern short D_L18_00162324 __attribute__((sda));
extern short D_L18_00162328 __attribute__((sda));
extern short D_L18_00162308 __attribute__((sda));
extern float D_L18_001DA7A0[][2] __attribute__((section(".data")));
extern FRow D_L18_001DA3C0[] __attribute__((section(".data")));
extern short D_L18_001DA610[][4][2] __attribute__((section(".data")));
extern int get_effect_texture_alt(int) __asm__("FUN_001f44b8");
extern void FUN_001f9fc8(void *);
extern void FUN_001f7d30(void *, void *, int);

void FUN_L18_002f2620(char *moby) {
    FRow m[4];
    int colors[4];
    float uv[4][2];
    unsigned long pkt[4];
    float mat[4][4];
    char *data = *(char **)(moby + 0x78);
    int i;
    int j;

    pkt[1] = get_effect_texture_alt((*(int *)&D_L18_00162324));
    pkt[3] = (*(int *)&D_L18_00162310) | (long)(*(int *)&D_L18_00162314) << 2;
    pkt[3] |= (long)(*(int *)&D_L18_00162318) << 4;
    pkt[3] |= (long)(*(int *)&D_L18_0016231C) << 6;
    pkt[3] |= (long)(*(int *)&D_L18_00162320) << 32;
    pkt[2] = 0xFF9000000260;
    pkt[0] = 0;
    FUN_001f9fc8(mat);
    mat[3][2] = *(float *)(moby + 0x18) - *(float *)data;
    colors[3] = (*(int *)&D_L18_00162328);
    colors[2] = (*(int *)&D_L18_00162328);
    colors[1] = (*(int *)&D_L18_00162328);
    colors[0] = (*(int *)&D_L18_00162328);
    for (i = 0; i < 25; i++) {
        float ofs = *(float *)&D_L18_00162308;
        for (j = 0; j < 4; j++) {
            int a = D_L18_001DA610[i][j][0];
            int b = D_L18_001DA610[i][j][1];
            qcopy(&m[j], &D_L18_001DA3C0[a]);
            uv[j][0] = D_L18_001DA7A0[b][0] + ofs;
            uv[j][1] = D_L18_001DA7A0[b][1];
        }
        FUN_001f7d30(m, mat, 0);
    }
}
typedef float FVec4_l18[4] __attribute__((aligned(16)));

typedef struct {
    FVec4_l18 v;
} FRow_l18;

extern float D_L18_001DAE80[][2] __attribute__((section(".data")));
extern FRow_l18 D_L18_001DA8D0[] __attribute__((section(".data")));
extern short D_L18_001DAC20[][4][2] __attribute__((section(".data")));
extern int get_effect_texture_l18(int) __asm__("FUN_001f44b8");

void FUN_L18_002f27c8(char *moby) {
    FRow_l18 m[4];
    int colors[4];
    float uv[4][2];
    unsigned long pkt[4];
    float mat[4][4];
    char *data = *(char **)(moby + 0x78);
    int i;
    int j;

    pkt[1] = get_effect_texture_l18((*(int *)&D_L18_00162324));
    pkt[3] = (*(int *)&D_L18_00162310) | (long)(*(int *)&D_L18_00162314) << 2;
    pkt[3] |= (long)(*(int *)&D_L18_00162318) << 4;
    pkt[3] |= (long)(*(int *)&D_L18_0016231C) << 6;
    pkt[3] |= (long)(*(int *)&D_L18_00162320) << 32;
    pkt[2] = 0xFF9000000260;
    pkt[0] = 0;
    FUN_001f9fc8(mat);
    mat[3][2] = *(float *)(moby + 0x18) - *(float *)data;
    colors[3] = (*(int *)&D_L18_00162328);
    colors[2] = (*(int *)&D_L18_00162328);
    colors[1] = (*(int *)&D_L18_00162328);
    colors[0] = (*(int *)&D_L18_00162328);
    for (i = 0; i < 38; i++) {
        float ofs = *(float *)&D_L18_00162308;
        for (j = 0; j < 4; j++) {
            int a = D_L18_001DAC20[i][j][0];
            int b = D_L18_001DAC20[i][j][1];

            qcopy(&m[j], &D_L18_001DA8D0[a]);
            uv[j][0] = D_L18_001DAE80[b][0] + ofs;
            uv[j][1] = D_L18_001DAE80[b][1];
        }
        FUN_001f7d30(m, mat, 0);
    }
}
#include "qcopy.h"

/* Draws 22 textured quads from the L18 tables, in the moby's frame. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F3DD0), where it is exact; names translated to the US level program. */



extern float D_L18_001DB3A0[][2] __attribute__((section(".data")));
extern FRow_l18 D_L18_001DB030[] __attribute__((section(".data")));
extern short D_L18_001DB240[][4][2] __attribute__((section(".data")));
extern int get_effect_texture_l18(int) __asm__("FUN_001f44b8");
extern short D_L18_00162310 __attribute__((sda));
extern short D_L18_00162314 __attribute__((sda));
extern short D_L18_00162318 __attribute__((sda));
extern short D_L18_0016231C __attribute__((sda));
extern short D_L18_00162320 __attribute__((sda));
extern short D_L18_00162324 __attribute__((sda));
extern short D_L18_00162328 __attribute__((sda));
extern short D_L18_00162308 __attribute__((sda));
extern void FUN_001f9fc8(void *);
extern void FUN_001f7d30(void *, void *, int);

void FUN_L18_002f2970(char *moby) {
    FRow_l18 m[4];
    int colors[4];
    float uv[4][2];
    unsigned long pkt[4];
    float mat[4][4];
    char *data = *(char **)(moby + 0x78);
    int i;
    int j;

    pkt[1] = get_effect_texture_l18((*(int *)&D_L18_00162324));
    pkt[3] = (*(int *)&D_L18_00162310) | (long)(*(int *)&D_L18_00162314) << 2;
    pkt[3] |= (long)(*(int *)&D_L18_00162318) << 4;
    pkt[3] |= (long)(*(int *)&D_L18_0016231C) << 6;
    pkt[3] |= (long)(*(int *)&D_L18_00162320) << 32;
    pkt[2] = 0xFF9000000260;
    pkt[0] = 0;
    FUN_001f9fc8(mat);
    mat[3][2] = *(float *)(moby + 0x18) - *(float *)data;
    colors[3] = (*(int *)&D_L18_00162328);
    colors[2] = (*(int *)&D_L18_00162328);
    colors[1] = (*(int *)&D_L18_00162328);
    colors[0] = (*(int *)&D_L18_00162328);
    for (i = 0; i < 22; i++) {
        float ofs = *(float *)&D_L18_00162308;
        for (j = 0; j < 4; j++) {
            int a = D_L18_001DB240[i][j][0];
            int b = D_L18_001DB240[i][j][1];
            qcopy(&m[j], &D_L18_001DB030[a]);
            uv[j][0] = D_L18_001DB3A0[b][0] + ofs;
            uv[j][1] = D_L18_001DB3A0[b][1];
        }
        FUN_001f7d30(m, mat, 0);
    }
}
typedef struct {
    char pad0[0x44];
    short count;
    char pad46[0x132];
    char *mobys[1];
} ML;

extern ML D_L18_0016D260;
extern int D_L18_0015F5C4;
extern unsigned char D_0015EDB0;
extern unsigned char D_L18_0017CE40[];
extern short D_L18_001623A4 __attribute__((sda));
extern void attach_manipulator(void *arg0, s32 arg1, void *arg2) __asm__("FUN_0020cb10");

void FUN_L18_002f2b18(char *moby) {
    int i;

    if (D_L18_0015F5C4 == 2 && D_0015EDB0 != 0) {
        for (i = 0; i < D_L18_0016D260.count; i++) {
            char *e = D_L18_0016D260.mobys[i];

            if (*(short *)(e + 0xA6) == 0x4E1) {
                unsigned char *s = D_L18_0017CE40;

                if (s[1] == 0) {
                    attach_manipulator(e, 0, s);
                    *(float *)(s + 0x20) = *(float *)&D_L18_001623A4;
                    *(float *)(s + 0x24) = *(float *)&D_L18_001623A4;
                    *(float *)(s + 0x28) = *(float *)&D_L18_001623A4;
                }
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f2bf0.s", FUN_L18_002f2bf0);
/* Latches the target from the global block once, and counts a class 0x24B hit. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F7278), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern short D_L18_001623A8_d __asm__("D_L18_001623A8") __attribute__((sda));

void FUN_L18_002f5e18(char *moby) {
    char *d = *(char **)(moby + 0x78);
    if (*(int *)(d + 0x3E4) == 0) {
        char *a = D_0013E533 + 0xE1D;
        if (*(int *)(a + 0x300) != 0) {
            *(int *)(d + 0x3E8) = *(int *)(a + 0x2FC);
        }
        if (*(int *)(a + 0x2084) == 0x77) {
            char *t = *(char **)(d + 0x3E8);
            *(int *)(d + 0x3E4) = 1;
            if (t != 0) {
                if (*(short *)(t + 0xA6) == 0x24B) {
                    *(int *)&D_L18_001623A8_d = *(int *)&D_L18_001623A8_d + 1;
                }
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f5e80.s", FUN_L18_002f5e80);
/* steps a moby's offset vector toward a target, returns whether both settled */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F7CD8), where it is exact; names translated to the US level program. */

extern float D_0015ED70;
extern float FUN_001f9af0(void *);
extern float FUN_00213f38(float, float, float, float, float *, float *);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);

int FUN_L18_002f6878(char *moby, float arg, void *x) {
    char *data = *(char **)(moby + 0x78);
    char *p = data + 0x3C0;
    float a[4];
    float b[4];
    float v = 0.0f;
    float len;
    float s;
    b[0] = v;
    FUN_001f9a28(a, x, p);
    a[2] = v;
    len = FUN_001f9af0(a);
    s = D_0015ED70 * 10.0f;
    FUN_00213f38(len, s, s, arg, b, (float *)(data + 0x374));
    FUN_001f9bf8(a, a, *(float *)(data + 0x374));
    FUN_001f9a10(p, p, a);
    if (len < 0.1f) {
        if (*(float *)(data + 0x374) < 0.1f) {
            return 1;
        }
        return 0;
    }
    return 0;
}
#include "sda.h"

/* Moves a moby's follow distance toward a target, clamped to a range, then applies it. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F7DC0), where it is exact; names translated to the US level program. */

extern char *D_L18_0016016C __asm__("D_L18_001600EC") MACRO_ADDR;
extern char D_0013E633[] __asm__("D_0013F3D0");
extern float D_0015EE6C __asm__("D_0015ED6C") MACRO_ADDR;
extern float FUN_001f9b80(void *, void *);
extern short D_L18_001623DC __asm__("D_L18_0016234C") __attribute__((sda));
extern short D_L18_00162408 __asm__("D_L18_00162378") __attribute__((sda));
extern short D_L18_0016240C __asm__("D_L18_0016237C") __attribute__((sda));
extern void FUN_L00_0025f730(void *a, float x);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
int FUN_L18_002f6878_c(char *moby, float arg, void *x) __asm__("FUN_L18_002f6878");

void FUN_L18_002f6960(char *m) {
    float v[4];
    char *d = *(char **)(m + 0x78);
    char *b = D_0013E633 + 0x0;
    float t;
    float lo, hi;
    subtract_vector_xyz(v, b, D_L18_0016016C + (*(int *)(d + 0x344) << 7) + 0x30);
    v[2] = 0.0f;
    if (*(int *)(b + 0x200C) == 0xF) {
        FUN_L00_0025f730(v, *(float *)&D_L18_0016240C);
    } else {
        FUN_L00_0025f730(v, *(float *)&D_L18_00162408);
    }
    add_vector_xyz(v, v, D_L18_0016016C + (*(int *)(d + 0x344) << 7) + 0x30);
    t = *(float *)(D_0013E633 + 0xE0);
    t += (FUN_001f9b80(m + 0x10, v) - *(float *)&D_L18_001623DC) / *(float *)&D_L18_001623DC * (D_0015EE6C * 4.75f);
    hi = D_0015EE6C * 20.0f;
    lo = D_0015EE6C * 4.75f;
    if (t > hi) {
        t = hi;
    } else if (t < lo) {
        t = lo;
    }
    FUN_L18_002f6878_c(m, t, v);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f6aa0.s", FUN_L18_002f6aa0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f6e10.s", FUN_L18_002f6e10);
extern int D_L18_001AC240[];
extern int D_L18_0015FFD8_d __asm__("D_L18_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f6fa8, 124 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
void FUN_L18_002f6fa8(int unused, int idx)
{
    short *p = D_L18_001AC240[idx];
    if (p != 0) {
        do {
            unsigned char *m = D_L18_0015FFD8_d + ((*(unsigned short *)p & 0x7FFF) << 8);
            if (m != 0 && m[0x20] != 0xFE && m[0x20] != 0xFD) {
                unsigned short flags = *(unsigned short *)(m + 0x34);
                *(int *)(m + 0x94) = 0;
                flags |= 1;
                m[0x31] = 0;
                *(unsigned short *)(m + 0x34) = flags;
            }
        } while (*p++ >= 0);
    }
}

extern int D_L18_001AC240[];
extern int D_L18_0015FFD8_d __asm__("D_L18_0015FFD8") __attribute__((section(".sdata")));
/* 0x002f7028, 140 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
// Walks a list of moby indices and resets the flags of each live moby.
void FUN_L18_002f7028(int a0, int idx) {
    short *p = D_L18_001AC240[idx];
    if (p != 0) {
        do {
            unsigned char *m = D_L18_0015FFD8_d + ((*(unsigned short *)p & 0x7FFF) << 8);
            if (m != 0 && m[0x20] != 0xFE && m[0x20] != 0xFD) {
                m[0x31] = 1;
                *(unsigned short *)(m + 0x34) &= 0xFFFE;
                *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
            }
        } while (*p++ >= 0);
    }
}

/* Picks a new state for the moby at random among the allowed transitions, retrying up to 100 times until one is accepted. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F8518), where it is exact; names translated to the US level program. */

extern char *D_L18_001600EC;
extern float FUN_001f9b80(void *, void *);
extern short D_L18_00162378_d __asm__("D_L18_00162378") __attribute__((sda));
extern short D_L18_001DFB40[];
s32 random_integer_below(s32 arg0) __asm__("FUN_00213260");

int FUN_L18_002f70b8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int state = *(int *)(data + 0x350);
    int tries = 0;
    int r;
    int ok;
    do {
        r = random_integer_below(6);
        switch (r) {
        case 0: state = 0xD; break;
        case 1: state = 0xE; break;
        case 2: state = 0xF; break;
        case 3: state = 0x10; break;
        case 4: state = 0x11; break;
        case 5: state = 0x13; break;
        }
        ok = *(short *)((char *)D_L18_001DFB40 + r * 2 + *(int *)(data + 0x34C) * 12);
        if (state == *(int *)(data + 0x350)) ok = 0;
        if (state == 0x13) {
            if (*(int *)(data + 0x364) != 0) {
                ok = 0;
            } else {
                float d = FUN_001f9b80(D_0013E533 + 0xE9D, D_L18_001600EC + *(int *)(data + 0x25C) * 128 + 0x30);
                if (*(float *)&D_L18_00162378_d + 2.0f < d) ok = 0;
            }
        }
        if (state == 0x11) {
            if (*(int *)(data + 0x350) == 0xE) ok = 0;
        }
        if (ok != 0) break;
        tries++;
    } while (tries < 100);
    return state;
}
typedef unsigned int u128_f7220 __attribute__((mode(TI)));
extern float FastSubRots(float, float) __asm__("FUN_001fa5c8");

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F8680), where it is exact; names translated to the US level program. */

typedef union { u128_f7220 quad; float f[4]; } L18Vector;

extern float FUN_001f9e90(float, float);

void FUN_L18_002f7220(char *source, char *dest, L18Vector *from, L18Vector *to) {
    L18Vector a, b;
    a.quad = from->quad;
    b.quad = to->quad;
    *(float *)(dest + 0x68) = FastSubRots(FUN_001f9e90(b.f[0] - a.f[0], b.f[1] - a.f[1]), *(float *)(source + 0x48));
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f7288.s", FUN_L18_002f7288);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f76a0.s", FUN_L18_002f76a0);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F8CE0), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x3A0];
    void *p3A0;
    char pad3A4[0x14];
    int p3B8;
} L18Q;

extern f32 ConvertIntegerToFloat(s32) __asm__("FUN_001fa6c0");
extern int FUN_001fa6e0(int, int, float);
extern short D_L18_00162450_d __asm__("D_L18_00162450") __attribute__((sda));
extern short D_L18_00162454_d __asm__("D_L18_00162454") __attribute__((sda));
extern short D_L18_00162458_d __asm__("D_L18_00162458") __attribute__((sda));
extern short D_L18_0016245C_d __asm__("D_L18_0016245C") __attribute__((sda));
extern short D_L18_00162460_d __asm__("D_L18_00162460") __attribute__((sda));
extern short D_L18_00162464_d __asm__("D_L18_00162464") __attribute__((sda));
extern short D_L18_00162468_d __asm__("D_L18_00162468") __attribute__((sda));
extern short D_L18_0016246C_d __asm__("D_L18_0016246C") __attribute__((sda));
extern short D_L18_00162470_d __asm__("D_L18_00162470") __attribute__((sda));
extern short D_L18_00162474_d __asm__("D_L18_00162474") __attribute__((sda));
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_00263618(void *, int, float, float);

void FUN_L18_002f7880(char *moby) {
    char a[16];
    char b[16];
    L18Q *q = *(L18Q **)(moby + 0x78);
    int n = FUN_001f96f8(*(int*)&D_L18_00162460_d);
    float f = ConvertIntegerToFloat(D_L18_0015F5CC % n);
    int h;
    int i;
    f = f / ConvertIntegerToFloat(n);
    f = f * 6.18318f;
    f = FUN_001f9de0(f - 3.14159f);
    h = FUN_001fa6e0(*(int*)&D_L18_00162458_d, *(int*)&D_L18_0016245C_d, f * 0.5f + 0.5f);
    FUN_L00_0024f7c8(q->p3A0, 1, a);
    FUN_L00_00263618(a, h, *(float*)&D_L18_00162450_d, *(float*)&D_L18_00162454_d);
    FUN_L00_0024f7c8(q->p3A0, 2, a);
    FUN_L00_00263618(a, h, *(float*)&D_L18_00162450_d, *(float*)&D_L18_00162454_d);
    if ((unsigned)(*(unsigned char *)(moby + 0x53) - 11) < 3) {
        int n2 = FUN_001f96f8(*(int*)&D_L18_00162474_d);
        float g = ConvertIntegerToFloat(D_L18_0015F5CC % n2);
        int h2;
        g = g / ConvertIntegerToFloat(n2);
        g = g * 6.18318f;
        g = FUN_001f9de0(g - 3.14159f);
        h2 = FUN_001fa6e0(*(int*)&D_L18_0016246C_d, *(int*)&D_L18_00162470_d, g * 0.5f + 0.5f);
        FUN_L00_0024f7c8(moby, 5, b);
        FUN_L00_00263618(b, h2, *(float*)&D_L18_00162464_d, *(float*)&D_L18_00162468_d);
        FUN_L00_0024f7c8(moby, 6, b);
        FUN_L00_00263618(b, h2, *(float*)&D_L18_00162464_d, *(float*)&D_L18_00162468_d);
    }
    for (i = 0; i < 8; i++) {
        FUN_L00_0024f7c8(moby, 11 + i, a);
        FUN_L00_00263618(a, q->p3B8, 0.7f, 0.5f);
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Activate the vendor moby and set its initial flags. */
/* Ported from rac1-decomp (PAL, src/overlays/l18/vendor_002F2AE0.c: func_L18_002F8F10), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x20];
    unsigned char state;
    char pad21[0x10];
    unsigned char substate;
    char pad32[2];
    unsigned short flags;
} Level18VendorMobyShort;

void FUN_L18_002f7ab0(Level18VendorMobyShort *moby) {
    if (moby->state == 0) {
        moby->state = 1;
        moby->flags |= 3;
        moby->substate = 0;
    }
}
#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002F2AE0.c: func_L18_002F8F38), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x18];
    float f18;
    char pad1C[4];
    unsigned char state;
    char pad21[0x10];
    unsigned char substate;
    char pad32[2];
    unsigned short flags;
    char pad36[0x0A];
    float f40;
} M;

extern f32 fast_add_rotations(f32 a, f32 b) __asm__("FUN_001fa580");
extern int D_L18_0015F5C4 MACRO_ADDR;
extern int D_L18_0015F5CC MACRO_ADDR;
extern int D_L18_001623A0 MACRO_ADDR;
extern int D_L18_0016D290_d __asm__("D_L18_0016D290") __attribute__((section(".data")));

void FUN_L18_002f7ad8(M *moby) {
    switch (moby->state) {
    case 0:
        moby->state = 1;
    case 1:
        if ((D_L18_0015F5C4 == 2 && D_L18_0016D290_d == 3) ||
            (D_L18_0015F5CC < 5 && D_L18_001623A0 != 0 && moby->f40 == 0.0f)) {
            moby->state = 2;
            moby->flags |= 1;
            moby->substate = 0;
        }
        break;
    case 2:
        if (D_L18_001623A0 != 0 && moby->f40 == 0.0f) {
            float d = 101.6f - moby->f18;
            moby->f40 = fast_add_rotations(moby->f40, 3.14159274f);
            moby->f18 += d + d;
        }
        if (D_L18_0015F5C4 != 2) {
            moby->substate = 1;
            moby->state = 1;
            moby->flags &= 0xFFFE;
        }
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f7c40.s", FUN_L18_002f7c40);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f8050.s", FUN_L18_002f8050);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002f8658.s", FUN_L18_002f8658);
