/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

/* Switch to state four while active, then restore the saved state. */
/* Ported from rac1-decomp (PAL, src/overlays/l18/vendor_002A8400.c: func_L18_002D7580), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x20];
    unsigned char state;
    char pad21[0x9B];
    unsigned char saved_state;
} Level18VendorMoby;

extern int FUN_L00_002dbb20(Level18VendorMoby *);

int FUN_L18_002d6190(Level18VendorMoby *moby) {
    int active = FUN_L00_002dbb20(moby);
    if (active != 0) {
        moby->state = 4;
    } else if (moby->state == 4) {
        moby->state = moby->saved_state;
    }
    return active;
}
extern int scale_ticks(int) __asm__("FUN_001f96f8");

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D7670), where it is exact; names translated to the US level program. */

typedef struct {
    char _pad00[0x10];
    unsigned char nframes; /* 0x10 */
} AnimSeq;

typedef struct {
    char _pad00[0x48];
    AnimSeq *seqs[1]; /* 0x48 */
} AnimClass;

typedef struct {
    char _pad00[0x24];
    AnimClass *pClass;       /* 0x24 */
    char _pad28[0x50 - 0x28];
    unsigned char frame;     /* 0x50 */
    unsigned char nextFrame; /* 0x51 */
    unsigned char seq;       /* 0x52 */
    unsigned char prevSeq;   /* 0x53 */
    char _pad54[0x5C - 0x54];
    float unk5C;             /* 0x5C */
    char _pad60[0x68 - 0x60];
    float *frameData;        /* 0x68 */
    char _pad6C[4];
    unsigned char unk70;     /* 0x70 */
} MobyAnim;

void blend_moby_animation(MobyAnim *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

void FUN_L18_002d6280(unsigned char *arg) {
    unsigned short flags;
    arg[0x20] = 5;
    if (arg[0x53] != 0) {
        blend_moby_animation(arg, 0, 0, scale_ticks(10));
    }
    flags = *(unsigned short *)(arg + 0x34);
    arg[0x31] = 0;
    flags |= 1;
    *(int *)(arg + 0x94) = 0;
    flags &= 0xEFFF;
    *(unsigned short *)(arg + 0x34) = flags;
}
extern int D_L18_001AC240[];
extern short D_L18_0015FFD8_d __asm__("D_L18_0015FFD8") __attribute__((section(".sdata")));
/* 0x002d6d50, 108 bytes.
 * Ported from rac1-decomp (PAL), where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
// Sets the data fields 0x30 and 0x24 of each listed moby whose class is 0x247.
void FUN_L18_002d6d50(int idx) {
    short *p = (short *)D_L18_001AC240[idx];
    if (p != 0) {
        char *base = *(char **)&D_L18_0015FFD8_d;
        do {
            int off = (*p & 0x7FFF) << 8;
            char *moby = (char *)off + (int)base;
            if (*(short *)(moby + 0xA6) == 0x247) {
                char *data = *(char **)(moby + 0x78);
                *(int *)(data + 0x30) = 1;
                *(float *)(data + 0x24) = 1.5f;
            }
        } while (*p++ >= 0);
    }
}

/* Initialize the vendor action mode and scale. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D81B0), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x24];
    float scale;
    char pad28[4];
    int mode;
} Level18VendorActionData;

typedef struct {
    char pad0[0x78];
    Level18VendorActionData *data;
} Level18VendorActionMoby;

void FUN_L18_002d6dc0(Level18VendorActionMoby *moby) {
    Level18VendorActionData *data = moby->data;
    data->mode = 5;
    data->scale = 1.5f;
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D9358), where it is exact; names translated to the US level program. */

extern int FUN_L00_0028d8c0(void *, int);
s32 allocate_voice_for_group_entry(s32 arg0, s32 arg1, s32 arg2) __asm__("FUN_0022dba0");

void FUN_L18_002d7f68(unsigned char *arg, int value) {
    char *data = *(char **)(arg + 0x78);
    if (arg[0x20] != 2) {
        arg[0x20] = 2;
        *(int *)(data + 0x6C) = value;
    }
    if (!FUN_L00_0028d8c0(arg, *(int *)(data + 0x70))) {
        *(int *)(data + 0x70) = allocate_voice_for_group_entry(0x12, 0, arg);
    }
}
/* turns the moby's heading toward a target, clamped per state, and updates its hover offset */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D9B00), where it is exact; names translated to the US level program. */

extern float D_0015ED6C;
extern float FUN_001f9de0(float);
extern float FUN_001fa580(float, float);
extern short D_L18_00161A48_d __asm__("D_L18_00161A48") __attribute__((sda));
extern short D_L18_00161A4C_d __asm__("D_L18_00161A4C") __attribute__((sda));

void FUN_L18_002d8710(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v = FUN_001fa580(*(float *)(moby + 0x44), *(float *)(data + 0x6C));
    *(float *)(moby + 0x44) = v;
    if (((unsigned char *)moby)[0x20] == 5) {
        if (v > 0.5235988f) {
            *(float *)(moby + 0x44) = 0.5235988f;
        } else if (v < -0.5235988f) {
            *(float *)(moby + 0x44) = -0.5235988f;
        }
    } else if (((unsigned char *)moby)[0x20] == 4) {
        if (v > 0.08726646f) {
            *(float *)(moby + 0x44) = 0.08726646f;
        } else if (v < -0.08726646f) {
            *(float *)(moby + 0x44) = -0.08726646f;
        }
    } else {
        if (v > 0.034906585f) {
            *(float *)(moby + 0x44) = 0.034906585f;
        } else if (v < -0.034906585f) {
            *(float *)(moby + 0x44) = -0.034906585f;
        }
    }
    *(float *)(data + 0x74) = FUN_001fa580(*(float *)(data + 0x74), *(float *)&D_L18_00161A4C_d * 0.017453292f * D_0015ED6C);
    *(float *)(moby + 0x18) = *(float *)(data + 0x64) + *(float *)&D_L18_00161A48_d * FUN_001f9de0(*(float *)(data + 0x74));
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (PAL, src/overlays/l18/vendor_002A8400.c: func_L18_002D9C48), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x20];
    unsigned char state;
} Level18State;

int FUN_L18_002d8858(Level18State *obj) {
    if (obj->state == 1) {
        return 1;
    }
    if (obj->state == 2) {
        obj->state = 5;
    }
    return 0;
}
/* UpdateMoby_628 */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DD650), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern float FUN_001f9b80(void *, void *);
extern int D_L18_0015F5CC;
extern int FUN_001f9740(int *);
extern short D_L18_00161CA0_d __asm__("D_L18_00161CA0") __attribute__((sda));
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);
extern void FUN_L00_00259888(char *arg, int a, int b, void *src, float scale);
extern void FUN_L00_002598b0(int, float, void *, int, float, float, int, int, int);
extern void FUN_L00_00259a88(int, void *);
extern void FUN_L18_002dc4b8(void);
extern void enqueue_callback_list_1_alt(void (*)(void), void *) __asm__("FUN_001f4600");
void mark_moby_for_removal(struct Obj *obj) __asm__("FUN_0020c828");

void FUN_L18_002dc260(char *moby) {
    char buf[0x30];
    float v[4];
    float *d = *(float **)(moby + 0x78);
    char *tgt;
    char *pos;
    int flag;

    if (FUN_001f9740((int *)(d + 2))) {
        mark_moby_for_removal(moby);
        return;
    }
    pos = moby + 0x10;
    tgt = D_0013E533 + 0xE9D;
    if (FUN_001f9b80(pos, tgt) < d[0] + 0.5f) {
        FUN_001f9a28(v, tgt, pos);
        v[2] = 0.0f;
        FUN_001f9bf8(v, v, D_0015ED6C * 4.0f);
        v[2] = D_0015ED6C * 4.0f;
        FUN_L00_00259888(buf, (int)moby, 0x10001, v, 1.0f);
        FUN_L00_00259a88(*(int *)(tgt + 0x2000), buf);
    }
    flag = D_L18_0015F5CC & 4;
    d[1] = d[1] + *(float *)&D_L18_00161CA0_d * D_0015ED6C;
    if (flag == 0) {
        FUN_L00_002598b0(*(int *)(d + 3), d[0], pos, 0x10000, 1.0f, 1.0f, 0, 1, 0);
    }
    enqueue_callback_list_1_alt(FUN_L18_002dc4b8, moby);
}
#include "qcopy.h"
extern void *CreateMoby() __asm__("FUN_0020c4f8");

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DD7D0), where it is exact; names translated to the US level program. */

char *FUN_L18_002dc3e0(void *owner, void *vector, float value) {
    char *moby = CreateMoby(0x274);
    if (moby != 0) {
        char *data = *(char **)(moby + 0x78);
        ((unsigned char *)moby)[0x30] = 0xFF;
        qcopy(moby + 0x10, vector);
        *(float *)data = value;
        *(int *)(data + 0x08) = 3;
        *(void **)(data + 0x0C) = owner;
    }
    return moby;
}
#define NOT_SDA

#define MACRO_ADDR

/* Read the vendor moby's current float value. */
/* Ported from rac1-decomp (PAL, src/overlays/l18/vendor_002A8400.c: func_L18_002E0F80), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x60];
    float value;
} Level18VendorFloatData;

typedef struct {
    char pad0[0x78];
    Level18VendorFloatData *data;
} Level18VendorFloatMoby;

float FUN_L18_002dfb90(Level18VendorFloatMoby *moby) {
    return moby->data->value;
}
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002E36B0), where it is exact; names translated to the US level program. */

extern void func_001FA1F8(void *, void *) __asm__("FUN_001fa030");

char *FUN_L18_002e22c0(void *vector) {
    char *moby = CreateMoby(0x326);
    if (moby != 0) {
        char *data = *(char **)(moby + 0x78);
        moby[0x30] = 0x40;
        moby[0x20] = 0;
        *(char **)(data + 0x0C) = moby;
        *(int *)(moby + 0x94) = 0;
        *(unsigned short *)(moby + 0x34) |= 0x41;
        qcopy(moby + 0x10, vector);
        clear_u64_value(moby + 0x40);
        func_001FA1F8(moby + 0xC0, moby + 0x40);
    }
    return moby;
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002EB4E0), where it is exact; names translated to the US level program. */

char *FUN_L18_002ea0f0(void *owner, void *vector, int value) {
    char *moby = CreateMoby(0x3D7);
    if (moby != 0) {
        char *data;
        ((unsigned char *)moby)[0x30] = 0xFF;
        qcopy(moby + 0x10, vector);
        data = *(char **)(moby + 0x78);
        *(void **)(data + 0x20) = owner;
        *(int *)(data + 0x28) = 5;
        *(int *)(data + 0x34) = value;
        *(int *)(data + 0x24) = 0;
    }
    return moby;
}
#include "qcopy.h"

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002EB558), where it is exact; names translated to the US level program. */

void FUN_L18_002ea168(unsigned char *arg, void *src, void *position, int active, float speed) {
    char *data = *(char **)(arg + 0x78);
    qcopy(arg + 0x10, src);
    *(int *)(data + 0x28) = scale_ticks(5);
    *(float *)(data + 0x24) = speed;
    if (active && arg[0x20] == 0) {
        arg[0x20] = 1;
        *(int *)(data + 0x28) = 0;
        qcopy(data, position);
    }
}

#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002A8400), where it is exact; names translated to the US level program. */

typedef struct { float v[4]; } __attribute__((aligned(16))) QVa840;
typedef int TIa7220 __attribute__((mode(TI)));

typedef struct {
    char v[16]; char padv[16];
    float f20;
    char pad24[4];
    float f28;
    char pad2C[4];
    int f30;
    int f34;
} Child;

typedef struct {
    char pad0[0x10];
    char pos[0x10];
    unsigned char b20;
    char pad21[0xB];
    float f2C;
    unsigned char b30;
    unsigned char b31;
    short s32;
    unsigned short h34;
    char pad36[0x12];
    float f48;
    char pad4C[0x2C];
    Child *child;
    char pad7C[0x14];
    int f90;
} Obj;

extern char *FUN_L00_0026cbb0(void *pos, void *dir, int c, int d, int n, int k, float f);
extern char D_0013F410[];
extern f32 fast_add_rotations(f32 a, f32 b) __asm__("FUN_001fa580");
extern f32 vector_length_xy(void *) __asm__("FUN_001f9b20");
extern f32 vector_length_xyz(void *a) __asm__("FUN_001f9af0");
extern float D_0015ED6C MACRO_ADDR;
extern float FUN_001f9e90(float, float);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001efa68(void *, void *, int, void *, void *);
extern int FUN_001f9770(void *);
extern void func_L00_0025F4A8_alt(void*,void*,void*,float,float,int,int,int,float,float,float,float,int,float,int,int,int,int) __asm__("FUN_L00_0025e450");
extern s32 scale_game_frames(s32) __asm__("FUN_001f96f8");
extern unsigned char *D_L18_001B2ADC;
extern unsigned char *FUN_L00_002712b8(void *pos, float *vec, int s, int a, int col, int n, float x, float y, float z, float w, float pw);
extern void FUN_L00_00257d78(float *, float, float);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void scale_vector_xyz(void *out, void *a, f32 s) __asm__("FUN_001f9a68");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
extern void transform_vector_by_basis(void *, void *, void *) __asm__("FUN_001f9cf8");
void mark_moby_for_removal_a7220(void *obj) __asm__("FUN_0020c828");
extern char *D_L18_001B2DDC_c __asm__("D_L18_001B2ADC") __attribute__((section(".data")));

void FUN_L18_002a7220(char *moby) {
    float a[4];
    char c[0x30];
    float b[4];
    float d[4];
    float e[4];
    float f[4];
    char *data = *(char **)(moby + 0x78);
    float *p;
    float f20, f1;
    char *t;

    *(float *)(moby + 0x40) = fast_add_rotations(*(float *)(moby + 0x40), D_0015ED6C * 6.2831855f);
    if (*(short *)(data + 0x12) != 0) {
        f20 = vector_length_xyz(data);
        subtract_vector_xyz(data, D_0013F410, moby + 0x10);
        f1 = vector_length_xyz(data);
        if (f20 < f1) {
            normalize_vector_xyz(data, data, f20);
            *(float *)(moby + 0x48) = FUN_001f9e90(*(float *)data, *(float *)(data + 4));
            *(float *)(moby + 0x44) = -FUN_001f9e90(vector_length_xy(data), *(float *)(data + 8));
        } else if (f1 < 0.1f) {
            mark_moby_for_removal_a7220(moby);
            return;
        }
    }
    add_vector_xyz(a, moby + 0x10, data);
    t = *(char **)(data + 0x14);
    if (t != 0 && *(short *)(t + 0xA6) == 0x2E && ((unsigned char *)t)[0x20] != 0xFE
        && ((unsigned char *)t)[0x20] != 0xFD) {
        subtract_vector_xyz(b, moby + 0x10, t + 0x10);
        b[2] = 0.0f;
        normalize_vector_xyz(b, b, 2.0f);
        b[3] = 5627.925f;
    } else {
        normalize_vector_xyz(b, data, 2.0f);
    }
    FUN_L00_00259888(c, (int)moby, 1, b, 2.0f);
    *(short *)(c + 0x1A) = *(unsigned short *)(moby + 0xA6);
    if (FUN_001efa68(moby + 0x10, a, 0, *(void **)(data + 0x14), c) != 0 || FUN_001f9770(data + 0x10) != 0) {
        func_L00_0025F4A8_alt(moby, data, moby + 0x10, 1.5f, 1.0f, 10, 6, 4, 1.0f, 0.5f, 9.0f, 0.5f, 0, 0.0f, 0, 0, -1, 0);
        mark_moby_for_removal_a7220(moby);
    } else {
        unsigned char *r;
        qcopy(moby + 0x10, a);
        FUN_L00_00257d78(d, D_0015ED6C * 0.1f, D_0015ED6C * 0.2f);
        scale_vector_xyz(e, data, random_float_between_alt(0.0f, 1.0f));
        add_vector_xyz(e, e, moby + 0x10);
        r = FUN_L00_002712b8(e, d, scale_game_frames(10), 0x7F, 0x606060, 3, 40000.0f, 1000.0f, 1.0f, -0.0002f, 0.0f);
        if (r != 0) {
            r[2] = *D_L18_001B2DDC_c;
            r[3] = 0x44;
        }
        *(TIa7220 *)f = 0;
        f[2] = 0.02f;
        transform_vector_by_basis(f, f, moby + 0xC0);
        FUN_L00_0026cbb0(e, f, 0x4F007FFF, 0x1FFFFFFF, scale_game_frames(10), 1, 20000.0f);
    }
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002A87D0), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m(int);
extern float FUN_001f9b20(void *);
extern float FUN_001f9e90(float, float);
extern int FUN_001f96f8(int);

char *FUN_L18_002a75f0(char *owner, float *pos, float *vec, int arg3) {
    char *moby = func_0020D348_m(0x29);
    if (moby != 0) {
        char *data;
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 0;
        *(long *)(moby + 0x38) = *(long *)(owner + 0x38);
        *(float *)(moby + 0x2C) = *(float *)(moby + 0x2C) * 3.0f;
        qcopy(moby + 0x10, pos);
        data = *(char **)(moby + 0x78);
        qcopy(data, vec);
        *(short *)(data + 0x10) = FUN_001f96f8(0xF0);
        *(short *)(data + 0x12) = arg3;
        *(char **)(data + 0x14) = owner;
        *(float *)(moby + 0x48) = FUN_001f9e90(vec[0], vec[1]);
        *(float *)(moby + 0x44) = -FUN_001f9e90(FUN_001f9b20(vec), vec[2]);
    }
    return moby;
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D6440), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x24];
    float f24;
    float f28;
    int c;
    int lim;
    int end;
    int flags;
} L18D;



extern char *D_L18_00174858;
extern char D_001413D4[];
extern f32 ConvertIntegerToFloat(s32) __asm__("FUN_001fa6c0");
extern float FUN_001f96b0(float);
extern int D_L18_0015F5C4;
extern int FUN_001efa68(void *, void *, int, void *, void *);
extern short D_L18_00161964;
extern void FUN_001f99f8(void *);
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a40(void *, void *, void *, float);
extern void FUN_001f9a68(void *, void *, float);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_001fa030(void *, void *);
extern void FUN_001fa2d8(void *, void *);
extern void FUN_L18_002d5488(void *, void *);
extern void FUN_L18_002d5610_u(void *, void *) __asm__("FUN_L18_002d5610");
extern void FUN_L18_002d5768(void);
void mark_moby_for_removal_c(struct Obj *obj) __asm__("FUN_0020c828");

void FUN_L18_002d5050(char *moby) {
    L18D *d = *(L18D **)(moby + 0x78);
    float v0[4];
    float v10[4];
    float a20[4];
    float a30[4];
    float a40[12];
    float a70[12];
    float aA0[16];
    float s, f, k;
    int r;
    if (*(int *)(D_001413D4) == 0x72 || D_L18_0015F5C4 == 2) {
        mark_moby_for_removal_c(moby);
    } else if (((unsigned char *)moby)[0x20] == 0) {
        qcopy(a30, moby + 0x10);
        s = ConvertIntegerToFloat(d->c);
        s = s / ConvertIntegerToFloat(d->lim);
        if (1.0f < s) {
            s = 1.0f;
        }
        FUN_001f9a28(v0, (char *)d + 0x10, moby + 0x10);
        FUN_001f9a68(v0, v0, 1.0f / ConvertIntegerToFloat(d->end - d->c));
        FUN_001f99f8(a20);
        a20[2] = FUN_001f9e90(v0[0], v0[1]);
        FUN_001fa030(a40, a20);
        FUN_001fa2d8(aA0, a40);
        FUN_001f99f8(a20);
        a20[2] = d->f24;
        a20[1] = d->f28;
        FUN_001fa030(a70, a20);
        FUN_001f9cf8(v0, v0, aA0);
        FUN_001f9cf8(v0, v0, a70);
        FUN_001f9cf8(v0, v0, a40);
        FUN_001f9a40(v10, d, v0, s);
        FUN_L18_002d5488(moby, v10);
        FUN_001f9a10(moby + 0x10, moby + 0x10, v10);
        *(float *)(moby + 0x48) = FUN_001f9e90(v10[0], v10[1]);
        f = FUN_001f9e90(FUN_001f9b20(v10), v10[2]);
        k = D_0015ED6C;
        *(float *)(moby + 0x44) = -f;
        *(float *)(moby + 0x40) = FUN_001fa580(*(float *)(moby + 0x40), k * 18.849556f);
        d->c = d->c + 1;
        r = FUN_001efa68(a30, moby + 0x10, 0, moby, 0);
        if (r) {
            char *p = D_L18_00174858;
            if (p != 0) {
                short h = *(short *)(p + 0xA6);
                if (h == 0x1DF) {
                    d->flags = d->flags & 4;
                } else if (h != 0x1A3) {
                    r = 0;
                }
            }
        }
        if (d->c == d->end || r) {
            FUN_L18_002d5610_u(moby, v10);
            mark_moby_for_removal_c(moby);
        } else if (d->flags & 2) {
            f = (float)(d->end - d->c);
            if (f <= FUN_001f96b0(*(float *)&D_L18_00161964)) {
                enqueue_callback_list_1_alt(FUN_L18_002d5768, moby);
            }
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d5348.s", FUN_L18_002d5348);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d5488.s", FUN_L18_002d5488);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D6A00), where it is exact; names translated to the US level program. */

typedef struct { float v[4]; } __attribute__((aligned(16))) QVec;
typedef int TId5610 __attribute__((mode(TI)));

extern unsigned char D_001413F4_d5610[] __asm__("D_001413F4");
extern short D_L18_0016196C __attribute__((sda));

void FUN_L18_002d5610(void *m, void *src) {
    char *moby = m;
    float q[4];
    float *qp = q;
    int flags;
    float a, b, c, d, e;
    *(TId5610 *)qp = *(TId5610 *)src;
    flags = *(int *)(*(char **)(moby + 0x78) + 0x38);
    c = (flags & 1) ? 2.0f : 0.75f;
    a = (flags & 1) ? 4.0f : 2.0f;
    b = (flags & 1) ? 2.0f : 1.0f;
    d = (flags & 4) ? 0.0f : 1.5f;
    func_L00_0025F4A8_alt(moby, qp, moby + 0x10, d, 1.0f, 0x14, 6, 0x20, a, b, 9.0f, c, 1, 5.0f, 0, 0, -1, 0);
    if (d != 0.0f) {
        if (D_001413F4_d5610[0] == 2) {
            FUN_L00_002598b0((int)moby, 2.0f, moby + 0x10, 2, *(float *)&D_L18_0016196C, 1.0f, 0, 1, 0);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d5768.s", FUN_L18_002d5768);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d5918.s", FUN_L18_002d5918);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D70E8), where it is exact; names translated to the US level program. */

typedef struct {
    char _pad00[0x10];
    unsigned char nframes; /* 0x10 */
} AnimSeq_q;

typedef struct {
    char _pad00[0x48];
    AnimSeq_q *seqs[1]; /* 0x48 */
} AnimClass_q;

typedef struct {
    char _pad00[0x24];
    AnimClass_q *pClass;       /* 0x24 */
    char _pad28[0x50 - 0x28];
    unsigned char frame;     /* 0x50 */
    unsigned char nextFrame; /* 0x51 */
    unsigned char seq;       /* 0x52 */
    unsigned char prevSeq;   /* 0x53 */
    char _pad54[0x5C - 0x54];
    float unk5C;             /* 0x5C */
    char _pad60[0x68 - 0x60];
    float *frameData;        /* 0x68 */
    char _pad6C[4];
    unsigned char unk70;     /* 0x70 */
} MobyAnim_q;

extern f32 vector_length_xy_q(void *) __asm__("FUN_001f9b20");
extern float D_0015ED70_q __asm__("D_0015ED70");
extern float FUN_001f9e90_q(float, float) __asm__("FUN_001f9e90");
extern float FUN_L00_0025abf0_q(float *a, float *b, float *out, float speed, float g) __asm__("FUN_L00_0025abf0");
extern int *D_L18_001AC240_q[] __asm__("D_L18_001AC240") __attribute__((section(".data")));
extern int D_L18_0015FFD8_m __asm__("D_L18_0015FFD8");
extern short D_L18_00161994_q __asm__("D_L18_00161994") __attribute__((sda));
extern void FUN_001f9c48_q(void *, void *, float) __asm__("FUN_001f9c48");
extern void FUN_0022da68_q(int, int, int) __asm__("FUN_0022da68");
extern void add_vector_xyz_q(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz_q(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void subtract_vector_xyz_q(void *out, void *a, void *b) __asm__("FUN_001f9a28");
void blend_moby_animation_q(MobyAnim_q *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

char *FUN_L18_002d5cf8(float f, int a0, int idx, float *p6, float *p7, int a8) {
    float v[4];
    float r;
    float g;
    char *found = 0;
    short *p = (short *)D_L18_001AC240_q[idx];
    char *moby;
    char *data;
    char *d2;
    if (p == 0) {
        return 0;
    }
    {
        char *base = D_L18_0015FFD8_m;
        unsigned short s;
        do {
            s = *p;
            {
                char *m = base + ((s & 0x7FFF) << 8);
                if (*(short *)(m + 0xA6) == 0x238) {
                    if (((unsigned char *)m)[0x20] == 5) {
                        found = m;
                    }
                }
            }
            p++;
        } while ((short)s >= 0);
    }
    moby = found;
    if (moby != 0) {
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 1;
        *(unsigned short *)(moby + 0x34) = (*(unsigned short *)(moby + 0x34) & 0xFFBE) | 0x1000;
        moby[0xBC] = 0;
        *(int *)(moby + 0x94) = *(int *)(*(char **)(moby + 0x24) + 0x10);
        if (((unsigned char *)moby)[0x53] != 0) {
            blend_moby_animation_q(moby, 0, 0, 1);
        }
        qcopy(moby + 0x10, p6);
        r = *(float *)&D_L18_00161994_q;
        *(int *)(moby + 0x40) = 0;
        *(float *)(moby + 0x44) = -r;
        p7[2] = p7[2] + 0.75f;
        subtract_vector_xyz_q(v, p7, p6);
        FUN_001f9c48_q(v, v, vector_length_xy_q(v) - *(float *)&D_L18_00161994_q);
        add_vector_xyz_q(v, v, p6);
        data = *(char **)(moby + 0x78);
        qcopy(data + 0x170, v);
        subtract_vector_xyz_q(data + 0x180, v, p6);
        *(int *)(data + 0x188) = 0;
        normalize_vector_xyz_q(data + 0x180, data + 0x180, f);
        g = D_0015ED70_q * 10.0f;
        *(short *)(data + 0xC8) = 0;
        *(float *)(data + 0x188) = FUN_L00_0025abf0_q(p6, v, 0, f, -g);
        *(float *)(moby + 0x48) = FUN_001f9e90_q(*(float *)(data + 0x180), *(float *)(data + 0x184));
        *(int *)(data + 0x194) = a8;
        *(int *)(data + 0x198) = a0;
        *(int *)(data + 0x19C) = 0;
        FUN_0022da68_q(0, 0, (int)moby);
    }
    return moby;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d5f20.s", FUN_L18_002d5f20);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d6108.s", FUN_L18_002d6108);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d62e8.s", FUN_L18_002d62e8);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D79F0), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x10];
    int i10;
    char pad1[0x10];
    float f24;
} L18Cls_q;

typedef struct {
    char pad0[0x10];
    float f10;
    char *p14;
    char *p18;
    char *p1C;
    float f20;
    float f24;
    float f28;
    float f2C;
    int i30;
    float f34;
    int i38;
} L18E_q;

typedef struct {
    char v[16]; char padv[16];
    float f20;
    char pad24[4];
    float f28;
    char pad2C[4];
    int f30;
    int f34;
} Child_q;

typedef struct {
    char pad0[0x10];
    char pos[0x10];
    unsigned char b20;
    char pad21[0xB];
    float f2C;
    unsigned char b30;
    unsigned char b31;
    short s32;
    unsigned short h34;
    char pad36[0x12];
    float f48;
    char pad4C[0x2C];
    Child_q *child;
    char pad7C[0x14];
    int f90;
} Obj_q;

extern char *D_L18_00174858_q __asm__("D_L18_00174858") __attribute__((section(".data")));
extern char *func_0020D348_m_q(int) __asm__("FUN_0020c4f8");
extern char D_0013F350_q[] __asm__("D_0013F350");
extern float D_0015ED6C_q __asm__("D_0015ED6C");
extern float D_0015ED70_d __asm__("D_0015ED70");
extern float FUN_001fa580_q(float, float) __asm__("FUN_001fa580");
extern float FUN_00213f38_q(float *, float *, float, float, float, float) __asm__("FUN_00213f38");
extern int D_L18_0015F5C4_d __asm__("D_L18_0015F5C4");
extern int D_L18_0016D290_q __asm__("D_L18_0016D290") __attribute__((section(".data")));
extern int FUN_001f9740_q(int *) __asm__("FUN_001f9740");
extern short D_L18_00161998_d __asm__("D_L18_00161998") __attribute__((sda));
extern short D_L18_0016199C_d __asm__("D_L18_0016199C") __attribute__((sda));
extern short D_L18_001619A0_d __asm__("D_L18_001619A0") __attribute__((sda));
extern void FUN_001f9a10_q(void *, void *, void *) __asm__("FUN_001f9a10");
extern void FUN_001f9bf8_q(void *, void *, float) __asm__("FUN_001f9bf8");
extern void FUN_0022da68_q(int, int, int) __asm__("FUN_0022da68");
extern void FUN_L00_00250df8_q(void *) __asm__("FUN_L00_00250df8");
f32 probe_ground_height(void *arg0, s32 arg1, f32 arg2) __asm__("FUN_00213508");
void mmr_q(void *obj) __asm__("FUN_0020c828");

void FUN_L18_002d6600(char *moby) {
    L18E_q *d = *(L18E_q **)(moby + 0x78);
    *(float *)(moby + 0x2C) = (*(L18Cls_q **)(moby + 0x24))->f24 * *(float *)&D_L18_00161998_d;
    switch (((unsigned char *)moby)[0x20]) {
    case 0: {
        *(float *)(moby + 0x18) = *(float *)(moby + 0x18) + 1.0f;
        *(int *)(moby + 0x94) = 0;
        *(float *)(moby + 0x18) = probe_ground_height(moby + 0x10, 0, 0.5f);
        qcopy(d, moby + 0x10);
        if (D_L18_00174858_q != 0) {
            d->i38 = 1;
        }
        {
            char *a = func_0020D348_m_q(0x6EB);
            a[0x30] = 0x40;
            *(short *)(a + 0x32) = 0x56;
            a[0x31] = 1;
            *(short *)(a + 0x32) = 0x56;
            *(float *)(a + 0x2C) = (*(L18Cls_q **)(a + 0x24))->f24 * *(float *)&D_L18_00161998_d;
            qcopy(a + 0x10, d);
            qcopy(a + 0x40, moby + 0x40);
            FUN_L00_00250df8_q(a);
            d->p1C = a;
        }
        d->p14 = func_0020D348_m_q(0x6F0);
        d->p14[0x30] = 0x40;
        *(short *)(d->p14 + 0x32) = 0x56;
        d->p14[0x31] = 1;
        *(float *)(d->p14 + 0x2C) = (*(L18Cls_q **)(d->p14 + 0x24))->f24 * *(float *)&D_L18_00161998_d;
        {
        char *q = d->p14;
        qcopy(q + 0x40, moby + 0x40);
        FUN_L00_00250df8_q(q);
        }
        d->p18 = func_0020D348_m_q(0x6F0);
        d->p18[0x30] = 0x40;
        *(short *)(d->p18 + 0x32) = 0x40;
        d->p18[0x31] = 1;
        *(float *)(d->p18 + 0x2C) = (*(L18Cls_q **)(d->p18 + 0x24))->f24 * *(float *)&D_L18_00161998_d;
        {
        char *q = d->p18;
        qcopy(q + 0x40, moby + 0x40);
        *(float *)(d->p18 + 0x48) = FUN_001fa580_q(*(float *)(q + 0x48), 3.1415901f);
        FUN_L00_00250df8_q(d->p18);
        }
        ((unsigned char *)moby)[0x20] = 1;
        {
            float t = *(float *)(moby + 0x18);
            float u = *(float *)&D_L18_001619A0_d;
            d->f10 = t;
            d->f34 = u;
        }
        *(int *)(moby + 0x94) = (*(L18Cls_q **)(moby + 0x24))->i10;
        break;
    }
    case 1: {
        float v[4];
        if (D_L18_0015F5C4_d == 2) {
            if (d->i38 != 0) {
                if (D_L18_0016D290_q == 3) {
                    if (d->p14 != 0) mmr_q(d->p14);
                    if (d->p18 != 0) mmr_q(d->p18);
                    if (d->p1C != 0) mmr_q(d->p1C);
                    mmr_q(moby);
                }
            }
        }
        if (d->f24 != 0.0f) {
            if ((d->i30 == 0 && FUN_001f9740_q((int *)&d->f2C) == 2) ||
                (D_L18_0015F5C4_d == 2 && D_L18_0016D290_q >= 4)) {
                FUN_0022da68_q(0, 0, (int)moby);
                d->f24 = 0;
            }
            {
                char *b = D_0013F350_q;
                if (*(short *)(b + 0x30E) == 0 && *(int *)(b + 0x2084) == 0x22) {
                    FUN_0022da68_q(0, 0, (int)moby);
                    d->f24 = 0;
                }
            }
        }
        if (d->f24 != 0.0f) {
            if (d->f20 != d->f24) {
                FUN_00213f38_q(&d->f20, &d->f28, d->f24, D_0015ED70_d * 4.0f, D_0015ED70_d * 4.0f, D_0015ED6C_q * 4.0f);
            } else {
                float k = D_0015ED70_d;
                FUN_00213f38_q(&d->f34, &d->f28, *(float *)&D_L18_0016199C_d, k * 16.0f, k * 4.0f, D_0015ED6C_q * 8.0f);
            }
        } else if (d->f34 != *(float *)&D_L18_001619A0_d) {
            float k = D_0015ED70_d;
            FUN_00213f38_q(&d->f34, &d->f28, *(float *)&D_L18_001619A0_d, k * 16.0f, k * 4.0f, D_0015ED6C_q * 8.0f);
        } else {
            FUN_00213f38_q(&d->f20, &d->f28, d->f24, D_0015ED70_d * 4.0f, D_0015ED70_d * 4.0f, D_0015ED6C_q * 4.0f);
        }
        if (d->p14 != 0) {
            FUN_001f9bf8_q(d->p14 + 0x10, d->p14 + 0xD0, -d->f20);
            FUN_001f9bf8_q(v, d->p14 + 0xE0, -d->f20 * 0.2f);
            FUN_001f9a10_q(d->p14 + 0x10, d->p14 + 0x10, v);
            FUN_001f9a10_q(d->p14 + 0x10, d->p14 + 0x10, d);
            FUN_L00_00250df8_q(d->p14);
        }
        if (d->p18 != 0) {
            FUN_001f9bf8_q(d->p18 + 0x10, d->p18 + 0xD0, -d->f20);
            FUN_001f9bf8_q(v, d->p18 + 0xE0, -d->f20 * 0.2f);
            FUN_001f9a10_q(d->p18 + 0x10, d->p18 + 0x10, v);
            FUN_001f9a10_q(d->p18 + 0x10, d->p18 + 0x10, d);
            FUN_L00_00250df8_q(d->p18);
        }
        *(float *)(moby + 0x18) = d->f10 + d->f34;
    }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d6b58.s", FUN_L18_002d6b58);
/* Of the mobys of class 0x247 in list idx, the one nearest to pos (within
   255 units), or 0. The second spelling of the table base keeps the
   address out of the loop's $gp-relative reload in the bc1f delay slot. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D8070), where it is exact; names translated to the US level program. */

extern float FUN_001f9b48(void *, void *);
extern int *D_L18_001AC240_c[] __asm__("D_L18_001AC240");
extern int D_L18_0015FFD8; /* no foreign declaration */
extern int D_L18_0015FFD8; /* no foreign declaration */

char *FUN_L18_002d6c80(void *pos, int idx) {
    short *p = (short *)D_L18_001AC240_c[idx];
    char *best = 0;
    float bestd = 255.0f;
    if (p == 0) return 0;
    while (1) {
        int off = (*p & 0x7FFF) << 8;
        char *m = (char *)(off + (int)D_L18_0015FFD8);
        if (*(short *)(m + 0xA6) == 0x247) {
            float d = FUN_001f9b48(pos, m + 0x10);
            if (d < bestd) {
                bestd = d;
                best = D_L18_0015FFD8 + off;
            }
        }
        if (*p++ < 0) return best;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d7b20.s", FUN_L18_002d7b20);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002D93C0), where it is exact; names translated to the US level program. */

extern char D_0013E550[];
extern void release_voice_slot(s32) __asm__("FUN_0022d798");

void FUN_L18_002d7fd0(unsigned char *arg) {
    int *data = *(int **)(arg + 0x78);
    if (arg[0x20] == 2) {
        int idx;
        arg[0x20] = 3;
        idx = data[0x70 / 4];
        if (idx != -1) {
            unsigned char *e = (unsigned char *)D_0013E550 + idx * 0x70;
            if (*(unsigned char **)(e + 0x88) == arg && e[0x74]) {
                release_voice_slot(idx);
            }
        }
        data[0x70 / 4] = -1;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d8050.s", FUN_L18_002d8050);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d82c0.s", FUN_L18_002d82c0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d8888.s", FUN_L18_002d8888);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002d88b8.s", FUN_L18_002d88b8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002db460.s", FUN_L18_002db460);
/* Allocate an object, init its fields and child record. */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DCD28), where it is exact; names translated to the US level program. */

extern short D_L18_00161BF8_d __asm__("D_L18_00161BF8") __attribute__((sda));
extern short D_L18_00161BFC_d __asm__("D_L18_00161BFC") __attribute__((sda));

void FUN_L18_002db938(char *pos, float *vec, int arg, float fa, float fb) {
    Obj *o = (Obj *)func_0020D348_m(0x270);
    if (o != 0) {
        Child *c;
        int g;
        o->b30 = 0xFF;
        o->b31 = 1;
        o->b20 = 0;
        g = *(int *)&D_L18_00161BFC_d;
        o->f2C = o->f2C * *(float *)&D_L18_00161BF8_d;
        o->s32 = 0xFF;
        o->h34 |= 0x10;
        o->f90 = g;
        c = o->child;
        qcopy(o->pos, pos);
        o->f48 = FUN_001f9e90(vec[0], vec[1]);
        qcopy(c->v, vec);
        c->f34 = arg;
        c->f28 = fa;
        c->f20 = fb;
        c->f30 = 0;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002dba20.s", FUN_L18_002dba20);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DD270), where it is exact; names translated to the US level program. */

extern char D_0013F3D0[];
extern float FUN_001f9dc8(float);
extern void FUN_L18_002dc0c8_u(char *moby, void *a1, void *a2) __asm__("FUN_L18_002dc0c8");

void FUN_L18_002dbe80(char *moby) {
    char hit[0x30];
    float v[4];
    float a[4];
    float b[4];
    char *d = *(char **)(moby + 0x78);
    float p, q, step;
    int i;

    FUN_001f9a28(v, D_0013F3D0, moby + 0x10);
    v[2] = 0.0f;
    FUN_001f9bf8(v, v, D_0015ED6C * 4.0f);
    v[2] = D_0015ED6C * 4.0f;
    FUN_L00_00259888(hit, (int)moby, 0x10001, v, 3.0f);
    step = 1.0f / ConvertIntegerToFloat(0x40) * 6.28318f;
    p = -3.14159f;
    q = FUN_001fa580(p, step);
    for (i = 0x3F; i >= 0; i--) {
        a[0] = FUN_001f9dc8(p) * *(float *)(d + 0x24);
        a[1] = FUN_001f9de0(p) * *(float *)(d + 0x24);
        a[2] = 0.0f;
        b[0] = FUN_001f9dc8(q) * *(float *)(d + 0x24);
        b[1] = FUN_001f9de0(q) * *(float *)(d + 0x24);
        b[2] = 0.0f;
        FUN_001f9a10(a, a, moby + 0x10);
        a[2] += 0.5f;
        FUN_001f9a10(b, b, moby + 0x10);
        b[2] += 0.5f;
        FUN_001efa68(a, b, 1, *(void **)(d + 0x34), hit);
        if (*(float *)(d + 0x24) < 3.0f) {
            FUN_L18_002dc0c8_u(moby, a, b);
        }
        p = FUN_001fa580(p, step);
        q = FUN_001fa580(q, step);
    }
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DD4B8), where it is exact; names translated to the US level program. */

extern float FUN_001f9b48(void *, void *);
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int FUN_001fa6e0(int, int, float);
extern int FUN_001fa728(char *, float);
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern short D_L18_00161BF4_d __asm__("D_L18_00161BF4") __attribute__((sda));
extern short D_L18_00161C80_d __asm__("D_L18_00161C80") __attribute__((sda));
extern short D_L18_00161C84_d __asm__("D_L18_00161C84") __attribute__((sda));
extern short D_L18_00161C88_d __asm__("D_L18_00161C88") __attribute__((sda));
extern short D_L18_00161C8C_d __asm__("D_L18_00161C8C") __attribute__((sda));
extern short D_L18_00161C90_d __asm__("D_L18_00161C90") __attribute__((sda));
extern short D_L18_00161C98_d __asm__("D_L18_00161C98") __attribute__((sda));
extern void FUN_L00_002730e0(void *, void *, int, int, int, int, float);

void FUN_L18_002dc0c8(char *moby, void *a1, void *a2) {
    float buf[4];
    float v[4];
    float w[4];
    char *d = *(char **)(moby + 0x78);
    int col;

    FUN_001f9a40(buf, a1, a2, 0.5f);
    buf[3] = FUN_001f9b48(a1, a2) * 0.5f;
    if (FUN_001fa728((char *)buf, *(float *)&D_L18_00161BF4_d) == -1) {
        return;
    }
    if (random_float_between_alt(0.0f, 1.0f) < *(float *)&D_L18_00161C98_d) {
        FUN_001f9a40(v, a1, a2, random_float_between_alt(0.0f, 1.0f));
        FUN_001f9a28(w, v, moby + 0x10);
        FUN_001f9bf8(w, w, *(float *)(d + 0x20));
        col = FUN_001fa6e0(*(int *)&D_L18_00161C80_d, *(int *)&D_L18_00161C84_d, random_float_between_alt(0.0f, 1.0f));
        FUN_L00_002730e0(v, w, col, FUN_001f96f8(*(int *)&D_L18_00161C8C_d) & 0xFF,
                          random_integer_below(0xFF) & 0xFF, 0, *(float *)&D_L18_00161C88_d);
        w[2] = 0.0f;
        FUN_L00_002730e0(v, w, col, FUN_001f96f8(*(int *)&D_L18_00161C90_d) & 0xFF,
                          random_integer_below(0xFF) & 0xFF, 0, *(float *)&D_L18_00161C88_d);
    }
}
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002DD848), where it is exact; names translated to the US level program. */

extern short D_L18_00161C9C_d __asm__("D_L18_00161C9C") __attribute__((sda));

void FUN_L18_002dc458(char *moby, void *pos, float f)
{
    int *d = *(int **)(moby + 0x78);
    int lim;
    qcopy(moby + 0x10, pos);
    lim = *(int *)&D_L18_00161C9C_d;
    d[2] += 2;
    *(float *)d = f;
    if (FUN_001f96f8(lim) < d[2]) {
        d[2] = FUN_001f96f8(*(int *)&D_L18_00161C9C_d);
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002dc4b8.s", FUN_L18_002dc4b8);
/* UpdateMoby state machine for the vendor moby (state at +0x20). */
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002E09F8), where it is exact; names translated to the US level program. */

extern char D_001413D4_q[] __asm__("D_001413D4") __attribute__((section(".data")));
extern f32 approach_value_q(f32 *, f32, f32) __asm__("FUN_00213ed8");
extern float D_0015ED6C_d __asm__("D_0015ED6C");
extern float D_L18_0015F3FC_d __asm__("D_L18_0015F3FC");
extern float FUN_001fa5c8_q(float, float) __asm__("FUN_001fa5c8");
extern int D_L18_0015F404_d __asm__("D_L18_0015F404");
extern int D_L18_00179E10_q[] __asm__("D_L18_00179E10") __attribute__((section(".data")));
extern int D_L18_0017EF08_q __asm__("D_L18_0017EF08") __attribute__((section(".data")));
extern int FUN_L00_00203908_q(int a, int b) __asm__("FUN_L00_00203908");
extern void FUN_001f99f8_q(void *) __asm__("FUN_001f99f8");
extern void FUN_001f9a40_q(void *, void *, void *, float) __asm__("FUN_001f9a40");
extern void FUN_L00_00216f90_q(void *, void *, int, int) __asm__("FUN_L00_00216f90");
extern void FUN_L00_002ea9d8_q(void *) __asm__("FUN_L00_002ea9d8");
extern void FUN_L00_002eaaa0_q(void *, void *, int, int, int) __asm__("FUN_L00_002eaaa0");
extern void FUN_L00_002eac18_q(int) __asm__("FUN_L00_002eac18");

void FUN_L18_002df608(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v[12];
    switch (((unsigned char *)moby)[0x20]) {
    case 0:
        moby[0x20] = 1;
        ((unsigned char *)moby)[0x30] = 0xFF;
        break;
    case 2:
        D_L18_0017EF08_q = 1;
        approach_value_q((float *)(data + 0x6C), 1.0f, D_0015ED6C_d * 4.0f);
        {
        float t = *(float *)(data + 0x6C);
        if (D_L18_0015F3FC_d < t) {
            D_L18_0015F3FC_d = t;
        }
        if (1.0f <= t) {
            D_L18_0015F404_d = 1;
            FUN_001f99f8_q(v);
            v[2] = *(float *)(data + 0x4C);
            FUN_L00_00216f90_q(data + 0x40, v, 0x72, 1);
            FUN_L00_002eaaa0_q(data, data + 0x20, 1, 0, 0);
            if (*(int *)(data + 0x78) == 1) {
                FUN_L00_00203908_q(0x4650, 0x85);
                moby[0x20] = 4;
            } else {
                moby[0x20] = 3;
            }
        }
        }
        break;
    case 3:
        D_L18_0017EF08_q = 1;
        if (FUN_001f9740_q((int *)(data + 0x74))) {
            FUN_00213f38_q((float *)(data + 0x60), (float *)(data + 0x64), 1.0f, *(float *)(data + 0x68), *(float *)(data + 0x68), *(float *)(data + 0x70));
        }
        FUN_001f9a40_q(v, data, data + 0x10, *(float *)(data + 0x60));
        FUN_001f99f8_q(v + 4);
        v[5] = FUN_001fa5c8_q(*(float *)(data + 0x34), *(float *)(data + 0x24)) * *(float *)(data + 0x60);
        v[5] = FUN_001fa580_q(*(float *)(data + 0x24), v[5]);
        v[6] = FUN_001fa5c8_q(*(float *)(data + 0x38), *(float *)(data + 0x28)) * *(float *)(data + 0x60);
        v[6] = FUN_001fa580_q(*(float *)(data + 0x28), v[6]);
        FUN_L00_002ea9d8_q(v);
        FUN_L00_002ea9d8_q(v + 4);
        approach_value_q((float *)(data + 0x6C), 0.0f, D_0015ED6C_d * 4.0f);
        {
        float d = *(float *)(data + 0x60);
        D_L18_0015F3FC_d = *(float *)(data + 0x6C);
        if (1.0f <= d) {
            D_L18_0015F404_d = 0;
            FUN_001f99f8_q(v + 8);
            v[10] = *(float *)(data + 0x4C);
            FUN_L00_00216f90_q(data + 0x40, v + 8, 0, 0);
            FUN_L00_002eac18_q(2);
            moby[0x20] = 5;
        } else if (*(int *)(D_001413D4_q) != 0x72) {
            FUN_001f99f8_q(v + 8);
            v[10] = *(float *)(data + 0x4C);
            FUN_L00_00216f90_q(data + 0x40, v + 8, 0x72, 1);
            return;
        }
        }
        break;
    case 4:
        if (FUN_001f9740_q((int *)(data + 0x74))) {
            FUN_00213f38_q((float *)(data + 0x60), (float *)(data + 0x64), 1.0f, *(float *)(data + 0x68), *(float *)(data + 0x68), *(float *)(data + 0x70));
        }
        FUN_001f9a40_q(v, data, data + 0x10, *(float *)(data + 0x60));
        FUN_001f99f8_q(v + 4);
        v[5] = FUN_001fa5c8_q(*(float *)(data + 0x34), *(float *)(data + 0x24)) * *(float *)(data + 0x60);
        v[5] = FUN_001fa580_q(*(float *)(data + 0x24), v[5]);
        v[6] = FUN_001fa5c8_q(*(float *)(data + 0x38), *(float *)(data + 0x28)) * *(float *)(data + 0x60);
        v[6] = FUN_001fa580_q(*(float *)(data + 0x28), v[6]);
        FUN_L00_002ea9d8_q(v);
        FUN_L00_002ea9d8_q(v + 4);
        if (1.0f <= *(float *)(data + 0x60)
            || (0.2f < *(float *)(data + 0x60) && D_L18_00179E10_q[0] == 0 && D_L18_00179E10_q[9] == -1)) {
            float t;
            approach_value_q((float *)(data + 0x6C), 1.0f, D_0015ED6C_d * 4.0f);
            t = *(float *)(data + 0x6C);
            D_L18_0015F3FC_d = t;
            if (1.0f <= t) {
                D_L18_0015F404_d = 0;
                *(float *)(data + 0x60) = 1.0f;
                FUN_001f99f8_q(v + 8);
                v[10] = *(float *)(data + 0x4C);
                FUN_L00_00216f90_q(data + 0x40, v + 8, 0, 0);
                FUN_L00_002eac18_q(3);
                moby[0x20] = 5;
            }
        } else if (*(int *)(D_001413D4_q) != 0x72) {
            FUN_001f99f8_q(v + 8);
            v[10] = *(float *)(data + 0x4C);
            FUN_L00_00216f90_q(data + 0x40, v + 8, 0x72, 1);
            return;
        } else {
            approach_value_q((float *)(data + 0x6C), 0.0f, D_0015ED6C_d * 4.0f);
            D_L18_0015F3FC_d = *(float *)(data + 0x6C);
        }
        break;
    case 5:
        if (0.0f < *(float *)(data + 0x6C)) {
            approach_value_q((float *)(data + 0x6C), 0.0f, D_0015ED6C_d * 4.0f);
            D_L18_0015F3FC_d = *(float *)(data + 0x6C);
        } else {
            moby[0x20] = 1;
        }
        break;
    }
}
#include "sda.h"

/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002E0E90), where it is exact; names translated to the US level program. */

extern char D_0013E633[] __asm__("D_0013F3D0");
extern float D_0015EE70 __asm__("D_0015ED70") MACRO_ADDR;
extern s32 scale_game_frames(s32) __asm__("FUN_001f96f8");

void FUN_L18_002dfaa0(char *moby, void *v0, void *v1, void *v2, void *v3, void *v4, int a6, int a7, int a8) {
    char *data = *(char **)(moby + 0x78);
    *(int *)(data + 0x60) = 0;
    *(int *)(data + 0x64) = 0;
    qcopy(data, v0);
    qcopy(data + 0x10, v1);
    qcopy(data + 0x20, v2);
    qcopy(data + 0x30, v3);
    qcopy(data + 0x40, v4);
    moby[0x20] = 2;
    *(float *)(data + 0x68) = D_0015EE70 * 0.333f;
    *(float *)(data + 0x70) = 1.0f / (float)scale_game_frames(a6);
    *(int *)(data + 0x74) = scale_game_frames(a7);
    *(int *)(data + 0x78) = a8;
    *(int *)(D_0013E633 + 0x140) = scale_game_frames(a6);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002dfba0.s", FUN_L18_002dfba0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002e9768.s", FUN_L18_002e9768);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002e9e70.s", FUN_L18_002e9e70);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002ea1f8.s", FUN_L18_002ea1f8);
/* Ported from rac1-decomp (PAL, src/overlays/l18_veldin2/vendor_002A8400.c: func_L18_002EB988), where it is exact; names translated to the US level program. */

extern char *FUN_00218888(void *, void *, void *, int, int, int, int, int, int);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern short D_L18_00161F1C_d __asm__("D_L18_00161F1C") __attribute__((sda));
extern short D_L18_00161F20_d __asm__("D_L18_00161F20") __attribute__((sda));
extern short D_L18_00161F24_d __asm__("D_L18_00161F24") __attribute__((sda));
extern short D_L18_00161F28_d __asm__("D_L18_00161F28") __attribute__((sda));
extern short D_L18_00161F2C_d __asm__("D_L18_00161F2C") __attribute__((sda));
extern short D_L18_00161F30_d __asm__("D_L18_00161F30") __attribute__((sda));
extern short D_L18_00161F34_d __asm__("D_L18_00161F34") __attribute__((sda));
extern short D_L18_00161F38_d __asm__("D_L18_00161F38") __attribute__((sda));
extern short D_L18_00161F3C_d __asm__("D_L18_00161F3C") __attribute__((sda));
extern short D_L18_00161F40_d __asm__("D_L18_00161F40") __attribute__((sda));
extern short D_L18_00161F44_d __asm__("D_L18_00161F44") __attribute__((sda));
extern short D_L18_00161F48_d __asm__("D_L18_00161F48") __attribute__((sda));
extern short D_L18_00161F4C_d __asm__("D_L18_00161F4C") __attribute__((sda));
extern short D_L18_00161F50_d __asm__("D_L18_00161F50") __attribute__((sda));
extern short D_L18_00161F54_d __asm__("D_L18_00161F54") __attribute__((sda));
extern short D_L18_00161F58_d __asm__("D_L18_00161F58") __attribute__((sda));
extern short D_L18_00161F5C_d __asm__("D_L18_00161F5C") __attribute__((sda));
extern short D_L18_00161F60_d __asm__("D_L18_00161F60") __attribute__((sda));
extern short D_L18_00161F64_d __asm__("D_L18_00161F64") __attribute__((sda));
extern short D_L18_00161F68_d __asm__("D_L18_00161F68") __attribute__((sda));
extern void FUN_L00_00257d78(float *, float, float);
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L18_002ea598(char *moby) {
    float v10[4];
    float v20[4];
    float v30[4];
    float v40[4];
    int i;
    int c1, c2, a, b, c;
    float k1, k2, k3, k4;
    FUN_001f9a28(v40, *(void **)(moby + 0x78), moby + 0x10);
    FUN_001f9bf8(v40, v40, D_0015ED6C * 60.0f);
    k1 = (*(float *)&(D_L18_00161F54_d)) * D_0015ED6C;
    k2 = (*(float *)&(D_L18_00161F58_d)) * D_0015ED6C;
    k3 = (*(float *)&(D_L18_00161F60_d)) * D_0015ED6C;
    k4 = (*(float *)&(D_L18_00161F64_d)) * D_0015ED6C;
    for (i = 0; i < 3; i++) {
        FUN_L00_00257d78(v20, k1, k2);
        FUN_001f9a68(v30, v20, (*(float *)&(D_L18_00161F5C_d)));
        v30[2] -= random_float_between_alt(k3, k4);
        a = func_001FA898_r(FUN_001f96b0(random_float_between_alt((*(float *)&(D_L18_00161F3C_d)), (*(float *)&(D_L18_00161F40_d)))));
        b = func_001FA898_r(FUN_001f96b0(random_float_between_alt((*(float *)&(D_L18_00161F44_d)), (*(float *)&(D_L18_00161F48_d)))));
        c = func_001FA898_r(FUN_001f96b0(random_float_between_alt((*(float *)&(D_L18_00161F4C_d)), (*(float *)&(D_L18_00161F50_d)))));
        v20[3] = random_float_between_alt((*(float *)&(D_L18_00161F2C_d)), (*(float *)&(D_L18_00161F30_d)));
        v30[3] = random_float_between_alt((*(float *)&(D_L18_00161F34_d)), (*(float *)&(D_L18_00161F38_d)));
        FUN_001f9a68(v10, v40, random_float_between_alt(0.0f, 1.0f));
        FUN_001f9a10(v10, v10, moby + 0x10);
        c1 = FUN_001fa6e0((*(int *)&(D_L18_00161F1C_d)), (*(int *)&(D_L18_00161F20_d)), random_float_between_alt(0.0f, 1.0f));
        c2 = FUN_001fa6e0((*(int *)&(D_L18_00161F24_d)), (*(int *)&(D_L18_00161F28_d)), random_float_between_alt(0.0f, 1.0f));
        FUN_00218888(v10, v20, v30, c1, c2, a, b, c, (*(int *)&(D_L18_00161F68_d)));
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002ea800.s", FUN_L18_002ea800);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002eacd8.s", FUN_L18_002eacd8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L18_002eaea0.s", FUN_L18_002eaea0);
typedef struct { float f[4]; } __attribute__((aligned(16))) Vec130;
typedef struct { float u, v; } UVec130;
typedef struct {
    Vec130 corner[4];
    unsigned int color[4];
    UVec130 uv[4];
    long unk70, tex, unk80, unk88;
} Qec130;
extern unsigned int D_L18_001620A0 __asm__("D_L18_001620A0") __attribute__((sda));
extern unsigned int D_L18_00162054 __asm__("D_L18_00162054") __attribute__((sda));
extern float D_L18_001620A8 __asm__("D_L18_001620A8") __attribute__((sda));
extern float D_L18_001620AC __asm__("D_L18_001620AC") __attribute__((sda));
extern Vec130 D_L18_001677C0 __asm__("D_L18_001677C0") __attribute__((section(".data")));
extern Vec130 D_0013F5E0 __asm__("D_0013F5E0");
extern Vec130 D_L18_001D9CA0[] __asm__("D_L18_001D9CA0") __attribute__((section(".data")));
extern UVec130 D_L18_001D9CE0[] __asm__("D_L18_001D9CE0") __attribute__((section(".data")));
extern void vsub_ec130(void *, void *, void *) __asm__("FUN_001f9a28");
extern void vadd_ec130(void *, void *, void *) __asm__("FUN_001f9a10");
extern void vscl_ec130(void *, void *, float) __asm__("FUN_001f9bf8");
extern void cross_ec130(void *, void *, void *) __asm__("FUN_001f9ad8");
extern void vmul_ec130(float, void *, void *) __asm__("FUN_001f9a68");
extern void xform_ec130(void *, void *, void *) __asm__("FUN_001f9d20");
extern long tex_ec130(int) __asm__("FUN_001f44b8");
extern float rnd_ec130(float, float) __asm__("FUN_L00_00257c48");
extern void draw_ec130(void *, void *, int) __asm__("FUN_001f7d30");

void FUN_L18_002ec130(void *mv) {
    Qec130 quad;
    Vec130 mat[4];
    Vec130 *pos;
    unsigned int c;
    float s;
    int i;
    pos = (Vec130 *)mv;
    quad.tex = tex_ec130(0xB);
    pos = (Vec130 *)((char *)pos + 0x10);
    quad.unk88 = 0x8000000048L;
    quad.unk80 = 0xFF9000000260L;
    quad.unk70 = 0;
    vsub_ec130(&mat[3], &D_L18_001677C0, pos);
    vscl_ec130(&mat[3], &mat[3], 0.3f);
    vadd_ec130(&mat[3], &mat[3], pos);
    mat[3].f[3] = 1.0f;
    vsub_ec130(&mat[0], &D_L18_001677C0, &mat[3]);
    vscl_ec130(&mat[0], &mat[0], 1.0f);
    cross_ec130(&mat[1], &mat[0], &D_0013F5E0);
    vscl_ec130(&mat[1], &mat[1], -1.0f);
    cross_ec130(&mat[2], &mat[1], &mat[0]);
    c = D_L18_001620A0;
    quad.color[3] = c;
    quad.color[2] = c;
    quad.color[1] = c;
    quad.color[0] = c;
    s = D_L18_001620A8 + rnd_ec130(0.0f, 0.025f);
    for (i = 0; i < 4; i++) {
        vmul_ec130(s, &quad.corner[i], &D_L18_001D9CA0[i]);
        xform_ec130(&quad.corner[i], &quad.corner[i], &mat[0]);
        quad.uv[i].u = D_L18_001D9CE0[i].u;
        quad.uv[i].v = D_L18_001D9CE0[i].v;
    }
    draw_ec130(&quad, 0, 0);
    c = D_L18_00162054;
    quad.color[3] = c;
    quad.color[2] = c;
    quad.color[1] = c;
    quad.color[0] = c;
    s = D_L18_001620AC + rnd_ec130(0.0f, 0.05f);
    for (i = 0; i < 4; i++) {
        vmul_ec130(s, &quad.corner[i], &D_L18_001D9CA0[i]);
        xform_ec130(&quad.corner[i], &quad.corner[i], &mat[0]);
        quad.uv[i].u = D_L18_001D9CE0[i].u;
        quad.uv[i].v = D_L18_001D9CE0[i].v;
    }
    draw_ec130(&quad, 0, 0);
}
