/* Exact SDK/library unit sceScfGetLocalTimefromRTC; symbolic expected assembly retained pending source recovery. */
__asm__(
    ".set noreorder\n"
    ".text\n"
    ".align 3\n"
    ".globl sceScfGetLocalTimefromRTC\n"
    ".type sceScfGetLocalTimefromRTC, @function\n"
    "sceScfGetLocalTimefromRTC:\n"
    "addiu      $29, $29, -0x30\n"
    "sd         $16, 0x0($29)\n"
    "sd         $17, 0x10($29)\n"
    "sd         $31, 0x20($29)\n"
    "jal        sceScfGetTimeZone\n"
    "daddu     $16, $4, $0\n"
    "jal        sceScfGetSummerTime\n"
    "daddu     $17, $2, $0\n"
    "addiu      $3, $0, 0x3C\n"
    "daddu      $4, $16, $0\n"
    "mult       $2, $2, $3\n"
    "ld         $31, 0x20($29)\n"
    "ld         $16, 0x0($29)\n"
    "addiu      $2, $2, -0x21C\n"
    "addu       $5, $17, $2\n"
    "ld         $17, 0x10($29)\n"
    "j          AdjustTime\n"
    "addiu     $29, $29, 0x30\n"
    ".size sceScfGetLocalTimefromRTC, .-sceScfGetLocalTimefromRTC\n"
    ".set reorder\n"
);
