#ifndef RNC_ASSEMBLY_SDK_DMA_IPU_GS_WAIT_IPU_IDLE_TYPES_H
#define RNC_ASSEMBLY_SDK_DMA_IPU_GS_WAIT_IPU_IDLE_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x858];
    s32 unk858;
};

#endif /* RNC_ASSEMBLY_SDK_DMA_IPU_GS_WAIT_IPU_IDLE_TYPES_H */
