#ifndef RNC_ASSEMBLY_SDK_DECI_DEBUG_SCE_SCF_GET_SUMMER_TIME_TYPES_H
#define RNC_ASSEMBLY_SDK_DECI_DEBUG_SCE_SCF_GET_SUMMER_TIME_TYPES_H

#include "types.h"

struct M2c_SummerWork {
    u32 config;
    u8 summer;
};

#endif /* RNC_ASSEMBLY_SDK_DECI_DEBUG_SCE_SCF_GET_SUMMER_TIME_TYPES_H */
