#ifndef RNC_ASSEMBLY_TEXTBIN_FUN_001EE008_TYPES_H
#define RNC_ASSEMBLY_TEXTBIN_FUN_001EE008_TYPES_H

#include "types.h"

typedef struct { int a[9]; } T36;

#endif /* RNC_ASSEMBLY_TEXTBIN_FUN_001EE008_TYPES_H */
