#ifndef RNC_ASSEMBLY_SDK_LIBRARY_MALLOC_TRIM_R_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_MALLOC_TRIM_R_TYPES_H

#include "types.h"

typedef struct Blk16_2C8B68 {
    char b[0x10];
} Blk16_2C8B68;

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_MALLOC_TRIM_R_TYPES_H */
