#ifndef RNC_ASSEMBLY_SDK_LIBRARY_SCEDBCRECEIVEDATA_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_SCEDBCRECEIVEDATA_TYPES_H

#include "types.h"

struct M2c_D_0015B080 {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    u8 pad_C[0x80];
    s32 unk8C;
};

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_SCEDBCRECEIVEDATA_TYPES_H */
