#ifndef RNC_ASSEMBLY_SDK_SCE_SIF_REMOVE_CMD_HANDLER_TYPES_H
#define RNC_ASSEMBLY_SDK_SCE_SIF_REMOVE_CMD_HANDLER_TYPES_H

#include "types.h"

typedef struct { char pad[0x54]; int n; char *p; } S0036C518;

#endif /* RNC_ASSEMBLY_SDK_SCE_SIF_REMOVE_CMD_HANDLER_TYPES_H */
