#ifndef RNC_ASSEMBLY_SDK_LIBRARY_MB_ADDRESS_INCREMENT_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_MB_ADDRESS_INCREMENT_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x11C];
    s32 unk11C;
    u8 pad_120[0x728];
    s32 unk848;
};

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_MB_ADDRESS_INCREMENT_TYPES_H */
