#ifndef RNC_ASSEMBLY_EE_WRITE_DMA_CHANNEL_REGISTERS_TYPES_H
#define RNC_ASSEMBLY_EE_WRITE_DMA_CHANNEL_REGISTERS_TYPES_H

#include "types.h"

struct Obj_00290000 { int x0; int x4; int x8; int xc; int x10; };

#endif /* RNC_ASSEMBLY_EE_WRITE_DMA_CHANNEL_REGISTERS_TYPES_H */
