#ifndef RNC_ASSEMBLY_SDK_SCE_SIF_ADD_CMD_HANDLER_TYPES_H
#define RNC_ASSEMBLY_SDK_SCE_SIF_ADD_CMD_HANDLER_TYPES_H

#include "types.h"

struct M2c_temp_3_12 {
    s32 unk0;
    s32 unk4;
};

#endif /* RNC_ASSEMBLY_SDK_SCE_SIF_ADD_CMD_HANDLER_TYPES_H */
