#ifndef RNC_ASSEMBLY_SDK_DMA_IPU_GS_DISPATCH_MPEG_CALLBACK_TYPES_H
#define RNC_ASSEMBLY_SDK_DMA_IPU_GS_DISPATCH_MPEG_CALLBACK_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x40];
    s32 unk40;
};

#endif /* RNC_ASSEMBLY_SDK_DMA_IPU_GS_DISPATCH_MPEG_CALLBACK_TYPES_H */
