#ifndef RNC_ASSEMBLY_SDK_DECI_DEBUG_DECI2_PUTCHAR_TYPES_H
#define RNC_ASSEMBLY_SDK_DECI_DEBUG_DECI2_PUTCHAR_TYPES_H

#include "types.h"

struct Ent { Fp fp; int arg; int pad; };

#endif /* RNC_ASSEMBLY_SDK_DECI_DEBUG_DECI2_PUTCHAR_TYPES_H */
