#ifndef RNC_ASSEMBLY_SDK_LIBRARY_CHECKMODELVERSION_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_CHECKMODELVERSION_TYPES_H

#include "types.h"

typedef struct {
	char	pad[0x24];
	int	server;		/* 0x24 */
} Cd;

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_CHECKMODELVERSION_TYPES_H */
