#ifndef RNC_ASSEMBLY_SDK_LIBRARY_INITTHREAD_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_INITTHREAD_TYPES_H

#include "types.h"

struct M2c_D_00154508 {
    s32 unk0;
    s32 unk4;
};

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_INITTHREAD_TYPES_H */
