#ifndef RNC_ASSEMBLY_CORE_CONVERT_MULTIBYTE_CHARACTER_TYPES_H
#define RNC_ASSEMBLY_CORE_CONVERT_MULTIBYTE_CHARACTER_TYPES_H

#include "types.h"

typedef struct { char pad[0x64]; unsigned char f64; char pad2[0xB]; char *f70; } S002C2418;

#endif /* RNC_ASSEMBLY_CORE_CONVERT_MULTIBYTE_CHARACTER_TYPES_H */
