#ifndef RNC_ASSEMBLY_SDK_DECI_DEBUG_ADJUST_TIME_TYPES_H
#define RNC_ASSEMBLY_SDK_DECI_DEBUG_ADJUST_TIME_TYPES_H

#include "types.h"

struct M2c_arg0 {
    u8 pad_0[0x2];
    u8 unk2;
};

#endif /* RNC_ASSEMBLY_SDK_DECI_DEBUG_ADJUST_TIME_TYPES_H */
