#ifndef RNC_ASSEMBLY_SDK_LIBRARY_SCECDINIT_TYPES_H
#define RNC_ASSEMBLY_SDK_LIBRARY_SCECDINIT_TYPES_H

#include "types.h"

struct M2c_D_00159968 {
    u8 pad_0[0x24];
    s32 unk24;
};

#endif /* RNC_ASSEMBLY_SDK_LIBRARY_SCECDINIT_TYPES_H */
