#ifndef RNC_AUDIO_MUSIC_MUSIC_START_TRACK_60000_TYPES_H
#define RNC_AUDIO_MUSIC_MUSIC_START_TRACK_60000_TYPES_H

#include "types.h"

#include "rnc/music_stream_state.h"

#endif /* RNC_AUDIO_MUSIC_MUSIC_START_TRACK_60000_TYPES_H */
