/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/globals.h"
#include "asm.h"
#include "eetypes.h"
#include "qcopy.h"
#include "qzero.h"
#include "rnc/gameplay/entities/moby.h"

typedef union {
    u128 q;
    f32 f[4];
} DebrisVec;

typedef struct {
    u32 c[3];
} DebrisColors;

typedef struct {
    u8 pad0[0x2C];
    f32 force;
} DebrisHit;

extern DebrisColors D_L01_00161C50;
extern void *FUN_L00_0025a420_u(void *, s32, s32) __asm__("FUN_L00_0025a420");
extern s32 FUN_0022da68(s32, s32, void *);
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern void FUN_001f9bf8(void *, void *, f32);
extern void FUN_001f9a10(void *, void *, void *);
extern int FUN_L00_00257b90(int lo, int hi);
extern s32 FUN_001f96f8(s32);
extern void FUN_L00_0026ced0(void *, void *, int, int, float, int);
extern struct Moby *spawn_debris_chunk(void *, void *, s32, f32, s32, f32, f32, f32, s32) __asm__("FUN_L01_002f8530");
extern void FUN_L00_00257470(void *, s32, s32);
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");

/* Once hit hard enough: bursts into 200 smoke puffs and 40 debris chunks, then removes itself. */
void FUN_L01_002f9810(struct Moby *m) {
    DebrisHit *hit;
    s32 i;
    s32 j;
    f32 s;

    hit = FUN_L00_0025a420_u(m, 0x10000, 0);
    m->unkA4 = 0xFF;
    if (hit != NULL && hit->force > 0.0f) {
        FUN_0022da68(0, 0x10, m);
        for (i = 0; i < 200; i++) {
            /* A block of its own: retail reuses these stack slots in the next loop. */
            {
                DebrisVec vel;
                DebrisVec pos;
                DebrisVec off;

                pos.q = 0;
                pos.f[0] = random_float_between(-1.0f, 1.0f);
                pos.f[1] = random_float_between(-1.0f, 1.0f);
                pos.f[2] = random_float_between(-1.0f, 1.0f);
                off.q = 0;
                vel.q = pos.q;
                s = random_float_between(-1.0f, 1.0f);
                s *= FUN_001f9dc8(m->rot.z);
                off.f[0] = s;
                s = random_float_between(-0.3f, 0.3f);
                s *= FUN_001f9de0(m->rot.z);
                off.f[1] = s;
                off.f[2] = random_float_between(0.0f, 2.0f);
                pos.q = off.q;
                FUN_001f9a10(&pos, &pos, &m->pos);
                FUN_001f9bf8(&vel, &vel, random_float_between(0.5f, 1.5f) * frame_time);
                s = random_float_between(0.5f, 1.0f) * 210000.0f;
                FUN_L00_0026ced0(&pos, &vel, 0x5F787878, 0x181818, s, FUN_001f96f8(FUN_L00_00257b90(30, 90)));
            }
        }
        for (j = 0; j < 40; j++) {
            DebrisColors colors;
            DebrisVec vel;
            DebrisVec pos;
            DebrisVec off;

            colors = D_L01_00161C50;
            pos.q = 0;
            pos.f[0] = random_float_between(-1.0f, 1.0f);
            pos.f[1] = random_float_between(-1.0f, 1.0f);
            pos.f[2] = random_float_between(-1.0f, 1.0f);
            off.q = 0;
            vel.q = pos.q;
            s = random_float_between(-1.2f, 1.2f);
            s *= FUN_001f9dc8(m->rot.z);
            off.f[0] = s;
            s = random_float_between(-0.4f, 0.4f);
            s *= FUN_001f9de0(m->rot.z);
            off.f[1] = s;
            off.f[2] = random_float_between(0.5f, 2.0f);
            pos.q = off.q;
            FUN_001f9a10(&pos, &pos, &m->pos);
            FUN_001f9bf8(&vel, &vel, random_float_between(1.0f, 5.0f) * frame_time);
            spawn_debris_chunk(&pos, &vel, colors.c[random_integer_below(3)], random_float_between(0.04f, 0.09f),
                               FUN_L00_00257b90(60, 180), 1.0f, 1.0f, 0.75f, 0);
        }
        FUN_L00_00257470(m, 0, -1);
        mark_moby_for_removal(m);
    }
}
typedef struct {
    f32 sway;
    f32 dir;
    s32 timer;
} SwayVars;

typedef struct {
    u8 pad0[0x10];
    u8 pos[0x10];
    u8 state;
    u8 pad21[0x27];
    f32 rotz;
    u8 pad4c[0x2C];
    SwayVars *pvars;
} SwayMoby;

typedef struct {
    s64 t;
    u8 pad8[8];
    void *moby;
    s32 flags;
    s32 x18;
    s32 x1c;
    s32 x20;
} CollQuery;

extern void FUN_L00_0025d1b8();
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 FUN_001160d8(void);
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern void FUN_L00_001f2868(void *, s32, void *, void *, f32);
extern s32 FUN_001f9740(void *);
extern s32 FUN_001f96f8(s32);
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");

void FUN_L01_002f9bf0(SwayMoby *m) {
    SwayVars *v;
    CollQuery q;

    v = m->pvars;
    if (m->state == 0) {
        FUN_L00_0025d1b8(m);
        m->state = 1;
        v->sway = random_float_between(-1.0f, 1.0f);
        v->dir = (FUN_001160d8() & 1) ? 1.0f : -1.0f;
    }
    q.moby = m;
    q.flags = 0x10001;
    q.x1c = 0;
    clear_u64_value(&q);
    q.x20 = 0;
    FUN_L00_001f2868(m->pos, 0x10, m, &q, 1.2f);
    if (v->dir == v->sway) {
        if (FUN_001f9740(&v->timer)) {
            v->dir = -v->dir;
            v->timer = FUN_001f96f8(0x5A);
        }
    }
    v->sway += frame_time * 4.0f * v->dir;
    if (v->sway > 1.0f) {
        v->sway = 1.0f;
    }
    if (v->sway < -1.0f) {
        v->sway = -1.0f;
    }
    m->rotz = fast_add_rotations(m->rotz, frame_time * -12.566371f * v->sway);
}
typedef union {
    u128 q;
    f32 f[4];
} BurstVec;

typedef struct {
    u32 c[3];
} BurstColors;

typedef struct {
    u8 pad0[0xA6];
    s16 oclass;
} BurstClassMoby;

typedef struct {
    u8 pad0[0x20];
    BurstClassMoby *moby;
} BurstTarget;

typedef struct {
    u8 pad0[0x10];
    BurstVec pos;
    u8 pad20[0x84];
    u8 bA4;
    u8 padA5[0xD];
    s16 id;
} BurstMoby;

extern s32 D_0015ED84_e[] __asm__("D_0015ED80") __attribute__((section(".sdata")));
extern s32 D_0014C190[][64];
extern s32 D_L01_001BA950[];
typedef struct {
    u8 pad0[0x454];
    u8 collected[1];
} BurstLevelState;
extern BurstLevelState D_L01_001BB6B0;
extern BurstColors D_L01_00161C60;
extern void *FUN_L00_0025a420_u(void *, s32, s32) __asm__("FUN_L00_0025a420");
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern void FUN_001f9bf8(void *, void *, f32);
extern void FUN_001f9a10(void *, void *, void *);
extern int FUN_L00_00257b90(int lo, int hi);
extern void FUN_L01_002f8530(void *, void *, u32, s32, f32, f32, f32, f32, s32);

void FUN_L01_002f9d80(BurstMoby *self) {
    BurstTarget *t;
    BurstColors colors;
    BurstVec dir;
    BurstVec pos;
    f32 r;
    f32 ang;
    s32 i;

    t = FUN_L00_0025a420_u(self, 0x830000, 0);
    if (D_L01_001BB6B0.collected[self->id] != 0 ||
        (D_0014C190[current_level_index][self->id >> 5] >> (self->id & 0x1F)) & 1) {
        mark_moby_for_removal(self);
    }
    if (t != NULL && t->moby->oclass == 0x2AE) {
        for (i = 0; i < 20; i++) {
            colors = D_L01_00161C60;
            pos.q = 0;
            pos.f[0] = random_float_between(-frame_time, frame_time);
            pos.f[1] = random_float_between(-frame_time, frame_time);
            pos.f[2] = random_float_between(-frame_time, frame_time);
            dir.q = pos.q;
            r = random_float_between(2.0f, 3.0f);
            ang = random_angle_radians();
            pos.f[0] = FUN_001f9dc8(ang) * r;
            pos.f[1] = FUN_001f9de0(ang) * r;
            pos.f[2] = 0.0f;
            FUN_001f9bf8(&dir, &dir, random_float_between(frame_time * 5.0f, frame_time * 20.0f));
            FUN_001f9a10(&pos, &pos, &self->pos);
            FUN_L01_002f8530(&pos, &dir, colors.c[random_integer_below(3)],
                             FUN_L00_00257b90(0xB4, 0x12C), 0.05f, 1.0f, 1.0f, 0.75f, 0);
        }
        D_0014C190[D_0015ED84_e[1]][self->id >> 5] |= 1 << (self->id & 0x1F);
        D_L01_001BA950[self->id >> 5] |= 1 << (self->id & 0x1F);
        mark_moby_for_removal(self);
    } else {
        self->bA4 = 0xFF;
    }
}
typedef struct {
    u128 target;
    s32 owner;
    s32 color;
} BeamVars;

typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0xC];
    f32 scale;
    u8 b30;
    u8 b31;
    s16 h32;
    u8 pad34[0xC];
    f32 rx;
    f32 ry;
    f32 rz;
    u8 pad4c[0x2C];
    BeamVars *pvars;
} BeamMoby;

extern void *spawn_beam_moby(s32 oclass) __asm__("FUN_0020c4f8");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
void FUN_L00_002502f0(void *, s32, s32, s32);
void FUN_L00_0026daa0(void *, u32, s32, s32, f32);
extern void FUN_L00_00250df8();

BeamMoby *FUN_L01_002fa068(s32 owner, u128 *pos, u128 *target, s32 color) {
    u128 p;
    u128 t;
    BeamMoby *m;
    BeamVars *v;
    u128 *pp;
    u128 *tp;

    pp = &p;
    tp = &t;
    p = *pos;
    t = *target;
    m = spawn_beam_moby(0x2D2);
    if (m != 0) {
        v = m->pvars;
        v->owner = owner;
        m->b30 = 0x7F;
        m->h32 = 0x7F;
        m->b31 = 1;
        m->scale *= 0.5f;
        FUN_L00_002502f0(m, 0x7F, 0x7F, 0x7F);
        m->rx = random_angle_radians();
        m->ry = random_angle_radians();
        m->rz = random_angle_radians();
        qcopy(&m->pos, pp);
        qcopy(&v->target, tp);
        v->color = color;
        FUN_L00_0026daa0(m, 0x2F00007F, color, -1, 210000.0f);
        FUN_L00_0026daa0(m, 0x4F004F7F, v->color, -1, 115500.0f);
        FUN_L00_00250df8(m);
    }
    return m;
}

/*
 * Explosion burst at `where` (uses the unit's BurstVec): three particles in
 * random colours from two six-colour palettes, two FUN_L00_002ac910 effects
 * on `moby`, its sound unless the moby is dying (state 0xFD/0xFE), and a
 * light flash of brightness `light` (negative: 13).
 */
typedef struct {
    u32 c[6];
} BurstPalette;

/* Light used by the flash; FUN_L00_002d3838 places it at a position. */
typedef struct {
    u8 pad_00[0x20];
    f32 r;
    f32 g;
    f32 b;
} BurstLight;

extern BurstPalette D_L01_0020B4F0;   /* inner colours */
extern BurstPalette D_L01_0020B508;   /* outer colours */
extern BurstLight D_L01_001E3440;
extern void clear_vector(void *) __asm__("FUN_001f99f8");
extern int random_int_between(int lo, int hi) __asm__("FUN_L00_00257b90");
extern void FUN_L00_0026a9f0(void *, void *, u32, u32, f32, s32, s32, f32, s32, s32);
/* s32 return is load-bearing: a void prototype changes the code */
extern s32 FUN_L00_002ac910(void *, void *, void *, f32, s32, s32, s32, s32, s32);
/* allocate_voice_for_target_entry; the unit declares it under this name */
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_L00_002d3838(void *, void *, s32, s32);

void FUN_L01_002fa1b0(struct Moby *moby, u128 *where, s32 sound, f32 scale, f32 light)
{
    BurstVec pos;
    BurstVec vel;
    BurstPalette inner;
    BurstPalette outer;
    BurstPalette *inner_p;
    BurstVec *pos_p;
    f32 size;
    f32 speed;
    s32 i;

    /* pos and inner are used through pointers, as in retail */
    pos_p = &pos;
    pos.q = *where;
    clear_vector(&vel);
    inner_p = &inner;
    for (i = 2; i >= 0; i--) {
        speed = random_float_between(8.0f, 10.0f) * frame_time;
        size = scale * 400000.0f;
        inner = D_L01_0020B4F0;
        outer = D_L01_0020B508;
        FUN_L00_0026a9f0(pos_p, &vel,
                         inner_p->c[random_integer_below(6)], outer.c[random_integer_below(6)],
                         size,
                         random_int_between(FUN_001f96f8(0xF), FUN_001f96f8(0x14)),
                         random_int_between(FUN_001f96f8(0x19), FUN_001f96f8(0x1E)),
                         speed * scale, 0, 0);
    }

    if (moby != 0) {
        FUN_L00_002ac910(moby, pos_p, &vel, scale + scale, FUN_001f96f8(0x14), 0x7F, 0, 0x40, 0x30);
        FUN_L00_002ac910(moby, pos_p, &vel, scale * 1.5f, FUN_001f96f8(0x1D), 0x20, 0, 0x20, 0);
        if (moby->state != 0xFE) {
            if (moby->state != 0xFD && sound != -1) {
                FUN_0022da68(sound, 0, moby);
            }
        }
    }

    if (light != 0.0f) {
        if (light > 0.0f) {
            D_L01_001E3440.g = light;
            D_L01_001E3440.b = light;
            D_L01_001E3440.r = light;
        } else {
            D_L01_001E3440.g = 13.0f;
            D_L01_001E3440.b = 13.0f;
            D_L01_001E3440.r = 13.0f;
        }
        FUN_L00_002d3838(&D_L01_001E3440, pos_p, 0, 0);
    }
}
#include "rnc/math/vector.h"
#include "rnc/overlay/quad.h"

typedef struct {
    u128 vel;
    void *coll;
    u8 sound[4];
} DropVars;

typedef struct {
    u8 pad0[0x10];
    Vec4 pos;
    u8 pad20[0x58];
    DropVars *vars;
    u8 pad7C[0x2A];
    u16 hA6;
} DropMoby;

typedef struct {
    u128 dir;
    DropMoby *owner;
    s32 flags;
    u8 b28;
    u8 b29;
    u16 id;
    f32 scale;
    s32 count;
} DropProbe;

extern f32 FUN_001f96b0(f32);
extern void FUN_001f9a10(void *, void *, void *);
extern f32 FUN_001f9b80(void *, void *);
extern s32 FUN_001efa68(void *, void *, s32, void *, void *);
extern s32 probe_world_sphere(f32, void *, s32, void *, void *) __asm__("FUN_L00_001f2868");
void FUN_L01_002fa1b0(struct Moby *moby, u128 *where, s32 sound, f32 scale, f32 light);
void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern u8 D_L01_00167240[];
extern u128 D_L01_001742E0;

void FUN_L01_002fa4c0(DropMoby *m) {
    DropVars *v;
    u128 *pos;
    Vec4 prev;
    DropProbe probe;
    u128 tmp;
    f32 a;
    f32 b;
    f32 zero;
    f32 one;
    f32 ten;
    f32 half;

    v = m->vars;
    pos = &m->pos.q;
    qcopy(&prev, pos);
    zero = 0.0f;
    one = 1.0f;
    ten = 10.0f;
    a = FUN_001f96b0(ten);
    b = FUN_001f96b0(ten);
    b = b * FUN_001f96b0(ten);
    ((f32 *)&v->vel)[2] -= (a * zero + one) * 2.0f / b;
    FUN_001f9a10(pos, pos, &v->vel);
    if (m->pos.f[0] < zero || m->pos.f[1] < zero || m->pos.f[2] < zero ||
        FUN_001f9b80(pos, D_L01_00167240) > 64.0f) {
        mark_moby_for_removal(m);
        return;
    }
    probe.owner = m;
    probe.flags = 0x10001;
    probe.scale = one;
    probe.count = 1;
    qcopy(&probe.dir, &v->vel);
    ((f32 *)&probe.dir)[2] = one;
    ((f32 *)&probe.dir)[3] = 5627.9248f;
    probe.b28 = 1;
    probe.b29 = 1;
    probe.id = m->hA6;
    if (FUN_001f9740(v->sound) != 0) {
        tmp = m->pos.q;
        FUN_L01_002fa1b0(m, &tmp, 0, 0.5f, zero);
        mark_moby_for_removal(m);
    } else if (FUN_001efa68(&prev, pos, 0, v->coll, &probe) != 0) {
        qcopy(pos, &D_L01_001742E0);
        tmp = m->pos.q;
        FUN_L01_002fa1b0(m, &tmp, 0, 0.5f, zero);
        mark_moby_for_removal(m);
    } else {
        half = 0.5f;
        if (probe_world_sphere(half, pos, 0x10, v->coll, &probe) != 0) {
            tmp = m->pos.q;
            FUN_L01_002fa1b0(m, &tmp, 0, half, zero);
            mark_moby_for_removal(m);
        }
    }
}
extern DebrisColors D_L01_00161C70;
extern u8 D_0013D388[];

/* Removed once collected; when hit, bursts into 500 smoke puffs and 100 chunks, marks itself collected and sets D_0013D388[0xE] (an item-availability flag). */
void FUN_L01_002fa800(struct Moby *m) {
    s32 i;
    s32 j;
    f32 s;

    if (D_L01_001BB6B0.collected[(s16)m->save_id] != 0 ||
        (D_0014C190[current_level_index][(s16)m->save_id >> 5] >> (m->save_id & 0x1F)) & 1) {
        mark_moby_for_removal(m);
        return;
    }
    if (FUN_L00_0025a420_u(m, 0x800000, 0) != NULL) {
        FUN_0022da68(0, 0, m);
        for (i = 0; i < 500; i++) {
            /* A block of its own: retail reuses these stack slots in the next loop. */
            {
                DebrisVec vel;
                DebrisVec pos;
                DebrisVec off;

                pos.q = 0;
                pos.f[0] = random_float_between(-1.0f, 1.0f);
                pos.f[1] = random_float_between(-1.0f, 1.0f);
                pos.f[2] = random_float_between(-1.0f, 1.0f);
                off.q = 0;
                vel.q = pos.q;
                s = random_float_between(-4.0f, 4.0f);
                s *= FUN_001f9dc8(m->rot.z);
                off.f[0] = s;
                s = random_float_between(-1.0f, 1.0f);
                s *= FUN_001f9de0(m->rot.z);
                off.f[1] = s;
                off.f[2] = random_float_between(0.0f, 8.0f);
                pos.q = off.q;
                FUN_001f9a10(&pos, &pos, &m->pos);
                FUN_001f9bf8(&vel, &vel, random_float_between(1.5f, 3.5f) * frame_time);
                s = random_float_between(1.5f, 3.5f) * 210000.0f;
                FUN_L00_0026ced0(&pos, &vel, 0x5F787878, 0x181818, s, FUN_001f96f8(FUN_L00_00257b90(120, 240)));
            }
        }
        for (j = 0; j < 100; j++) {
            DebrisColors colors;
            DebrisVec vel;
            DebrisVec pos;
            DebrisVec off;

            colors = D_L01_00161C70;
            pos.q = 0;
            pos.f[0] = random_float_between(-1.0f, 1.0f);
            pos.f[1] = random_float_between(-1.0f, 1.0f);
            pos.f[2] = random_float_between(-1.0f, 1.0f);
            off.q = 0;
            vel.q = pos.q;
            s = random_float_between(-4.0f, 4.0f);
            s *= FUN_001f9dc8(m->rot.z);
            off.f[0] = s;
            s = random_float_between(-1.0f, 1.0f);
            s *= FUN_001f9de0(m->rot.z);
            off.f[1] = s;
            off.f[2] = random_float_between(1.0f, 8.0f);
            pos.q = off.q;
            FUN_001f9a10(&pos, &pos, &m->pos);
            FUN_001f9bf8(&vel, &vel, random_float_between(1.0f, 5.0f) * frame_time);
            spawn_debris_chunk(&pos, &vel, colors.c[random_integer_below(3)], random_float_between(0.05f, 0.15f),
                               FUN_L00_00257b90(60, 180), 1.0f, 1.0f, 0.75f, 0);
        }
        D_0014C190[current_level_index][(s16)m->save_id >> 5] |= 1 << (m->save_id & 0x1F);
        D_L01_001BA950[(s16)m->save_id >> 5] |= 1 << (m->save_id & 0x1F);
        D_0013D388[0xE] = 1;
        mark_moby_for_removal(m);
    }
}
typedef struct {
    u8 pad0[0xA6];
    s16 type;
} Moby;

typedef struct {
    u8 pad0[0x44];
    s16 count;
    u8 pad46[0x178 - 0x46];
    Moby *list[1];
} MobyList;

typedef struct {
    u8 b0;
    u8 active;
    u8 pad2[0x1E];
    f32 x;
    f32 y;
    f32 z;
} Effect;

extern s32 D_L01_0015F5C4;
extern u8 D_0015EDB0;
extern MobyList D_L01_0016CCE0;
extern Effect D_L01_0017C8C0;
extern void attach_manipulator(void *, int, void *) __asm__("FUN_0020cb10");

void FUN_L01_002fac80(void) {
    s32 i;

    if (D_L01_0015F5C4 == 2 && D_0015EDB0 != 0) {
        for (i = 0; i < D_L01_0016CCE0.count; i++) {
            if (D_L01_0016CCE0.list[i]->type == 0x32B && D_L01_0017C8C0.active == 0) {
                attach_manipulator(D_L01_0016CCE0.list[i], 0, &D_L01_0017C8C0);
                D_L01_0017C8C0.z = D_L01_0017C8C0.y = D_L01_0017C8C0.x = 2.75f;
            }
        }
    }
}
#include "qcopy.h"
#include "sda.h"

/* Agnogg ship update (moby classes 730, 731, 790 on level 01): state machine on moby->state. */
/* Ported from rac1-decomp (src/overlays/l01_novalis/vendor_002FABE8.c: func_L01_002FC140), where it is exact; names translated to the US level program. */

typedef struct { float x, y, z, w; } V4_2FC140;
typedef struct { int pad0[4]; int f10; } Class_2FC140;
typedef struct {
    /* 0x00 */ char pad0[0x10];
    /* 0x10 */ V4_2FC140 v;
    /* 0x20 */ int pad20;
    /* 0x24 */ int rec;
    /* 0x28 */ int pad28;
    /* 0x2C */ int timer;
} Link_2FC140;
typedef struct {
    /* 0x00 */ char pad0[0x10];
    /* 0x10 */ V4_2FC140 pos;
    /* 0x20 */ unsigned char state;
    /* 0x21 */ char pad21[3];
    /* 0x24 */ Class_2FC140 *pclass;
    /* 0x28 */ char pad28[8];
    /* 0x30 */ unsigned char f30;
    /* 0x31 */ char pad31;
    /* 0x32 */ unsigned short f32;
    /* 0x34 */ unsigned short flags;
    /* 0x36 */ char pad36[0x1C];
    /* 0x52 */ unsigned char f52;
    /* 0x53 */ unsigned char f53;
    /* 0x54 */ char pad54[0x1C];
    /* 0x70 */ unsigned char f70;
    /* 0x71 */ char pad71[7];
    /* 0x78 */ void *data;
    /* 0x7C */ char pad7C[0x18];
    /* 0x94 */ int f94;
    /* 0x98 */ char pad98[0xE];
    /* 0xA6 */ short oclass;
    /* 0xA8 */ char padA8[8];
    /* 0xB0 */ unsigned char fB0;
    /* 0xB1 */ char padB1;
    /* 0xB2 */ short fB2;
    /* 0xB4 */ char padB4[8];
    /* 0xBC */ unsigned char fBC;
    /* 0xBD */ char padBD[0x43];
} Moby_2FC140;
typedef struct {
    /* 0x00 */ float f0;
    /* 0x04 */ int link;
    /* 0x08 */ short timer;
    /* 0x0A */ short fA;
    /* 0x0C */ float fC;
    /* 0x10 */ int f10;
    /* 0x14 */ int list[7];
    /* 0x30 */ int rec;
    /* 0x34 */ int f34;
    /* 0x38 */ int f38;
    /* 0x3C */ int f3C;
} Data_2FC140;
typedef struct {
    /* 0x00 */ char pad0[0x30];
    /* 0x30 */ V4_2FC140 a;
    /* 0x40 */ char pad40[0x30];
    /* 0x70 */ V4_2FC140 b;
} Rec_2FC140;
typedef struct { unsigned char pad0[0x454]; unsigned char collected[1]; } Lv_2FC140;
extern Moby_2FC140 *D_L01_00160058_2FC140 __asm__("D_L01_0015FFD8") MACRO_ADDR;
extern Rec_2FC140 *D_L01_0016016C_2FC140 __asm__("D_L01_001600EC") MACRO_ADDR;
extern float D_0015EE6C_2FC140 __asm__("D_0015ED6C") MACRO_ADDR;
extern int D_L01_0015F6A8_2FC140 __asm__("D_L01_0015F5C4") MACRO_ADDR;
extern int D_0015EE84_2FC140 __asm__("D_0015ED84") MACRO_ADDR;
extern char D_L01_001BAD60_2FC140[] __asm__("D_L01_001BAA50");
extern Lv_2FC140 D_L01_001BB9C0_2FC140 __asm__("D_L01_001BB6B0");
extern unsigned char D_L01_0015FD08_2FC140[] __asm__("D_L01_0015FC88") MACRO_ADDR;
extern char D_L01_001BADB0_2FC140[] __asm__("D_L01_001BAAA0");
extern unsigned char D_0014C050_u[] __asm__("D_0014C050");
extern char D_0013F3D0_u[] __asm__("D_0013F3D0");
extern int D_001413DC_u[] __asm__("D_001413DC");
extern unsigned char D_0013D388_u[] __asm__("D_0013D388");
extern void func_L01_002FC058_2FC140(void) __asm__("FUN_L01_002fac80");
extern int func_001F9938_2FC140(void *) __asm__("FUN_001f9770");
extern int scale_game_frames(int) __asm__("FUN_001f96f8");
extern void blend_moby_animation(void *, int, int, int) __asm__("FUN_00212f90");
extern void func_L00_00299B68_2FC140(int) __asm__("FUN_L00_00298840");
extern void func_L00_0028FC68_2FC140(void) __asm__("FUN_L00_0028e990");
extern int func_00215570_2FC140(void *, int) __asm__("FUN_00214720");
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern float func_001F9D48_2FC140(void *, void *) __asm__("FUN_001f9b80");
extern float func_L00_001FF860_2FC140(float, float) __asm__("FUN_001f9e90");
extern void set_moby_animation(void *, int, int) __asm__("FUN_00212ed8");
extern void func_L00_0029A7D0_2FC140(int) __asm__("FUN_L00_00299460");
extern void func_L00_00261848_2FC140(int) __asm__("FUN_L00_002607d0");
extern void func_L00_00263DB0_2FC140(int) __asm__("FUN_L00_00262d38");
extern void func_L01_0029C2A0_2FC140(void *, int, void *, int, void *) __asm__("FUN_L01_0029b0a0");
extern void func_L00_002512D8_2FC140(int) __asm__("FUN_L00_002502a0");
extern void func_L00_00286128_2FC140(void *, void *) __asm__("FUN_L00_00284e50");
extern int func_0020BFC8_2FC140(int, int) __asm__("FUN_0020b178");
extern void func_L01_002A3680_2FC140(void) __asm__("FUN_L01_002a2480");

void FUN_L01_002fad68(Moby_2FC140 *moby) {
    Data_2FC140 *data;
    Link_2FC140 *q;
    int r16;
    int cnt;
    int flag;
    int i;
    int n4;
    float fz;
    float fd;

    data = moby->data;
    func_L01_002FC058_2FC140();
    func_001F9938_2FC140(&data->timer);
    switch (moby->state) {
    case 0:
        fz = moby->pos.z - 0.75f;
        moby->f30 = 0xFF;
        moby->state = 1;
        data->timer = 0;
        fd = data->f0;
        data->fC = fz;
        moby->f94 = 0;
        moby->flags = moby->flags | 0x41;
        moby->pos.z = moby->pos.z + fd;
        break;
    case 1:
        r16 = *(unsigned char *)(moby->fB0 + (D_0015EE84_2FC140 << 4) + D_0014C050_u);
        if (r16 == 0xFF) {
            if (moby->f53 != 2) {
                blend_moby_animation(moby, 2, 0, scale_game_frames(0x14));
            }
            moby->state = 10;
            moby->flags = moby->flags & 0xFFBE;
            moby->f32 = r16;
            moby->f94 = moby->pclass->f10;
        } else {
            if (D_L01_0015F6A8_2FC140 == 0) {
                unsigned char *pp = D_0013D388_u;
                if (pp[0xF] == 0) {
                    func_L00_00299B68_2FC140(5);
                    pp[0xF] = 1;
                }
            }
            func_L00_0028FC68_2FC140();
            if (func_00215570_2FC140(D_0013F3D0_u, data->f10) != 0) {
                moby->flags = moby->flags & 0xFFBE;
                moby->f94 = moby->pclass->f10;
                if (data->link != -1) {
                    q = D_L01_00160058_2FC140[data->link].data;
                    q->timer = scale_game_frames(0x1A4);
                    D_L01_00160058_2FC140[data->link].fBC = 1;
                    clear_u64_value(&D_L01_0016016C_2FC140[q->rec].b);
                    clear_u64_value(&q->v);
                    D_L01_0016016C_2FC140[q->rec].b.y = -func_L00_001FF860_2FC140(
                        func_001F9D48_2FC140(&D_L01_0016016C_2FC140[q->rec].a, &moby->pos),
                        moby->pos.z - D_L01_0016016C_2FC140[q->rec].a.z);
                    D_L01_0016016C_2FC140[q->rec].b.z = func_L00_001FF860_2FC140(
                        moby->pos.x - D_L01_0016016C_2FC140[q->rec].a.x,
                        moby->pos.y - D_L01_0016016C_2FC140[q->rec].a.y);
                }
                moby->state = 2;
            }
        }
        break;
    case 2:
        moby->pos.z = moby->pos.z - D_0015EE6C_2FC140 * 5.0f;
        if (data->link != -1) {
            q = D_L01_00160058_2FC140[data->link].data;
            q->v.y = -func_L00_001FF860_2FC140(
                func_001F9D48_2FC140(&D_L01_0016016C_2FC140[q->rec].a, &moby->pos),
                moby->pos.z - D_L01_0016016C_2FC140[q->rec].a.z);
            q->v.z = func_L00_001FF860_2FC140(
                moby->pos.x - D_L01_0016016C_2FC140[q->rec].a.x,
                moby->pos.y - D_L01_0016016C_2FC140[q->rec].a.y);
        }
        if (moby->f53 == 0) {
            if (moby->pos.z - data->fC <= 0.0f) {
                set_moby_animation(moby, 1, 0);
            }
        }
        if (moby->pos.z <= data->fC) {
            moby->pos.z = data->fC;
            moby->state = 3;
        }
        break;
    case 3:
        if (moby->f52 != 1) {
            break;
        }
        if ((moby->f70 & 2) == 0) {
            break;
        }
        if (moby->f53 != 2) {
            blend_moby_animation(moby, 2, 0, scale_game_frames(0x14));
        }
        if (moby->oclass == 0x2DA) {
            moby->state = 10;
        } else {
            moby->state = 4;
        }
        break;
    case 4:
        flag = 1;
        cnt = 0;
        i = 0;
        do {
            if (data->list[i] != -1 && (char *)D_L01_00160058_2FC140 + (data->list[i] << 8) != 0
                && ((Moby_2FC140 *)((char *)D_L01_00160058_2FC140 + (data->list[i] << 8)))->state != 0xFE
                && ((Moby_2FC140 *)((char *)D_L01_00160058_2FC140 + (data->list[i] << 8)))->state != 0xFD) {
                flag = 0;
                break;
            }
            cnt++;
            i++;
        } while (cnt < 3);
        if (flag == 0) {
            break;
        }
        n4 = D_001413DC_u[0];
        if (n4 == 7) {
            break;
        }
        if (n4 == 0x14) {
            break;
        }
        data->timer = scale_game_frames(0x2D);
        moby->state = 5;
        break;
    case 5:
        if (data->timer != 0) {
            break;
        }
        data->fA = moby->f32;
        moby->flags = moby->flags | 0x41;
        func_L00_00299B68_2FC140(3);
        moby->state = 6;
        break;
    case 6:
        if (D_L01_0015F6A8_2FC140 == 2) {
            break;
        }
        func_L00_0029A7D0_2FC140(3);
        moby->state = 7;
        break;
    case 7:
        if (D_L01_0015F6A8_2FC140 == 2) {
            break;
        }
        func_L00_00299B68_2FC140(4);
        moby->state = 8;
        break;
    case 8:
        if (D_L01_0015F6A8_2FC140 == 2) {
            break;
        }
        func_L00_00261848_2FC140(3);
        func_L00_00263DB0_2FC140(3);
        moby->flags = moby->flags & 0xFFBE;
        if (data->link != -1) {
            ((Lv_2FC140 *)D_L01_001BAD60_2FC140)->collected[D_L01_00160058_2FC140[data->link].fB2] = D_L01_00160058_2FC140[data->link].fB0 + 2;
            if (D_L01_00160058_2FC140[data->link].fB0 == 0xFF
                || (D_L01_0015FD08_2FC140[D_L01_00160058_2FC140[data->link].fB0] != 0xFF
                    && D_0014C050_u[D_L01_00160058_2FC140[data->link].fB0 + (D_0015EE84_2FC140 << 4)] == 0xFF)) {
                D_L01_001BB9C0_2FC140.collected[D_L01_00160058_2FC140[data->link].fB2] = D_L01_00160058_2FC140[data->link].fB0 + 2;
            }
        }
        if (data->f3C != -1) {
            q = D_L01_00160058_2FC140[data->f3C].data;
            q->timer = scale_game_frames(0xB4);
            D_L01_00160058_2FC140[data->f3C].fBC = 1;
            if (data->f34 != -1 && data->f38 != -1) {
                D_L01_00160058_2FC140[data->f34].fBC = 2;
                D_L01_00160058_2FC140[data->f38].fBC = 2;
                func_L01_0029C2A0_2FC140(&D_L01_00160058_2FC140[data->f34].fBC, 1, &D_L01_00160058_2FC140[data->f34], 1, D_L01_001BADB0_2FC140);
                func_L01_0029C2A0_2FC140(&D_L01_00160058_2FC140[data->f38].fBC, 1, &D_L01_00160058_2FC140[data->f38], 1, D_L01_001BADB0_2FC140);
            }
        }
        func_L00_002512D8_2FC140(moby->fB0);
        if (data->rec != -1) {
            func_L00_00286128_2FC140(&D_L01_0016016C_2FC140[data->rec].a, &D_L01_0016016C_2FC140[data->rec].b);
        }
        func_0020BFC8_2FC140(0, -1);
        func_L01_002A3680_2FC140();
        moby->state = 10;
        break;
    case 10:
        moby->pos.z = data->fC;
        break;
    }
}
typedef union {
    u128 q;
    f32 f[4];
} PendVec4;

typedef struct {
    u8 pad0[0x60];
    PendVec4 pivot;
    f32 swing;
    s32 sound;
} PendulumVars;

typedef struct {
    u8 pad0[0x10];
    PendVec4 pos;
    u8 state;
    u8 pad21[0x23];
    f32 rot_x;
    f32 rot_z;
    u8 pad4c[0x2C];
    PendulumVars *vars;
    u8 pad7c[0x34];
    u8 id;
    u8 padB1[0xB];
    u8 trigger;
} PendulumMoby;

extern u8 D_0014C050[];
extern u8 D_0013E550[];
extern int FUN_L00_0028d8c0(void *, int);
extern void release_voice_slot(int) __asm__("FUN_0022d798");
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_001f9a10(void *, void *, void *);
extern f32 FUN_001f9dc8(f32);
extern f32 FUN_001f9de0(f32);

void FUN_L01_002fb8a8(PendulumMoby *self) {
    PendulumVars *v;
    PendVec4 arm;
    PendVec4 d;
    s32 h;
    u8 *voice;

    v = self->vars;
    switch (self->state) {
    case 0:
        qcopy(&v->pivot, &self->pos);
        v->swing = 1.0f;
        self->state = 1;
        v->sound = -1;
        break;
    case 1:
        if (self->trigger == 2 || D_0014C050[self->id + current_level_index * 16] == 0xFF) {
            self->state = 2;
            self->trigger = 0;
        }
        break;
    case 2:
        v->swing -= frame_time * 0.5f;
        if (v->swing < 0.0f) {
            v->swing = 0.0f;
        }
        if (v->swing == 0.0f) {
            h = v->sound;
            if (h != -1) {
                voice = D_0013E550 + h * 0x70;
                if (*(void **)(voice + 0x88) == self && voice[0x74] != 0) {
                    release_voice_slot(h);
                }
            }
            v->sound = -1;
            self->state = 1;
        } else if (!FUN_L00_0028d8c0(self, v->sound)) {
            v->sound = FUN_0022da68(0, 4, self);
        }
        break;
    }
    self->rot_x = v->swing * 0.62831855f;
    arm.q = 0;
    arm.f[2] = -11.0f;
    FUN_001f9a10(&arm, &arm, &v->pivot);
    d.f[0] = FUN_001f9dc8(self->rot_z) * 11.0f * FUN_001f9de0(self->rot_x);
    d.f[1] = FUN_001f9de0(self->rot_z) * 11.0f * FUN_001f9de0(self->rot_x);
    d.f[2] = FUN_001f9dc8(self->rot_x) * 11.0f;
    FUN_001f9a10(&self->pos, &arm, &d);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_002fd0e8.s", FUN_L01_002fd0e8);
typedef struct {
    f32 x, y, z, w;
} SparkVec;

typedef struct {
    u8 pad0[0x24];
    f32 radius;
} SparkClass;

typedef struct {
    u8 pad0[0x10];
    SparkVec pos;
    u8 state;
    u8 pad21[3];
    SparkClass *pclass;
    u8 pad28[4];
    f32 scale;
} SparkMoby;

typedef struct {
    u8 pad0[0x2C];
    f32 f2c;
} SparkHit;

extern s32 D_L01_0015F580;
void *FUN_L00_0025a420_u(void *, s32, s32) __asm__("FUN_L00_0025a420");
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_L01_002787a0();
extern void *FUN_L00_00263fd8(void *, s32, void *, void *, s32, s32, void *, void *, f32, void *);
extern void FUN_L01_00278e20();
void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern void FUN_001f9a10(void *, void *, void *);

void FUN_L01_002fd9a0(SparkMoby *m) {
    SparkHit *hit;
    s32 flag;
    s32 i;
    f32 ang;
    f32 s;
    SparkVec off;
    SparkVec rot;

    flag = 0;
    hit = FUN_L00_0025a420_u(m, 0x10000, 0);
    switch (m->state) {
    case 0:
        m->state = 1;
        break;
    case 1:
        if (hit != 0 && hit->f2c > 0.0f) {
            flag = 1;
        }
        if (flag) {
            m->state = 2;
        }
        break;
    case 2:
        FUN_0022da68(0, 0, m);
        FUN_L01_002787a0(m);
        s = m->scale / m->pclass->radius;
        for (i = 0; i < 4; i++) {
            ang = (f32)i * 1.5707964f;
            clear_u64_value(&rot);
            rot.z = fast_add_rotations(ang, 0.87266463f);
            off.x = FUN_001f9dc8(ang) * -0.57f * s;
            off.y = FUN_001f9de0(ang) * -0.57f * s;
            off.z = 0.0f;
            FUN_001f9a10(&off, &off, &m->pos);
            off.z += s * 1.2f;
            FUN_L00_00263fd8(m, 0x719, &off, &rot, 0, 0, &D_L01_0015F580, &D_L01_0015F580, 0.0f,
                             &D_L01_0015F580);
        }
        FUN_L01_00278e20(m, 0x718);
        mark_moby_for_removal(m);
        break;
    }
}
/* The four scrolling layers FUN_L01_002feb28 draws (0x60 bytes each, the ScrollLayer layout of 002b96e0.c). */
typedef struct {
    Vec4 *verts;
    u8 pad4[8];
    s32 count;
    u8 pad10[0x4C];
    f32 glow;
} WaterLayer;

extern WaterLayer D_L01_001FBC80[];
extern s32 D_L01_00161CE0 __attribute__((sda));
extern s32 D_L01_0015F5CC;
extern f32 FUN_001fa6c0(s32);
extern f32 FUN_001f9de0(f32);
extern void FUN_L01_002feb28(void);
extern int enqueue_callback_2518(void (*)(void), void *) __asm__("FUN_001f4600");

/* On first use, lowers and ripples the layers' vertices; every frame, pulses their glow and queues FUN_L01_002feb28. */
void FUN_L01_002feb58(void *arg) {
    s32 i;
    s32 g;
    s32 j;
    s32 k;
    s32 n;
    s32 m;
    Vec4 *v;
    Vec4 *w;
    f32 s;

    if (D_L01_00161CE0 == 0) {
        D_L01_00161CE0 = 1;
        for (i = 0; i < 4; i++) {
            v = (D_L01_001FBC80 + i)->verts;
            for (j = 0; j < (D_L01_001FBC80 + i)->count; j++) {
                v->f[3] = v->f[2] = v->f[2] - 0.45f;
                v++;
            }
        }
        k = 1;
        for (n = 0; n < 4; n++) {
            k--;
            w = (D_L01_001FBC80 + n)->verts;
            for (m = 0; m < (D_L01_001FBC80 + n)->count; m += 2) {
                if (k & 1) {
                    w[0].f[2] += 0.05f;
                    w[0].f[3] -= 0.05f;
                    w[1].f[2] -= 0.05f;
                    w[1].f[3] += 0.05f;
                } else {
                    w[0].f[2] -= 0.05f;
                    w[0].f[3] += 0.05f;
                    w[1].f[2] += 0.05f;
                    w[1].f[3] -= 0.05f;
                }
                w += 2;
                k++;
            }
        }
    }
    s = FUN_001f9de0((FUN_001fa6c0(D_L01_0015F5CC & 0x3F) - 32.0f) * 0.09817477f);
    s = s * 0.5f + 0.5f;
    for (g = 3; g >= 0; g--) {
        D_L01_001FBC80[g].glow = s;
    }
    enqueue_callback_2518(FUN_L01_002feb28, arg);
}
typedef struct {
    Vec4 home;
    f32 t;
    f32 radius;
} HoverVars;

typedef struct {
    u8 pad0[0x10];
    Vec4 pos;
    u8 state;
    u8 pad21[0x27];
    f32 rot_z;
    u8 pad4C[0x2C];
    HoverVars *vars;
    u8 pad7C[0x2A];
    s16 oclass;
} HoverMoby;

extern f32 FUN_001f99c0(f32);

void FUN_L01_002fed68(HoverMoby *m) {
    HoverVars *v;
    Vec4 *player;
    Vec4 off;
    f32 k;

    v = m->vars;
    switch (m->state) {
    case 0:
        qcopy(&v->home, &m->pos);
        v->t = 0.0f;
        m->state = 1;
        break;
    case 1:
        player = &hero.motion.pos;
        if (FUN_001f9b80(v, player) < v->radius &&
            FUN_001f99c0(m->pos.f[2] - player->f[2]) < 2.0f) {
            m->state = 2;
            if (m->oclass == 0x300) {
                FUN_0022da68(0, 0, m);
            }
        }
        break;
    case 2:
        v->t += 1.0f / FUN_001f96b0(20.0f);
        if (v->t >= 1.0f) {
            v->t = 1.0f;
            m->state = 3;
        }
        break;
    case 3:
        k = 1.1f;
        if (FUN_001f9b80(v, &hero.motion.pos) > v->radius * k &&
            FUN_001f9b80(v, D_L01_00167240) > v->radius * k) {
            m->state = 4;
            if (m->oclass == 0x300) {
                FUN_0022da68(0, 0, m);
            }
        }
        break;
    case 4:
        player = &hero.motion.pos;
        if (FUN_001f9b80(v, player) < v->radius &&
            FUN_001f99c0(m->pos.f[2] - player->f[2]) < 2.0f) {
            m->state = 2;
        } else {
            v->t -= 1.0f / FUN_001f96b0(20.0f);
            if (v->t <= 0.0f) {
                v->t = 0.0f;
                m->state = 1;
            }
        }
        break;
    }
    off.f[0] = FUN_001f9dc8(m->rot_z) * v->t * (m->oclass == 0x300 ? 2.0f : -2.0f);
    off.f[1] = FUN_001f9de0(m->rot_z) * v->t * (m->oclass == 0x300 ? 2.0f : -2.0f);
    off.f[2] = 0.0f;
    m->pos.f[0] = v->home.f[0] + off.f[0];
    m->pos.f[1] = v->home.f[1] + off.f[1];
}

#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l01_novalis/vendor_002FABE8.c: func_L01_00300C38), where it is exact; names translated to the US level program. */


extern char *FUN_L00_0025a420(void *, int, int);
extern char *FUN_L01_002ffa90_c(void *owner) __asm__("FUN_L01_002ffa90");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern float fast_cos(float);
extern float fast_sin(float);
extern float random_float_between(float, float);
extern int FUN_L00_00257b90(int lo, int hi);
extern int allocate_voice_for_target_entry(int, int, int);
extern int scale_game_frames(int);
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern void FUN_L00_0026ced0(void *, void *, int, int, float, int);
extern void add_vector_xyz(void *, void *, void *);
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");

void FUN_L01_002ff860(struct Moby *m) {
    char *d = (char *)m->pvars;
    char *t = FUN_L00_0025a420(m, 0x10000, 0);
    m->unkA4 = 0xFF;
    if (t != 0 && 0.0f < *(float *)(t + 0x2C)) {
        float v[4];
        float w[4];
        int n = random_integer_below(*(int *)(d + 4) - *(int *)d + 1) + *(int *)d;
        int k;
        if (n > 0) {
            do {
                n--;
            } while (n != 0);
        }
        allocate_voice_for_target_entry(0, 0, (int)m);
        for (k = 0x95; k >= 0;) {
            float a, b;
            *(OvlQuad *)v = 0;
            v[0] = -0.2f;
            v[2] = 1.2f;
            k--;
            add_vector_xyz(v, v, &m->pos);
            a = fast_cos(random_angle_radians());
            b = random_float_between(1.5f, 3.0f);
            a = a * (b * frame_time);
            w[0] = a;
            a = fast_sin(random_angle_radians());
            b = random_float_between(1.5f, 3.0f);
            a = a * (b * frame_time);
            w[1] = a;
            w[2] = 0;
            w[2] = random_float_between(w[2], 3.0f) * frame_time;
            a = random_float_between(125000.0f, 175000.0f);
            FUN_L00_0026ced0(v, w, 0x207F7F7F, 0x272727, a,
                             scale_game_frames(FUN_L00_00257b90(0x2D, 0x3C)));
        }
        FUN_L01_002ffa90_c(m);
        mark_moby_for_removal(m);
    }
}
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 state;
    u8 pad21[0xF];
    u8 b30;
    u8 b31;
    s16 h32;
    u8 pad34[4];
    u64 d38;
    u128 rot;
    u8 pad50[0x28];
    s32 *pvars;
} SpawnedMoby;
extern void *create_moby(s32 oclass) __asm__("FUN_0020c4f8");
extern void FUN_L00_00250df8();

SpawnedMoby *FUN_L01_002ffa90(SpawnedMoby *src) {
    SpawnedMoby *m;
    s32 *pv;

    m = create_moby(0x30B);
    if (m != 0) {
        m->b30 = 0x20;
        m->h32 = 0xFF;
        m->b31 = 1;
        m->state = 0;
        pv = m->pvars;
        m->d38 = src->d38;
        qcopy(&m->pos, &src->pos);
        qcopy(&m->rot, &src->rot);
        *pv = -1;
        FUN_L00_00250df8(m, -1);
    }
    return m;
}

typedef struct {
    s32 sound;
} SmokeVars;

typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0x58];
    SmokeVars *vars;
    u8 pad7c[0x44];
    u128 mtx[4];
} SmokeMoby;

extern int FUN_L00_0028d8c0(void *, int);
extern s32 FUN_0022da68(s32, s32, void *);
extern void FUN_001f9cf8(void *, void *, void *);
extern void FUN_001f9a10(void *, void *, void *);
extern int FUN_L00_00257b90(int lo, int hi);
extern void FUN_L00_0026ced0_u(void *, void *, u32, u32, f32, s32) __asm__("FUN_L00_0026ced0");

void FUN_L01_002ffb28(SmokeMoby *self) {
    SmokeVars *v;
    Vec4 pos;
    Vec4 vel;
    Vec4 tmp;
    f32 size;
    s32 i;

    v = self->vars;
    if (FUN_L00_0028d8c0(self, v->sound) == 0) {
        v->sound = FUN_0022da68(0, 4, self);
    }
    for (i = 0; i < 2; i++) {
        pos.q = 0;
        tmp.q = 0;
        pos.f[0] = -0.2f;
        pos.f[2] = 1.2f;
        tmp.f[0] = random_float_between(0.8f, 1.2f) * (frame_time * 3.0f);
        tmp.f[2] = random_float_between(0.8f, 1.2f) * (frame_time + frame_time);
        vel.q = tmp.q;
        FUN_001f9cf8(&vel, &vel, self->mtx);
        FUN_001f9a10(&pos, &pos, &self->pos);
        size = random_float_between(125000.0f, 175000.0f);
        FUN_L00_0026ced0_u(&pos, &vel, 0x207F7F7F, 0x272727, size,
                           FUN_001f96f8(FUN_L00_00257b90(0x2D, 0x3C)));
    }
}
typedef struct {
    u8 pad0[0x8];
    f32 f8;
    u8 padC[4];
    f32 f10;
    s32 timer;
    u8 pad18[4];
    f32 spin;
} OrbVars;
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[0xC];
    f32 scale;
    u8 b30;
    u8 b31;
    s16 h32;
    u8 pad34[0xC];
    s32 w40;
    u8 pad44[4];
    f32 rotz;
    u8 pad4C[0x2C];
    OrbVars *pvars;
} OrbMoby;
extern void FUN_L00_0025d1b8(OrbMoby *);
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");

OrbMoby *FUN_L01_002ffcd0(u128 *pos, f32 scale) {
    OrbMoby *m;
    OrbVars *pv;

    m = create_moby(0x313);
    if (m != 0) {
        pv = m->pvars;
        FUN_L00_0025d1b8(m);
        m->w40 = 0;
        m->h32 = 0x40;
        m->b30 = 0xFF;
        m->scale = m->scale * scale;
        m->rotz = random_angle_radians();
        qcopy(&m->pos, pos);
        qzero(pv);
        pv->f8 = -frame_time;
        pv->timer = 0x78;
        pv->f10 = frame_time_sq * 15.0f;
        pv->spin = random_float_between(0.0031415929f, 0.062831856f);
        FUN_L00_00250df8(m);
    }
    return m;
}



#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/l01_novalis/vendor_002FABE8.c: func_L01_00301198), where it is exact; names translated to the US level program. */

extern char *FUN_L00_002d7e90(void *, float);
extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern f32 fast_sin(f32) __asm__("func_001F9DE0");
extern f32 random_angle_radians(void) __asm__("func_00213308");
extern f32 random_float_between(f32, f32) __asm__("func_002132A8");
extern int D_L01_001612D8; /* no foreign declaration */
extern int D_L01_001612D0; /* no foreign declaration */
extern float D_L01_001742E8 __attribute__((section(".data"))); /* no foreign declaration */
extern int FUN_001efa68(void *, void *, int, void *, void *);
extern int FUN_001f0b58(void);
extern int FUN_L00_00257b90(int lo, int hi);
extern int allocate_voice_for_target_entry_alt(int, int, int) __asm__("FUN_0022da68");
extern int tick_countdown_32_alt(int *) __asm__("FUN_001f9740");
extern s32 random_integer_below(s32) __asm__("func_00213260");
extern void FUN_L00_0026f548(void *, void *, int, int);
extern void FUN_L00_002a3ec8(int, int, int, float, float, float, float);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void mark_moby_for_removal(void *) __asm__("func_0020C828");

/* Per-frame update of a falling debris moby: moves it, bursts into particles when it hits the ground, and removes it when its timer runs out. */
void FUN_L01_002ffdc0(struct Moby *moby) {
    float next_pos[4];
    float effect_pos[4];
    float particle_vel[4];
    char *data = (char *)moby->pvars;
    *(float *)(data + 8) -= *(float *)(data + 0x10);
    moby->rot.x += *(float *)(data + 0x1C);
    add_vector_xyz(next_pos, &moby->pos, data);
    if (FUN_001efa68(&moby->pos, next_pos, 2, 0, 0)) {
        int i;
        char *effect;
        if (!FUN_001f0b58()) {
            if (*(int *)(data + 0x18) == 0) {
                allocate_voice_for_target_entry_alt(0, 0, (int)moby);
            }
            FUN_L00_002a3ec8(D_L01_001612D0, D_L01_001612D8, 1, moby->pos.x, moby->pos.y, 0.5f, -0.35f);
            {
                float pos_unit = frame_time;
                float pos_unit2 = frame_time_sq;
                *(int *)(data + 0x18) = 1;
                *(int *)(data + 0x14) = 0x78;
                *(int *)(data + 0x1C) = 0;
                *(float *)(data + 8) = pos_unit * -1.5f;
                *(float *)(data + 0x10) = pos_unit2 * 0.8f;
            }
            effect_pos[0] = moby->pos.x;
            effect_pos[1] = moby->pos.y;
            effect_pos[2] = D_L01_001742E8;
            effect = FUN_L00_002d7e90(effect_pos, 2.0f);
            if (effect != 0) {
                effect[0x23] = 0x70;
            }
            for (i = 0; i < 16; i++) {
                float a = random_angle_radians();
                float r = random_float_between(frame_time * 0.0f, frame_time * 3.0f);
                particle_vel[0] = fast_cos(a) * r;
                particle_vel[1] = fast_sin(a) * r;
                particle_vel[2] = random_float_between(frame_time * 3.0f, frame_time * 6.5f);
                {
                    int lifetime = FUN_L00_00257b90(0x5A, 0x78);
                    FUN_L00_0026f548(effect_pos, particle_vel, random_integer_below(2), lifetime);
                }
            }
        } else {
            mark_moby_for_removal(moby);
            return;
        }
    }
    qcopy(&moby->pos, next_pos);
    if (*(int *)(data + 0x18) != 0) {
        moby->scale *= 0.99f;
    }
    if (tick_countdown_32_alt((int *)(data + 0x14))) {
        mark_moby_for_removal(moby);
    }
}
typedef struct {
    u8 pad0[0x10];
    s32 w10;
    u8 pad14[0x10];
    f32 f24;
} MobyClass;
typedef struct {
    u8 pad0[0x20];
    f32 f20;
    u8 pad24[0x14C];
    s32 w170;
    u8 pad174[0xB0];
    f32 f224;
    u8 pad228[0x28];
    f32 f250;
} ClonedVars;
typedef struct {
    u8 pad0[0x10];
    u128 pos;
    u8 pad20[4];
    MobyClass *mclass;
    u8 pad28[4];
    f32 scale;
    u8 b30;
    u8 b31;
    s16 h32;
    u16 flags;
    u8 pad36[2];
    u64 d38;
    u128 rot;
    u8 pad50[0x28];
    void *pvars;
    u8 pad7C[0x18];
    s32 w94;
} ClonedMoby;
extern void FUN_L00_002591d0(ClonedMoby **, s32, s32, s32);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
typedef struct {
    s32 src_id;
    u8 pad4[4];
    s32 count;
} SpawnerVars;
typedef struct {
    u8 pad0[0x60];
    u8 path[0x18];
    s32 w78;
    s32 w7C;
    s32 w80;
    s32 w84;
    f32 f88;
    u8 pad8C[0x24];
    f32 fB0;
    f32 fB4;
    u8 padB8[0x198];
    f32 f250;
} CloneAiVars;
typedef struct {
    u8 pad0[0x10];
    f32 x;
    f32 y;
    u8 pad18[8];
    u8 state;
    u8 pad21[0x57];
    void *pvars;
} SpawnerMoby;
typedef struct {
    u8 pad0[0x80];
    f32 x;
    f32 y;
} PlayerPosView;
extern s32 FUN_L01_0026e008(s32, s32);
extern ClonedMoby *FUN_L01_00302328(ClonedMoby *);
extern f32 FUN_001f9e90(f32, f32);
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern void FUN_L00_0025c558(void *, void *, s32, s32, s32, f32);
extern s32 D_L01_00161E90 __attribute__((sda));

void FUN_L01_003021b8(SpawnerMoby *m) {
    SpawnerVars *v = m->pvars;
    SpawnerMoby *n;
    CloneAiVars *nv;
    f32 k;

    switch (m->state) {
    case 0:
        m->state = 1;
        break;
    case 1:
        if (v->src_id < 0) {
            break;
        }
        if (FUN_L01_0026e008(v->src_id, 0xC) != 0) {
            break;
        }
        if (v->count >= D_L01_00161E90) {
            break;
        }
        v->count++;
        n = (SpawnerMoby *)FUN_L01_00302328((ClonedMoby *)m);
        if (n != 0) {
            nv = n->pvars;
            k = 0.8f;
            nv->w84 = 8;
            nv->w80 = truncate_float_to_s32(nv->f250 * k * 1024.0f);
            nv->f88 = nv->f250 * k;
            nv->fB0 = 7.0f;
            nv->fB4 = 13.0f;
            nv->w78 = 0;
            nv->w7C = 0;
            FUN_L00_0025c558(
                n, nv->path, 5, 8, 0,
                fast_add_rotations(FUN_001f9e90(hero.motion.pos.f[0] - m->x, hero.motion.pos.f[1] - m->y),
                                   3.1415927f));
            n->state = 9;
        }
        break;
    }
}

ClonedMoby *FUN_L01_00302328(ClonedMoby *src) {
    ClonedMoby *m;
    ClonedVars *v;

    m = 0;
    FUN_L00_002591d0(&m, *(s32 *)src->pvars, 0, 0);
    v = m->pvars;
    m->b30 = 0x80;
    m->h32 = 0x80;
    m->d38 = src->d38;
    m->b31 = 1;
    m->w94 = m->mclass->w10;
    m->flags |= 0x1020;
    m->scale = m->mclass->f24;
    {
        ClonedMoby *d = m;
        qcopy(&d->pos, &src->pos);
        qcopy(&d->rot, &src->rot);
    }
    v->f20 = 3.0f;
    v->f250 = 1.0f;
    v->w170 = truncate_float_to_s32(819.2f);
    v->f224 = 30.0f;
    FUN_L00_00250df8(m);
    return m;
}
void *FUN_L00_0025a420_u(void *, s32, s32) __asm__("FUN_L00_0025a420");
void mark_moby_for_removal(void *) __asm__("FUN_0020c828");

void FUN_L01_00307c48(void *self) {
    u8 *p;

    p = FUN_L00_0025a420_u(self, 0x10000, 0);
    if (p != NULL && *(f32 *)(p + 0x2C) > 0.0f) {
        mark_moby_for_removal(self);
    }
}
